### ISSUE TITLE
Handle moderators that can’t be removed b/c they predate the current user

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1004]
Moderators that predate you being added as a moderator cannot be removed by you via the reddit api. So we need to either:

- [ ] Hide the remove button if there is data in the reddit moderator data that can inform us of who you can/can't do this to
- [ ] Message an error when the remove fails for this reason

**Comment by noisecapella** [comment]
From the source it looks like we just check the user creation date: https://github.com/mitodl/reddit/blob/stable/r2/r2/models/subreddit.py#L955

It looks like the date is obtained with the rest of the moderator data so there shouldn't need to be extra requests for the data
