### ISSUE TITLE
remove flash when updating the page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#102]
Seen in our meeting Wednesday afternoon

**Comment by rhysyngsun** [comment]
This is caused by the `<Loading/>` component due to new api requests, we probably need a smarter component that is actually tracking the presence of data, not the request status.

**Comment by noisecapella** [comment]
One bug I found: If you are on the front page and click a link to see comments of a post, the comments don't load. You need to refresh the page to see the comments

**Comment by rhysyngsun** [comment]
Hmm, I think I know why that's happening.
