### ISSUE TITLE
Update edit profile form to match design

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1049]
See https://invis.io/9EN908ZQPAX#/311617870_Edit_Profile

### acceptance criteria
- [x] Update field labels and hints
- [x] move full name to right of profile image

### out of scope
- styling, which should update site-wide

**Comment by mbertrand** [comment]
@pdpinch how does this look:

<img width="842" alt="screen shot 2018-08-14 at 4 36 14 pm" src="https://user-images.githubusercontent.com/187676/44118135-2958d270-9fe3-11e8-915b-a248e8d70e66.png">

**Comment by pdpinch** [comment]
Sorry I didn't get back to you in time -- this is exactly what I had in mind though. 

> @pdpinch <https://github.com/pdpinch> how does this look:
