### ISSUE TITLE
Detail page: Anonymous view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1051]
Anonymous users should be able to see the detail page, but when they interact with it they should get a pop-up encouraging them to log in or create an account. 

Design at https://invis.io/9EN908ZQPAX#/314585748_Detail_Link_Not_Logged

### acceptance criteria
- [x] protect upvote, similar to channel listing page
- [ ] protect comment form
- [x] protect follow button
- [ ] protect comment reply button 
- [ ] anything else?

**Comment by pdpinch** [comment]
Blocked waiting for updated designs

**Comment by pdpinch** [comment]
We're still working out some of the fine details about the design, but in general it will be similar to the "pop-up" for sharing a URL. I expect it will have a button to log in / sign up and a close button.

**Comment by mbertrand** [comment]
The following are not displayed at all on a post detail page for anonymous users: comment form, comment reply form, follow button.  The only thing mentioned in the checklist above that is displayed is the upvote (& downvote) button.  Should that change?

**Comment by aliceriot** [comment]
Yeah, I'm working on the reply stuff and refactoring a lot of stuff on the comment component, might be best to hold off on that to avoid merge conflicts or duplicate work

**Comment by mbertrand** [comment]
Thanks Alice, I will start on creating the login popup and attach it to the vote and follow buttons for now, leave the comment changes for later.

**Comment by aliceriot** [comment]
we also have this existing popup / tooltip thing, which I'm guessing we'll want to get rid of:

![login-popup](https://user-images.githubusercontent.com/6207644/44281399-a32e2480-a225-11e8-8ba4-8128b656de23.png)

**Comment by pdpinch** [comment]
Yes, we would like to replace that -- on the detail page and on the listing page.
