### ISSUE TITLE
Detail page: when using embedly with an iframe, include link to the source URL

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1052]
Currently, when we embed certain content, the "read more" link is omitted and users don't have an obvious way to get to the source material. This seems to happen in paritcular when the embed.ly API returns an iframe. 

We should include a link to the source URL. It should appear after the title in parentheses, like "mit.edu" in this mock-up: https://projects.invisionapp.com/share/DQNIO5IG2XA

**Comment by pdpinch** [comment]
waiting on design

**Comment by aliceriot** [comment]
one complication here is that, for some reason, embedly doesn't return the url for the original content in the 'rich' type response. So, for instance with a google doc, we'd need to pass in the original url to the embedly component as well as the embedly object itself.

As a basic design thing, though, one simple option would be to copy the link we show for 'link' type responses:

![fjfjfjffjasdf](https://user-images.githubusercontent.com/6207644/44100676-98bf6bcc-9fb3-11e8-8d53-3d85e5d2e9e9.png)

**Comment by mbertrand** [comment]
@pdpinch, currently I've added the domain & link icon next to the title for all link posts regardless of what embedly is doing, not just if embedly is using an iframe, is that okay?  I think it would be more consistent.

PS The title already links directly to the source URL.

**Comment by pdpinch** [comment]
Ok. If we find it’s redundant to the “read more” link, we can remove that.
