### ISSUE TITLE
members widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1054]
Display a simple widget in the right rail with a list of members' profile images, and a count of the total number of members. 

<img width="290" alt="screenshot 2018-08-13 14 56 31" src="https://user-images.githubusercontent.com/430126/44051890-190ca2e6-9f09-11e8-947a-44baf0948949.png">

Blocked waiting for a design of viewing all the members. 

Note: the members api is not paginated and doesn't support anonymous access

### related issues
#1063 updates to members API

**Comment by rhysyngsun** [comment]
See https://github.com/mitodl/open-discussions/issues/1249#issuecomment-424383077 for implementation issues that came up in planning

**Comment by pdpinch** [comment]
This was addressed by #1803
