### ISSUE TITLE
Handle account already in use errors

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1057]
This happens when the user already has a OD session but tries to login with an account (MM or touchstone) that is linked to another user:

https://sentry.io/mit-office-of-digital-learning/discussions/issues/635378179/
https://sentry.io/mit-office-of-digital-learning/discussions/issues/621321627/

**Comment by rhysyngsun** [comment]
Sentry issue: [DISCUSSIONS-9D](https://sentry.io/mit-office-of-digital-learning/discussions/issues/635378179/)

**Comment by pdpinch** [comment]
Need to decide whether to show user an error, or just abort the new login attempt.

**Comment by pdpinch** [comment]
I don't suppose it's possible to abort the new login attempt and throw up a snack bar with "You are logged in as <full name>." ?

**Comment by pdpinch** [comment]
I think that would work fine. So this issue should include creating the error page and also some front-end work to take the message and display it as a banner (not a snack bar)?

**Comment by rhysyngsun** [comment]
@pdpinch could you clarify which of those approaches you would like?

**Comment by pdpinch** [comment]
Sorry I wasn't clear. I prefer "send them to a generic url with the conf var `LOGIN_ERROR_URL` along with a `message` parameter of something like `You are already logged in with email [email]`.

**Comment by rhysyngsun** [comment]
@pdpinch the message is driven by the string representation of the exception that was raised. In this case it will be "This micromasters account is already in use." We could customize the message by overriding python social auth's implementation, but we'll need to keep our copy of that implementation up-to-date if it ever changes upstream.

**Comment by pdpinch** [comment]
I think we can live with that, although I don't understand why it says "micromasters account" ? Is that the exception if it's a collision between an email account and a Touchstone account?

**Comment by rhysyngsun** [comment]
@pdpinch that's if they tried to login via MM if already logged into OD with another account. For touchstone accounts, it will unfortunately say "saml account", because the backend name is saml. We could probably change that by subclassing the saml auth provider with `"touchstone"` as the name.

**Comment by pdpinch** [comment]
For this issue, it's fine to stick with "saml account" If we find that a lot of users are encountering this error and that the message is confusing, we can update at that time.
