### ISSUE TITLE
Login: Update UI for recognized email to include micromasters & touchstone login

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1058]
PR #1039 changed the login flow to present the user with a greeting, profile image, and email address when they enter a recognized email address into the login form. We want to do something similar if the email matches a Micromasters- or Touchstone-authenticated user. We will show them a the same greeting/image/email, and under that we will show a button/link that redirects to Micromasters or a Touchstone login link button respectively. 

See [MIT OPEN onboarding google doc for guidance](https://docs.google.com/document/d/1_sD0-ng7PsYmvmmOjoTYcguygLVctx2RZqUbJsDPvR8)

**Comment by rhysyngsun** [comment]
Currently [this pipeline code](https://github.com/mitodl/open-discussions/blob/master/authentication/pipeline/user.py#L173-L199) returns an appropriate response for micromasters, we should update that to support all non-email providers, then update the frontend to use that.

**Comment by rhysyngsun** [comment]
That's _probably_ as simple as changing `MicroMastersAuth.name` to `backend.name`

**Comment by pdpinch** [comment]
I added a link to the google doc to the description
