### ISSUE TITLE
Widgets: updates to members API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1063]
For the channel members widget (#1054), we'll need to update the members API:

### acceptance criteria:
- [ ] return member's profile image (and name and headline??)
- [ ] allow anonymous access
- [ ] add optional pagination, since we only need the first few for the channel widget itself

**Comment by rhysyngsun** [comment]
See https://github.com/mitodl/open-discussions/issues/1249#issuecomment-424383077 for implementation issues that came up in planning

**Comment by pdpinch** [comment]
This was addressed as part of #1936
