### ISSUE TITLE
Sign up: add recaptcha

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1065]
As an admin, I'd like to avoid having a bunch of fake accounts created by bots.

We can add the Google recaptcha tool to the signup page.

**Comment by mbertrand** [comment]
[react-google-recaptcha](https://www.npmjs.com/package/react-google-recaptcha) seems like a good option.

Will need to [get a recaptcha site key](https://www.google.com/recaptcha/admin) @blarghmatey @shaidar (or add discussions domains to an existing site key)
