### ISSUE TITLE
Channel settings: add snackbar when adding / removing users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1068]
As a channel moderator, it would be nice to get a confirmation message that my action to add or remove a user from a channel was successful. 

We can use a simple snackbar for the following actions:

- [ ] add moderator
- [ ] remove moderator
- [ ] remove myself as a moderator
- [ ] add contributor
- [ ] remove contributor

**Comment by noisecapella** [comment]
@pdpinch Did we decide to have the snackbar when the user is removed as well?

**Comment by noisecapella** [comment]
Do we have text for the snackbar messages or should I come up with something myself?

**Comment by noisecapella** [comment]
Also what is 'add member' and 'remove member'?

**Comment by pdpinch** [comment]
Oops. There is no adding/removing members. Just moderators and contributors. I've removed those two boxes from the description.
