### ISSUE TITLE
erroneous permission error

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1074]
To reproduce:

 - Go to a URL you don't have permission to. I went to https://discussions.odl.mit.edu/c/mm_scm_holders/iw/credential_holders_fourth_thursdays_live_video/ which gives me a 'Stop! Who goes there?' message
 - Click a channel on the sidebar
 - Click a post within that channel
 - You should see a 'Stop! Who goes there?' message even though you have permission to view the post. If you refresh the page it will work fine.

**Comment by mbertrand** [comment]
@noisecapella can you still reproduce this error?  I followed the steps above but didn't get the permission error on the last step.

**Comment by noisecapella** [comment]
I can't reproduce it either, closing
