### ISSUE TITLE
Channel Settings: Headline

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1094]
As a channel owner, I'd like to be able to set a "headline" for my channel -- a short description that will appear below the channel title. 

In this mock-up ([InVision](https://invis.io/9EN908ZQPAX#/311617712_Channel_Settings_Entrance)|[Zeplin](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b60e6947d6f9ad509224cee)), the headline is the text "An online community for climate learning, discussion, and collaboration."

The headline field should be part of the appearance tab of Channel Settings. It will need a character limit of 80 characters, so it can reasonably fit in the header. 

I think we can use the `public_description` field in reddit for this purpose.

**Comment by rhysyngsun** [comment]
I _think_ at one point we were putting data in here, but then switch to `description` for the sidebar. Might want to scrub production channels to make sure there isn't anything lengthy in there.

**Comment by pdpinch** [comment]
I updated the character limit in the description.
