### ISSUE TITLE
add authentication/authorization to create_channel API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#111]
The MicroMasters app will need a privileged API to create channel in open_discussions.

We will use a shared secret for authentication and authorization of the MicroMasters app.

**Comment by amir-qayyum-khan** [comment]
So do we need to create a staff user for MM in open discussions, then it can create channels

```curl -X POST -u USERNAME:PASSWORD "http://<open_discussions_url>:8063/api/v0/channels/" \
  -H "Content-Type: application/json" \
  -d '{"title": "Test Channel", "name": "test_channel", "public_description": "This is a test channel", "channel_type": "public"}'
```

**Comment by rhysyngsun** [comment]
We specifically want this only on the HTTP verbs that modify channels, specifically `POST`, `PUT`, and `PATCH`.  Other verbs should allow the current auth mechanism because it'll otherwise break the UI. Don't worry about the MM piece right now, it's not a factor in this issue.
