### ISSUE TITLE
Move reported posts and comments interface into channel settings ui

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1125]
As a channel moderator, I expect all my channel setting to be in the same place. 

Instead of linking to the reported content from a sidebar widget, we can put them under a tab in the channel settings UI. 

see https://invis.io/9EN908ZQPAX#/316064703_Channel_Settings_Reported_Content

The reported posts and comments should use the standard post and comment card component, as they do now.

**Comment by pdpinch** [comment]
Blocked waiting for some design tweaks

**Comment by pdpinch** [comment]
Design mock-ups should be complete now.

**Comment by noisecapella** [comment]
@pdpinch Should the `(5)` in the tab title in the mockup be visible for all tabs? We won't have that information without explicitly fetching it from the API so we would need to do it for each tab on the page. I don't think it's a large extra burden but wanted to double check

**Comment by pdpinch** [comment]
We can skip the count. It's not worth (any) extra effort.

**Comment by noisecapella** [comment]
Another question, I noticed that we're moving the reported information from 
![screenshot from 2018-09-11 16-02-21](https://user-images.githubusercontent.com/863262/45384467-24d26180-b5dc-11e8-8349-03573acd9158.png)

to
![screenshot from 2018-09-11 16-00-56](https://user-images.githubusercontent.com/863262/45384474-2ac84280-b5dc-11e8-993c-92c93d298d9c.png)

If the moderator is viewing it on the home page would they see this information in the menu or in the post summary card?

**Comment by pdpinch** [comment]
The post summary card should be consistent everywhere, so the "Reported xx times" information should be moved to the card and out of the menu.

**Comment by noisecapella** [comment]
@pdpinch Is the 'How to deal with reported content' tab part of this?

**Comment by noisecapella** [comment]
![screenshot from 2018-09-12 14-40-51](https://user-images.githubusercontent.com/863262/45446036-ea2efe80-b699-11e8-89b4-08980e66d580.png)

The capitalization is inconsistent IMO. How should I fix it? And is 'Show this thread' meant to be what 'permalink' is now?

**Comment by pdpinch** [comment]
I'll open a separate issue for "How to deal with reported content" -- it's a good idea, but l at least have to review the text. 

I agree about the capitalization. In the interested of consistency, I recommend capitalizing just the first word. 

You are correct "Show this thread" = permalink. Most users don't seem to know what that means.
