### ISSUE TITLE
Profile: posts and comments feed

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1126]
As a user, I'd like to be able to easily see the history of posts and comments made by another user. 

We will display a feed of posts and comments on users' profile pages. 

See https://invis.io/9EN908ZQPAX#/316071207_Profile_With_Comments

### questions
- Can we do infinite scroll, similar to the channel listing?
- Is there a PRAW API, or should we use elasticsearch?

### acceptance criteria
- [ ] API for fetching list of user's posts, comments
- [ ] tabbed UI
- [ ] count of posts and comments

**Comment by rhysyngsun** [comment]
@pdpinch yes, there is a praw API for this: https://praw.readthedocs.io/en/latest/code_overview/models/redditor.html#praw.models.Redditor

It behaves similarly to the subreddit listing API so we could probably reuse most of our channel listing code for displaying the posts.

Similarly with the comment listing.

For both, we'll need to decide if we want to expose things like sorting and if not, what the default is (hot, new, etc).
