### ISSUE TITLE
Channel settings: CTA button and styling tweaks to image upload UI

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1127]
As a user, it needs to be a little clearer how and what I am supposed to upload for the channel appearance.

See https://invis.io/9EN908ZQPAX#/316069757_Channel_Settings_Appearance_Upload_Cover_Image

**Comment by rhysyngsun** [comment]
@pdpinch I think this is somewhat blocked by completion of the style refactor, right?

**Comment by pdpinch** [comment]
This is blocked by #1153

**Comment by aliceriot** [comment]
what changes are related to this ticket, as opposed to #1203

**Comment by pdpinch** [comment]
This issue was specifically about the text and button that appears after you click to add an avatar or a channel banner, i.e. the "drag and image here or click to select an image" part.

**Comment by aliceriot** [comment]
@pdpinch question on this, currently we have a desktop and mobile photo upload message. the mobile one looks like this:

![mobileversionffffjfjfj](https://user-images.githubusercontent.com/6207644/46749765-75dd8000-cc84-11e8-91d3-f100ad2ead19.png)

I don't see a design for a mobile upload - should we just do a button, as in the design linked above, with 'Click to select an image' on it?

**Comment by pdpinch** [comment]
That’s OK for now. We may want to come back to this to make it look nicer. But I think we can get away with this for now.
