### ISSUE TITLE
Channel settings: randomize default channel avatar images

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1128]
As a staff member, when I create a new channel (and it doesn't yet have a channel banner or avatar) I'd like the default avatar image gradients (just the avatar) to be randomized, so its easier to tell the difference between channels. 

Gradients that we can use (presumably, the reverse is also acceptable):
 
```
#61BB3A & #02A0C6
#03152D & #6B829A
#E01238 & #D97422
#1CC5D9 & #35C880
#3023AE & #C86DD7
```

**Comment by rhysyngsun** [comment]
Probably straightforward enough to seed a RNG with the channel name and use that to generate colors since the name is immutable. That'd give us deterministic but different colors without having to store anything in the DB.

**Comment by pdpinch** [comment]
@loemerdotcom can you pool of 5 or 6 good gradients that we can randomly choose from?

**Comment by pdpinch** [comment]
I updated the description with gradient values from @loemerdotcom
