### ISSUE TITLE
Error uploading profile image in Edge and iOS Safari

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1140]
### steps to reproduce:

1. Edit profile image in MS Edge
2. Choose image; Image display in browser
3. Crop and click Save button

### Expected Behavior

Profile image is saved

### actual behavior 

- User gets "Error uploading Image" message
- API returns a 400 error on the patch request (see screenshot)

![win10_edge_17 0-1](https://user-images.githubusercontent.com/430126/44800889-9397cf80-ab85-11e8-8c10-5d2927af312d.jpg)

**Comment by pdpinch** [comment]
I'm getting a similar error from Safari on iOS 9, but not on Safari desktop. Unfortunately, it doesn't look like browserexchange has JavaScript console support for mobile browsers. 

![bs_realios_mobile_iphone 6s-9 0](https://user-images.githubusercontent.com/430126/44803280-fee4a000-ab8b-11e8-85c2-21cbc082cefb.jpg)

**Comment by mbertrand** [comment]
For Edge, the error is `Object doesn't support object or method toBlob` (https://github.com/fengyuanchen/cropperjs/issues/172)

**Comment by mbertrand** [comment]
Likely the same issue in iOS: https://github.com/mosch/react-avatar-editor/issues/170
