### ISSUE TITLE
Login/signup card sizes should be standardized

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1147]
The card components in the login/signup flow do not have a set width, resulting in an occasionally wonky UI (these screenshots were taken while I was working on a separate issue, so please ignore the back button)

![ss 2018-08-30 at 14 16 39](https://user-images.githubusercontent.com/14932219/44872135-b77d1300-ac62-11e8-9551-620a0dd90f4f.png)
![ss 2018-08-30 at 14 16 46](https://user-images.githubusercontent.com/14932219/44872134-b77d1300-ac62-11e8-95f1-5febcadd4b22.png)
![ss 2018-08-30 at 14 17 37](https://user-images.githubusercontent.com/14932219/44872133-b77d1300-ac62-11e8-8248-cb76904aeb53.png)

**Comment by pdpinch** [comment]
According to @loemerdotcom this card should stretch across columns 4-9. @aliceriot added the material grid in #1110 so this should just be a CSS change.

**Comment by pdpinch** [comment]
I believe this will be part of #1153
