### ISSUE TITLE
Removing a post causes a console error

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1157]
To reproduce, go to the channel page, remove the post. You should see a snackbar saying that the post was removed. If you open the browser console you should see an error message and a stack trace saying `TypeError: "post is null"`

It appears like the post is successfully removed. If you refresh the channel the post won't be there anymore

**Comment by pdpinch** [comment]
Do you mean “remove” the post, or something else?

**Comment by aliceriot** [comment]
do you mean 'removing' a post? I tried to repro this with deleting and didn't see an issue, but I do see the described error when 'removing' a post from the channel page.

**Comment by noisecapella** [comment]
Sorry I didn't see this earlier. Yes it's only removing a post, which means only moderators would see the console error
