### ISSUE TITLE
Hide scrollbar for side navigation

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1170]
The sidebar doesn't look right with a scrollbar. 

Many users have scrollbars turned off for all scrollable regions, but we'd like to hide the scrollbar even for users who haven't set them to be hidden (see YouTube.com for example)

**Comment by pdpinch** [comment]
Maybe YouTube just changes the CSS overflow setting on hover?

**Comment by rhysyngsun** [comment]
I took a quick stab at this because i thought it'd be easy, but I found the overflow-y: scroll on hover to be unreliable in chrome (random chance that you're unable to scroll until you mouse out and hover again).

**Comment by pdpinch** [comment]
I think there are some react-friendly solution to this out in the wild.

**Comment by aliceriot** [comment]
It looks like that is the approach youtube is using, although there's a lot of CSS going on so I'm not sure how exactly they have dealt with possibly unreliable aspects of it

**Comment by gsidebo** [comment]
Reopening due to bug

**Comment by pdpinch** [comment]
@gsidebo did this get fixed by #1273?
