### ISSUE TITLE
Feature flag for branding

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1178]
We would like to be able to preview what the new branding (logo and title) will look like on the CI and RC servers without releasing it to production yet. 

### acceptance criteria:
- [x] create, or recruit an existing, feature flag for MIT Open branding
- [x] put the logo in the top left nav behind the flag
- [x] put the URL of the "terms of service" links behind the flag
- [x] put the logos and footers for notification emails behind the flag

### related issues
- #985 MIT Open Terms of Service
- #1177 Link "MIT" in footer to MIT home page
- #1066 Update email templates

### out of scope
- verification emails only exist for MIT Open

**Comment by rhysyngsun** [comment]
@pdpinch url for terms of service can just use the existing `AuthenticatedSite.tos_url` field.

**Comment by pdpinch** [comment]
With #1230 fixed, I think we can close this?

**Comment by rhysyngsun** [comment]
@pdpinch yup!
