### ISSUE TITLE
Restore channel description form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1188]
Originally, the pencil/edit icon on the channel description card was used for editing the channel description (`description` in reddit). 

We later started using the pencil/edit icon on the channel description card as a link to the Channel Settings when we did not have an edit button in the left nav. 

Since that button has been added, the pencil/edit icon can go back to its original purpose.

**Comment by mbertrand** [comment]
@pdpinch what was the original purpose of the pencil/edit icon? Go directly to the appearance tab of settings?
