### ISSUE TITLE
comments API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#12]
create API for comments

- [ ] Create
- [ ] List
- [ ] Edit
- [ ] Delete ?

**Comment by rhysyngsun** [comment]
Blocking pending decision on how we want to handle the nested nature of comments.

**Comment by Ferdi** [comment]
@rhysyngsun  What is to be decided ?

**Comment by pdpinch** [comment]
Was this closed by 8185646?

**Comment by rhysyngsun** [comment]
Yes
