### ISSUE TITLE
JS code formatting proposal

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#120]
Currently we have our line-width set to 120 characters. Prettier (the JavaScript code formatter) uses this line width to figure out how much to fit on one line. I kinda think that 120 characters is too wide, it results in things like this:

```js
      <aside className="mdc-temporary-drawer mdc-typography" ref={div => (this.drawerRoot = div)}>
// or
const shouldLoadData = R.complement(R.allPass([R.eqProps("postID"), R.eqProps("channelName")]))
```

I'd like to propose we change the setting to the standard 80 characters instead, which would result in the more-manageable:

```js
      <aside
        className="mdc-temporary-drawer mdc-typography"
        ref={div => (this.drawerRoot = div)}
      >
// or
const shouldLoadData = R.complement(
  R.allPass([R.eqProps("postID"), R.eqProps("channelName")])
)
```

and also make it easier to look at two files side-by-side without having to scroll horizontally. thoughts? @rhysyngsun @noisecapella

**Comment by rhysyngsun** [comment]
I'm in favor of that, those long lines are pushing it a bit. I'd want to skim a diff to see if there's any obvious issues with that particular value, though.

**Comment by aliceriot** [comment]
Sure, I'll open a quick PR to test it out

**Comment by aliceriot** [comment]
https://github.com/mitodl/open-discussions/pull/121

**Comment by rhysyngsun** [comment]
yeah, I think that formatting in the PR is a big improvement. could @gsidebo weigh in too since he's looked at quite a bit of the code too?

**Comment by aliceriot** [comment]
I'm in favor of doing this, after I merge #118, if there are no objections.

**Comment by gsidebo** [comment]
For it!
