### ISSUE TITLE
Make UI consistent between post composition and post editing

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1201]
The submit/cancel controls are very different between the post composition and post editing UI (screenshots taken on #1153 PR branch)
 
![ss 2018-09-17 at 17 41 09](https://user-images.githubusercontent.com/14932219/45651961-091a0000-baa1-11e8-9518-7d432d4eafef.png)
![ss 2018-09-17 at 17 41 19](https://user-images.githubusercontent.com/14932219/45651966-0ae3c380-baa1-11e8-9d7d-1a3179152674.png)

**Comment by aliceriot** [comment]
this should be fixed now, although the post editing controls may need to be fixed to be right-aligned for consistency, depending on what @loemerdotcom thinks

**Comment by aliceriot** [comment]
![whwheheherere](https://user-images.githubusercontent.com/6207644/45760410-fc5bf000-bbf7-11e8-9bda-51aedd24caf8.png)

^^ current appearance

**Comment by pdpinch** [comment]
I think this is good for now.
