### ISSUE TITLE
make left nav styling same as Zeplin

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1209]
Currently:

<img width="383" alt="screen shot 2018-09-19 at 8 24 33 am" src="https://user-images.githubusercontent.com/430126/45753028-7a62cb80-bbe5-11e8-81b6-baba054762d7.png">

Spacing and text styling should be the same as: https://zpl.io/2EAZJpY

### acceptance criteria:
- [x] Compose button font styling
- [x] More white space between elements and above home
- [x] rounded channel avatars (see Zeplin)

**Comment by aliceriot** [comment]
how this look?

![navfixes](https://user-images.githubusercontent.com/6207644/46023651-0e83d580-c0b3-11e8-89a3-879bdfc44aae.png)

**Comment by aliceriot** [comment]
@loemerdotcom

**Comment by pdpinch** [comment]
- fonts look good. 
- I know the outline home icon isn't an option. @loemerdotcom when you get a chance, can you update the mocksup to use the solid home icon
- I feel like I can see a slight drop shadow, in particular on the bottom edge of the last two channel avatars -- that's not intentional is it?
- out of scope, but I think Ferdi would like solid colors instead of the gradients for the channels with no image
