### ISSUE TITLE
Users API: create profile if it doesn't exist on PATCH

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#122]
There's a possibility the profile doesn't exist, we should `get_or_create` it to be safe.

[See discussion](https://github.com/mitodl/open-discussions-client/pull/1#discussion_r135793315)

**Comment by pdpinch** [comment]
Is this a partial solution to #184 ?

**Comment by rhysyngsun** [comment]
I'm not sure what #184 is about exactly, this was basically about making this code more failure-proof/idempotent: https://github.com/mitodl/open-discussions/blob/master/profiles/serializers.py

**Comment by noisecapella** [comment]
Wouldn't the `PATCH` require the username to be specified, which would require that a `POST` was done previously?

**Comment by rhysyngsun** [comment]
yeah, actually, and that is wrapped in atomic, so we should never have a user and no profile unless something whacky happened and we'd want to know. I'll close this then.
