### ISSUE TITLE
Post form: grey out post button when choosing post type

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1237]
As implemented, the "Post" button competes with the post type buttons ("write something" and "share a link"). It should be greyed out until the user choses a post type. 

currently:

![compete](https://user-images.githubusercontent.com/430126/45887818-9784cf00-bd8a-11e8-8e4c-ecb868aca0e5.png)

as designed: 

![draft freeform start](https://user-images.githubusercontent.com/430126/45887853-a9667200-bd8a-11e8-9155-1cf36a90835c.jpg)

**Comment by aliceriot** [comment]
should we also keep it greyed out until the user enters a title?

**Comment by pdpinch** [comment]
I think that makes sense. You can't submit without a title, right?

**Comment by aliceriot** [comment]
yeah, currently if you try the button will not be greyed out, but clicking it won't submit the post. instead they will be a 'you need a title' validation message that pops up

**Comment by pdpinch** [comment]
This is more complicated that I thought, and it doesn't solve the design issue.

**Comment by pdpinch** [comment]
We're going to solve this with styling. See #1314
