### ISSUE TITLE
Detail page: author, headline, date styling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1255]
In order to avoid awkward wrapping at narrow windows width like this:

<a href="https://mitodl.slack.com/archives/G8FUVTEL9/p1537457989000100"><img src="https://user-images.githubusercontent.com/430126/45989360-5f5ee400-c049-11e8-9627-24c61483f4f0.jpg" width="50%"></a>

We opted to put the poster's name, headline and the (relative) post date _each on their own line_ in the mobile view only. 

mobile: https://zpl.io/2vW869r
desktop: https://zpl.io/bo9J9Lg

### acceptance criteria
- [ ] the desktop version shows a dash `-` between the name and the headline. The dash can be omitted. 
- [ ] we should test this with current maximum names, headlines and dates. I've asked Max to take a look at our production date for these.

**Comment by aliceriot** [comment]
one complication here is that we currently have a link around the profile image, name, and headline, and @mbertrand has an open PR which will also turn the date into a link. This makes it a little tricky to flow them on one line, which could flow nicely on narrower devices.

We can do some things which sort of work with `flex-wrap` and similar things, but it's a little tricky. It might be easier to put on two lines, although I'm not exactly sure what's the best solution yet.

**Comment by pdpinch** [comment]
@aliceriot we've got a design change now. In the mobile view, each item goes on it's own line. 

I updated the description with links to Zeplin. This is now ready to work on.

**Comment by aliceriot** [comment]
ok, there's still a bit of a complication because we currently have a link, which links to the user's profile page, wrapping the profile image, headline, and name. Should I keep that, or remove it? If we want to keep it, it constaints the layout a little bit. I also think that after #1234 is merged it might get a little congested to have two different links so close together.

**Comment by pdpinch** [comment]
Does it help to wrap the profile image and the name each in their own links?

I’m not really sure why the headline is linked. I think we could drop that link in the interest of simplification. .

**Comment by aliceriot** [comment]
@loemerdotcom how's this look?

![mobileversion](https://user-images.githubusercontent.com/6207644/46154946-322a5580-c244-11e8-9202-d8cd241227ff.png)
