### ISSUE TITLE
Site names over a handful of characters in length get hidden behind the user menu on mobile

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1257]
Example at 320px width:

![screen shot 2018-09-25 at 10 30 58](https://user-images.githubusercontent.com/28598/46021310-69ff9480-c0ae-11e8-8a11-dbe7c4ceba0f.png)

**Comment by pdpinch** [comment]
This should be fixed by #1404

**Comment by pdpinch** [comment]
With our current sitenames, this was addressed by #1448
