### ISSUE TITLE
Add "Submit a New Post" button to Discussion homepage

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#126]
- [x] the create post page should have tabs for the two options (text post vs link post)
- [x] there should be a dropdown on the create post page for choosing which subreddit to post to
- [x] if you click 'create post' from a subreddit the subreddit which you're on should be selected by default
- [x] following that change, we should show the 'create post' button in the sidebar everywhere

**Comment by pdpinch** [comment]
I'm not sure that all these are required for MVP. I'm going to move this out of 'Ready' for now.

**Comment by aliceriot** [comment]
this is basically covering just implementing the mockups as they are currently, so IMO it's part of MVP. the one part that we might push off is the dropdown menu, we could add that later, but we do need to do the styling work and the work to get the tabs set up.

**Comment by Ferdi** [comment]
@aliceriot , if it simplifies things a bit, can we just do text posts for now ?   We can add other types of posts later.

**Comment by aliceriot** [comment]
I suppose we could, but we already have support for 'link' posts built out, its just a matter of polishing the UI.
