### ISSUE TITLE
Viewport a little too wide for iPhone SE

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1267]
I'm not sure what the best solution is to this, but it looks like the viewport is too wide when using an iPhone SE. There's a little bit of horizontal scroll and some buttons go off screen. 

For example:

![bs_realios_mobile_iphone se-11 0 2](https://user-images.githubusercontent.com/430126/46101182-4b29fc80-c199-11e8-9688-e9b79b303afa.jpg)

**Comment by pdpinch** [comment]
@aliceriot you had mentioned seeing some issues in iPhone5. Is this the same issue?

**Comment by aliceriot** [comment]
nope! it's another one, haha
