### ISSUE TITLE
Channel Settings: move "Edit" button to channel header; change to gear icon

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1271]
Move channel settings button from left nav into the channel header. This will give us more room for channel titles in the left nav. 

Invision: https://invis.io/9EN908ZQPAX#/311617712_Channel_Settings_Entrance
Zeplin: https://zpl.io/bAq64eO

### acceptance criteria
- [ ] only display the button to channel moderators

**Comment by aliceriot** [comment]
here's what I have so far:

![whwehfawef](https://user-images.githubusercontent.com/6207644/46357444-db9d8c80-c632-11e8-8d26-44c3a8febfc5.png)

**Comment by aliceriot** [comment]
@pdpinch I can go ahead and open an PR with what I have, or if the channel design changes are final I could wrap it into a PR to address all of those at once, whatever you think makes sense

**Comment by pdpinch** [comment]
Sorry to hold this up. I think at this point you should just go ahead with this. You can combine it with #1291
