### ISSUE TITLE
Update about card styling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1275]
While we're waiting for widgets, we still have an about card. The styling needs a refresh to better match. 

See Zeplin: https://zpl.io/VODjzwQ

**Comment by pdpinch** [comment]
This is blocked until we get a design update.

**Comment by rhysyngsun** [comment]
@pdpinch could you clarify this issue for me a bit? is this supposed to be about moving that banner into the sidebar, removing the logo, and updating the language a bit?

**Comment by rhysyngsun** [comment]
Moved back to ready and unassigned since I'm not working on this presently

**Comment by pdpinch** [comment]
closed by #1574
