### ISSUE TITLE
link style for time links should be grey instead of navy

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1292]
When we made the authored-date (e..g "8 min ago") text into a link, we also changed the color. That was unintended and should be reverted. 

https://github.com/mitodl/open-discussions/pull/1234/commits/b26c91cafaf6fcb9375856b08a5554778c559226 part of https://github.com/mitodl/open-discussions/pull/1234

However, these links _should_ have a hover state that underlines the link.

**Comment by pdpinch** [comment]
@aliceriot can you do #1313 at the same time?

**Comment by aliceriot** [comment]
sure - I'll try to go through and make sure we're using the same styles for all links that should look the same (might try to get storybook working to make that a little easier).
