### ISSUE TITLE
Change styling and rendering approach for popups/tooltips

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1299]
There are a few issues with our tooltips (referred to in the codebase as 'popups') that prompt anonymous users to log in. Their positioning depends on where they are rendered, so you can't render a single tooltip at, say, the bottom of the page, and use it in multiple places on the page. You instead need to render a separate tooltip for each link/button that needs to reveal one. This is problematic especially on pages with lots of comments (each 'reply' link reveals a tooltip). Another bad side effect is that since the position cannot be determined dynamically, the tooltips can cause some styling issues when they're revealed (e.g.: https://github.com/mitodl/open-discussions/issues/1296)

Overall goal of this issue: 
1. Allow for a single tooltip to be rendered on a page if multiple components make use of it
1. Display the tooltips in a way that doesn't alter the rest of the UI, located near the element that reveals them when clicked
1. (strongly recommended but I guess not crucial) Create an HOC that lets us add tooltips to a component without having to rewrite the rendering and state updating logic over and over
1. (optional but seriously please do this) Rename all variables/classes/components with 'popup' in their name to instead have 'tooltip' in their name. These components are much more accurately described as tooltips

We may want to look at what material design suggests: https://material.io/design/components/tooltips.html#behavior

**Comment by aliceriot** [comment]
yeah, I think we should do this. I think it won't be too hard to throw together a nice solution using the react context API.

**Comment by gsidebo** [comment]
NOTE: The 'Share' tooltip (`static/js/components/SharePopup.js`) also needs to be updated for the same reasons mentioned above. Since it's a separate component, it might be best to work on that in a separate issue for the sake of keeping the diff small (cc @aliceriot)

**Comment by aliceriot** [comment]
oh yeah, I think it should definitely be updated to use the same system
