### ISSUE TITLE
post form: CTA style changes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1314]
As a user, I find it hard to decide which CTA button to click in the post form.

To make the hierarchy of CTAs clearer, we make the post type buttons `navy` instead of `rouge`. We should expect to use this style of button in other places where there are multiple levels of CTAs.

See Zeplin: https://zpl.io/2yydpZo

**Comment by pdpinch** [comment]
This replaces #1237

**Comment by aliceriot** [comment]
side note: what is a CTA?

**Comment by Ferdi** [comment]
@aliceriot  buzzword    :-)
Call To Action, I  think

**Comment by aliceriot** [comment]
second question: the linked mockup shows a greyed-out post button still, do we want to have that? if so, what circumstances should that be greyed-out in? it's complicated because we do allow the user to make an 'empty' post which does not have any text content.

**Comment by pdpinch** [comment]
Disabling the submit button is out of scope — for exactly the reasons you mention.

**Comment by aliceriot** [comment]
cool, thanks for confirming - just one last question, we currently have this little "text" icon in the 'Write something' button:

![newbuttons](https://user-images.githubusercontent.com/6207644/46692215-b7aeed80-cbd4-11e8-944e-914eb535cd41.png)

in the mockups it's a different icon, should I go ahead and switch it out?
