### ISSUE TITLE
Search: index user profiles

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1317]

**Comment by mbertrand** [comment]
- [ ] Add profile fields to the ElasticSearch document structure: 
  ```
    'author_avatar_small': {'type’: 'keyword'},
    'author_avatar_medium': {'type': 'keyword'}
    'author_headline': {'type': 'text'},
    'author_bio': {'type': 'text'},
    'author_channel_membership': {‘type’: ‘keyword’}
  ```
- [ ] Trigger an index update on a profile and all posts/comments authored by that profile when the profile is changed.

**Comment by mbertrand** [comment]
Part of epic #1316

**Comment by mbertrand** [comment]
Based on what I've read so far, I agree with @noisecapella that it should be fine to have profiles in the same index as posts and comments.

**Comment by mbertrand** [comment]
Suggestion: assign `author_avatar` to the value of the output of the`ui.utils.image_uri` function, assuming a small image size.

**Comment by mbertrand** [comment]
Blocked by #1337
