### ISSUE TITLE
Comment card: overflow menu drop-down is misaligned

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1321]
I'm seeing this in Firefox, in the Reported Content tab of the channel settings (/manage/c/edit/nathantest5/moderation/ on RC)

<img width="950" alt="screen shot 2018-10-05 at 12 14 11 pm" src="https://user-images.githubusercontent.com/430126/46546975-8ebaef80-c898-11e8-80fa-86d543a7cf42.png">

**Comment by mbertrand** [comment]
@pdpinch does this placement look correct?

<img width="295" alt="screen shot 2018-10-18 at 4 10 42 pm" src="https://user-images.githubusercontent.com/187676/47181213-6eefe680-d2f0-11e8-9099-49681e16b0ba.png">
