### ISSUE TITLE
Investigate missing posts in Elasticsearch index

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1324]
To calculate this list:

    from search.connection import get_conn
    conn = get_conn()
    search = conn.search(index=get_default_alias_name(), size=10000)
    hits = search['hits']['hits']
    search_posts = [post for post in hits if post['_source']['object_type'] == 'post']
    post_ids = set(Post.objects.values_list('post_id', flat=True))
    diff = post_ids.difference(set([hit['_source']['post_id'] for hit in search_posts]))
    print(diff)

I'm seeing five posts in production which exist in `Post` and not in the search index. At least one of the posts exists and it's been causing recurring issues due to a comment which references the post: https://sentry.io/mit-office-of-digital-learning/discussions/issues/579649855/?query=search

I'm not sure why the post isn't indexed. If there was a problem indexing there should be a Sentry error but I'm not finding it (yet)

**Comment by mbertrand** [comment]
#1368, #1369

**Comment by mbertrand** [comment]
Within a particular channel, there are posts in ES but not in Django and vice versa:
```python
from search.api import *
query = {
  "from": 0,
  "size": 10000,
  "query": {
    "term": {
      "channel_name": "mit_odl_engineering"
    }
  }
}
index = get_default_alias_name('post')
search = Search(index=index, using=get_conn())
search.update_from_dict(query)
results = search.execute().to_dict()

post_ids =set(Post.objects.filter(channel__name='mit_odl_engineering').values_list('post_id', flat=True))
es_ids = set([hit['_source']['post_id'] for hit in results['hits']['hits']])

post_ids.difference(es_ids)
>{'if', 'm6'}

es_ids.difference(post_ids)
>{'bw', 'c0', 'c1', 'c3', 'c7', 'df', 'dh', 'di', 'dq', 'dr', 'f0'}
```

**Comment by mbertrand** [comment]
The two posts that are in Django but not ES have `banned_by=<username>` in reddit, so those are probably OK.

**Comment by pdpinch** [comment]
@mbertrand @noisecapella what more do we need to do here?

**Comment by mbertrand** [comment]
I think only 25 posts are being indexed per channel due to the `OPEN_DISCUSSIONS_CHANNEL_POST_LIMIT` being set to 25.  But this should become irrelevant once PR #1415 is merged.  Once that is on production I'd like to see what if anything is still missing after recreating the index.

**Comment by mbertrand** [comment]
The number of posts in Elasticsearch now equals the number of posts in Django.
