### ISSUE TITLE
Email: front page template round 2

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1325]
Current version (iPhone 6s):

![img_d106984fb3ba-1](https://user-images.githubusercontent.com/430126/46623363-67b02800-cafb-11e8-9389-6ed78c65d0fb.jpeg)

New version, on Zeplin: https://zpl.io/2pBW1dE (updated 10/10)

### acceptance criteria:
- [x] stop centering the text at the narrowest window width
- [x] change title to "Top Stories for You"
- [x] Tighten up the vertical spacing between elements, to make it clearer where the card boundaries are (in other words, follow the Zeplin spacing)
- [x] restore the channel name
- ~~restore a count of comments~~
- [x] change subject line to "[`sitename`] Top stories for You"

### questions:
- Can we display thumbnails from link posts, or is there more infrastructure we need for that?
  - A: maybe 
- How much weight does the "comment" styling add?
  - A: doesn't matter, we're cutting the comment count

**Comment by pdpinch** [comment]
I made a few changes to the description: we're dropping the comment count. And I simplified the email subject.

**Comment by rhysyngsun** [comment]
This should be closed.
