### ISSUE TITLE
In ES mapping, change certain 'keyword' types to 'text'

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1333]
The 'text' type should be used for data where we want stemming and other language aware processing to be done to allow more matches

**Comment by mbertrand** [comment]
@noisecapella, these are the fields currently using the `text` type in master or the profile index PR:

**Posts & comments**:  text: `channel_title`, `post_title`, `text`
**Profiles**: `author_headline`, `author_bio`

Maybe change `author_name` from `keyword` to `text`?

**Comment by pdpinch** [comment]
I don't think this is blocking channel search any more. I'm going to move it to the profile epic, if it's even necessary.
