### ISSUE TITLE
fixup sign-up page layout

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1347]
The signup page is looking pretty ragged (desktop and mobile)

<img width="40%" align="left" src="https://user-images.githubusercontent.com/430126/46868640-02a84b00-cdf7-11e8-8ffa-bffedd7e4b74.png">
<img width="40%" src="https://user-images.githubusercontent.com/430126/46868639-020fb480-cdf7-11e8-891b-8e941374c324.png">

### acceptance criteria
- [x] if possible, size the captcha box to be the same width as the input field and the touchstone button
- [x] change the "Next" button text to "Sign Up" 
- [x] change the `<hr>` width to be the same as the  input field and the touchstone button

**Comment by rhysyngsun** [comment]
The captcha resizing is really tricky because the google script controls that component, I can look into resizing it via JS.

**Comment by pdpinch** [comment]
Would it be easier to set everything else to the same width as the captcha box?
