### ISSUE TITLE
fixup basic embedly styling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1356]
This isn't looking too good. The horizontal space between the image and the text is too small. 

![embeldyspace](https://user-images.githubusercontent.com/430126/46893621-8ede6080-ce3f-11e8-8cf3-e55c485303ad.png)

I'm going to open another issue to narrow the column width of the post detail page (#1357). It may make sense to combine these two issues.

**Comment by aliceriot** [comment]
how's this look as an update? I just added some more padding between the image and text, and made the text the same size we currently use for displaying text posts:

![floop](https://user-images.githubusercontent.com/6207644/48643388-95677700-e9ad-11e8-97af-004fa90f7109.png)

**Comment by pdpinch** [comment]
Much better. Please open a PR.
