### ISSUE TITLE
Update the index when the channel settings are updated

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1358]
We will need to update all posts and comments in Elasticsearch for the channel when the channel settings are modified in the UI. We just need to start the `search.tasks.index_channel` task. We can create a decorator in `search.task_helpers` and use it in `channels.api` similar to how we handle updates for posts and comments.

**Comment by pdpinch** [comment]
Which fields in channel settings will need to be updated in the index?

**Comment by noisecapella** [comment]
@pdpinch At the moment just `channel_title`
