### ISSUE TITLE
fixup intro card layout

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1359]
It appears that at narrow window widths the content of the intro card can overflow it's box, affecting the entire page layout. This was seen in desktop Chrome at a narrow window width, but not in cursory mobile testing. 

![openmobile](https://user-images.githubusercontent.com/430126/46893957-c00b6080-ce40-11e8-8838-8676eabc7d44.png)

**Comment by aliceriot** [comment]
I can repro this issue in the chrome simulator for an iPhone 5, which is a screen width (320px) that we should be supporting, so we definitely want to fix this.

**Comment by aliceriot** [comment]
how's this look for a quick fix?

![quickfix](https://user-images.githubusercontent.com/6207644/46959725-b5ccaa80-d06a-11e8-832a-e0cb5b77ec4e.png)

(just reducing font sizes and tweaking a few CSS things)
