### ISSUE TITLE
Sign up: no error message when reusing email verification URL

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1363]
### Steps to reproduce
- [ ] Go to /signup and enter a new email address
- [ ] In one browser, go the verification URL sent by email
- [ ] In another browser, use the URL again

### Expected behavior
- error message indicated the URL is expired or already used

### Actual behavior
- A loading loop displays and the register API returns a 500 

```
AttributeError at /api/v0/register/confirm/
Got AttributeError when attempting to get a value for field `partial_token` on serializer `RegisterConfirmSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `SocialAuthState` instance.
Original exception text was: 'NoneType' object has no attribute 'token'.
```

Sentry Error: https://sentry.io/mit-office-of-digital-learning/discussions/issues/649994911/

**Comment by rhysyngsun** [comment]
`RegisterConfirmSerializer` needs to return a structured error if the token couldn't be found.
