### ISSUE TITLE
Post form: link field doesn't throw error on type return

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1366]
If you type an unusable URL (e.g. it doens't start with http) into the link field and click post, validation fails and an error is displayed. 

However, if you type an unusable URL followed by `return` or `enter` the form submits (or maybe cancels?) without validation. 

While we're working on this, we might want to review the formatting of the error message. It doesn't look like the validation errors elsewhere, e.g. the signup forms:

<img align="left" width="60%" alt="screen shot 2018-10-15 at 8 44 33 am" src="https://user-images.githubusercontent.com/430126/46951711-c6732580-d056-11e8-8a32-afb1262c30af.png">
<img width="30%" alt="screen shot 2018-10-15 at 8 45 55 am" src="https://user-images.githubusercontent.com/430126/46951710-c6732580-d056-11e8-85d0-eae036d41d8a.png">

**Comment by aliceriot** [comment]
that validation message is coming from the browser (we have `type="url"` set on the input field) which is why it is styled differently. I'm not sure about options for styling browser-native validation messages, our option might be to re-implement the same validation in our own system.

**Comment by aliceriot** [comment]
re-implementing it in our own system would, I think, address the 'enter' issue as well.
