### ISSUE TITLE
Missing posts in the elasticsearch index

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1368]
We need to change our reindexing code to reference our database models to get the post and channel information, rather than asking reddit for it since reddit cuts off posts at about 1000 posts per channel

**Comment by pdpinch** [comment]
I thought we had done this as part of #730 / #742 ?

**Comment by noisecapella** [comment]
No, we only created the models and keep them up to date. We don't use them for reindexing yet

**Comment by noisecapella** [comment]
To clarify, the PR adds code to update the database models when `recreate_index` runs, based on information from reddit. I think that was incorrect, we instead need to do it the other way around.
