### ISSUE TITLE
Channels should be owned by the indexing user

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1369]
Right now channels are owned by the user who created the channel. If they were created through MicroMasters this is the indexing user, a special user who manages channels for indexing and other purposes. However if the channel was created through the discussions UI the channel is owned by the user who created it. This prevents us from properly managing the channel. We actually don't even record this user anywhere so if these channels are private we have to iterate through all users to see who has access to it.

Instead we should create all channels with the indexing user, then assign the creating user as a moderator right after. We should also make a script which will fix existing channels on production:
 - For each channel figure out who the current owner is (for private channels where we don't know the owner, this may require looping through all users and testing out access)
 - Record the list of moderators and their creation date (this determines who has seniority).
 - Add the indexing user as a moderator.
 - Remove all other users as moderators, making sure to remove the owner last.
 - As the indexing user, add all other moderators back in the order of seniority

**Comment by rhysyngsun** [comment]
Part of this should be a script to repair over existing channels that don't have this to be the situation.

**Comment by noisecapella** [comment]
Yes, that's the next step

**Comment by pdpinch** [comment]
@noisecapella can you explain the problem in the description? I'm not convinced this is the best solution.

**Comment by noisecapella** [comment]
@pdpinch I updated the description

**Comment by noisecapella** [comment]
> Is the "indexing user" and the "creating user" reddit concepts, or discussions concepts?

The "indexing user" is our own concept. The "creating user" is a reddit concept, they are the person who created the subreddit and they have the most moderator seniority for that subreddit. I don't think they have any other privileges besides what they get from being a moderator (@rhysyngsun correct me if I'm wrong)

> If they are in discussions, can you mention where they are set/stored.

You're right about `INDEXING_API_USERNAME`. We don't store this information in our models though we should.

> In other discussions about "looping through channels" it hasn't been clear to me whether we are iterating over the channels in open-discussions, or iterating through the subreddits in reddit. I'm not convinced the latter is necessary.

We won't have any other way of knowing who the moderator is besides asking reddit, since we didn't store that information in `Channel`.

> Why is seniority important?

Reddit moderators can only remove moderators with less seniority. To make sure nobody can remove the indexing user they need to be added earliest to have seniority, and that means we need to remove and add back all the other moderators

**Comment by rhysyngsun** [comment]
@pdpinch @noisecapella correct. I think critically, maintaining the "indexing user" ("administrative user" is probably more apt) as the most senior moderator (hence, effectively, the owner of the channel) is important to give us an allowance to programmatically manage other users (as they'll have lower seniority) without having to masquerade as a real user (and jump through hoops to determine _who_ we'd need to masquerade as). Basically, it allows us to have consistency in how channels are setup and managed.
