### ISSUE TITLE
Can't pin link-type posts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1385]
For some reason, I can pin text posts, but not link posts. I should be able to pin all posts. 

![screen shot 2018-10-18 at 9 34 36 am](https://user-images.githubusercontent.com/430126/47158166-0f2a1900-d2b9-11e8-8ff5-0297c399c28e.png)
![screen shot 2018-10-18 at 9 34 25 am](https://user-images.githubusercontent.com/430126/47158167-0f2a1900-d2b9-11e8-8e03-fe17280e1046.png)

**Comment by aliceriot** [comment]
I believe this is a limitation of reddit, I think we discovered that when we initially implementing the UI and API layer for pinning but I don't remember the exact things.

**Comment by aliceriot** [comment]
@noisecapella might remember the specifics

**Comment by rhysyngsun** [comment]
This worked on the backend, so I just removed the check for the post type on the frontend.
