### ISSUE TITLE
Add channel banner to post detail page & channel settings page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1388]
- [ ] Desktop post detail page, logged in: https://zpl.io/VQEJqKk  
- [ ] Desktop post detail page, not logged in: https://zpl.io/2ZzODOd
- [ ] Mobile post detail page: https://zpl.io/2vW869r
- [ ] Desktop channel settings page: https://zpl.io/V00ry1l

**Comment by rhysyngsun** [comment]
@pdpinch is that "Moderator" button(?) on the settings page header something that needs to be implemented for this? If yes, what is it?

**Comment by pdpinch** [comment]
No. I'm actually not sure what is & I'm pretty sure it shouldn't be there.

**Comment by rhysyngsun** [comment]
@pdpinch one more question, should the channel nav (the white bar that currently has "Home" on it) be showing up on pages other than the channel listing page?

**Comment by pdpinch** [comment]
Yeah, that's an oversight in the design. It should be on the post details page and the channel settings page. Let me know if you can do that as part of this work, or if it should split out.
