### ISSUE TITLE
Profile: add location 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1399]
As a user, I'd like to be able to share my location (as defined by me) so that others users "nearby" can find me. 

Design TBD, but we are thinking of something like Twitter. If you start typing a city, state or country, it helps you complete it. If you want to type your own string, that's also accepted. 

### acceptance criteria
- [ ] choose a placename API for helping with autocompletion and also converting to geo coordinates
  - in the past we had trouble with Google because it was blocked in some regions
  - other possibilities include https://nominatim.openstreetmap.org/ and something Ferdi recommended
  - need to review the terms for any API we choose, to consider cost and what data we can persist from the API
- [ ] extend profile model to include location -- as a string and also as geocoordinates 

### questions
- Should we add this data to elasticsearch?

**Comment by mbertrand** [comment]
- Use algolia for the API (geonames second choice if issues arise)
- Use algolia's [`places.js`](https://community.algolia.com/places/documentation.html)  library
- Restrict to city search
- When user selects one of the possible results, save that entire result as JSON to the database
- Display '<city>, <administrative>, <country>` values from the JSON on the user profile.  Example: `Boston, Massachusetts, United States of America`
