### ISSUE TITLE
Allow moderators to add new members to private channels

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1400]
As a moderator, I'd like to be able to add new users by email to my private channel. But currently, I can't add anyone who doesn't have an account. 

We can do this by allowing unrecognized emails in the channel members form. When the email address doesn't match an existing user, we can generate an email with a custom message, but that functions similarly to 

### acceptance criteria
- [x] draft text for invite email: https://zpl.io/VQ9RBe9
- [ ] update the `/signup/details` template text so that it will work with this flow
- [ ] determine how best to temporarily store the account information

### Questions
- Can we just create an account, without it being active?
  **A:** No. This won't work the social auth workflow. We would have an account with no social auths, so it would be impossible to log in to the account.
- Can we allow the new user to sign up with any email address or do they have to sign up with the invited email address?
  **A:** They have to sign up with the invited email address
- What do we do if multiple invites have been sent to the same user (this might affect the answer to the Q directly above this)?
  **A:** I think the previous answer makes this moot?
- Do we want to normalize the channel invitation experience across users that do and don't exist?
  - i.e. are we going to allow any channel moderator to add any user, hence permitting them to get content on the frontpage of arbitrary users? (this is probably not a huge issue right now, but is more critical if we open up who can create channels)
  **A:** No plans now. We'll keep an eye on this. 
- Do we need to add the ability to unsubscribe from channels too?
  **A:** We will be adding this soon.

**Comment by pdpinch** [comment]
This is blocked until we get the email template text finalized, and we answer the 2nd question.

**Comment by rhysyngsun** [comment]
@pdpinch could we clarify exactly what is expected if multiple invites are sent to the same user? Do they get all those subscriptions when they register?

**Comment by rhysyngsun** [comment]
@pdpinch a few remaining Qs:

- what is the email template for this supposed to look like?
- if the user has multiple invites, do we want to resolve all of those on signup or just the one for the invite link they clicked?

**Comment by pdpinch** [comment]
This is no longer blocked by questions or by the need for a template. It is still blocked by #1512

**Comment by rhysyngsun** [comment]
Actually a few more Q's that occurred to me:

- What confirmation message does the moderator see?
- Where do pending invites show up (if at all)? Right now our list is coming from reddit, whereas pending invites are in the postgres db, so mixing together in one list could be tricky.
