### ISSUE TITLE
When recreating the search index, get the list of channels from django, not reddit

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#1401]
Currently, the reddit api is used to retrieve a list of existing channels.  This will only return the channels created by the indexing user.  Get all the channels via `Channel.objects.all()` instead.

However, indexing private channels will not work until #1369 is implemented.

**Comment by mbertrand** [comment]
Dupe

**Comment by pdpinch** [comment]
What is this a duplicate of?

**Comment by mbertrand** [comment]
#1368
