### ISSUE TITLE
comment button appears above banner message in narrow widths

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1405]
At the widest desktop width, the layering looks OK. But at tablet and mobile widths, the comment button appears above the banner message. 

![screen shot 2018-10-22 at 8 46 10 am](https://user-images.githubusercontent.com/430126/47293143-478e6780-d5d7-11e8-840d-2756cdb2f5a0.png)

**Comment by aliceriot** [comment]
I think it's actually at all widths:

![wiiiiiiiide](https://user-images.githubusercontent.com/6207644/48429127-81680f00-e73a-11e8-9e22-9d51b1a6ceda.png)
