### ISSUE TITLE
Post Summary card layout changes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1426]
We've gotten some feedback that our current design isn't dense and rich enough. These design changes are intended to use the available space more efficiently. 

See https://zpl.io/aNoOp4D

### acceptance criteria
- [x] Preview the first two lines of the post content, ending with an elipsis if it's too long
  - [x] #1636 for articles, this requires adding the article text to the posts API
- [ ] Move the comment button and overflow menu to the left
- [ ] Increase the height of the thumbnail image to fill the card
- [ ] Note: not all cards will be the same height

### out of scope
- The zeplin design has an older version of the "pinned post" label

**Comment by gsidebo** [comment]
@pdpinch just to confirm: we're getting rid of the user headline in these summary cards?

**Comment by pdpinch** [comment]
That's correct. 

We have been considering moving the headline to a "tool tip" on hover, but haven't pursued it yet because of concerns about mobile.

**Comment by gsidebo** [comment]
Another question: when the post/article content contains line breaks, should we treat them like spaces for the purposes of the preview text? I'm guessing the answer is "yes" but definitely worth checking in about.

**Comment by pdpinch** [comment]
I spoke to @gsidebo about this. We're going to break this into 3 separate issues, only 2 of which we'll pursue at this time. Removing the headline is on hold. 

I'll update the issues as soon as I can.

**Comment by gsidebo** [comment]
@pdpinch The design also indicates a UI change in the way that we show pinned posts. Here's a screenshot of a pinned post I have locally: 
![ss 2019-01-16 at 15 18 25](https://user-images.githubusercontent.com/14932219/51276206-13da9800-19a2-11e9-8c44-2f0f554a918b.png)

From the design:
![ss 2019-01-16 at 15 19 47](https://user-images.githubusercontent.com/14932219/51276251-34a2ed80-19a2-11e9-9abe-468fbf8a7cb6.png)

Should I be making this change as well?

**Comment by pdpinch** [comment]
@gsidebo read the note in the issue description:

> The design also indicates a UI change in the way that we show pinned posts.

(if there's a way that I could have made that clearer, let me know -- other than updating the design)

**Comment by pdpinch** [comment]
I'm closing this in favor of #1733
