### ISSUE TITLE
TypeError in IE 11: Object doesn't support this action

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1431]
https://sentry.io/mit-office-of-digital-learning/discussions/issues/682762100/

```
TypeError: Object doesn't support this action
  at s (./static/js/components/CanonicalLink.js:28:3)
...
(5 additional frame(s) were not displayed)
```

**Comment by pdpinch** [comment]
This was happening pretty frequently, but now it's been two days since the last occurrence.

**Comment by rhysyngsun** [comment]
This issue doesn't exist anymore in sentry for whatever reason, plus it's over a year old, so closing it
