### ISSUE TITLE
Article: Custom build of ckeditor

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1454]
Open a new repo (https://github.com/mitodl/ckeditor-custom-build) for configuring the requirements and build an NPM package that can be imported into open-discussions.

**Comment by aliceriot** [comment]
The first go at this is done, with this pr here: https://github.com/mitodl/ckeditor-custom-build/pull/1

it's up on npm here: https://www.npmjs.com/package/@mitodl/ckeditor-custom-build

so I think we can close this issue
