### ISSUE TITLE
Widgets: Feature flag 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1458]
As the widgets are under development, we need a feature flag that controls the display of widgets

Estimate: this is already done in a forthcoming PR.

**Comment by jklingen92** [comment]
I've included a configuration setting that allows you to turn off all
widget lists. Is that what you're looking for or a more granular control?

**Comment by pdpinch** [comment]
@rhysyngsun since #1452 merged, can we close this?

**Comment by rhysyngsun** [comment]
resolved in #1534
