### ISSUE TITLE
Mobile drawer header does not include site name

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1467]
This was brought up in the PR comments for #1448 

![ss 2018-11-07 at 12 00 55](https://user-images.githubusercontent.com/14932219/48217293-00cd9b00-e355-11e8-9618-44eac8481499.png)
![ss 2018-11-08 at 11 20 24](https://user-images.githubusercontent.com/14932219/48217275-f90df680-e354-11e8-8595-36de683e3776.png)

Note how the drawer lacks the 'MicroMasters' site name

**Comment by pdpinch** [comment]
The correct layout can be seen at https://zpl.io/bz1ZjBG
