### ISSUE TITLE
create post button is gone from mobile

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#147]
I think this maybe relates to the changes made in https://github.com/mitodl/open-discussions/pull/143

@noisecapella was that an intended effect?

**Comment by noisecapella** [comment]
No, not sure why that's happening

**Comment by aliceriot** [comment]
it's because react-router doesn't parse the URL params out in the same way at every point in the route hierarchy. that's why I had to resort to using a regex, because the `<Navigation />` component which lives in the drawer doesn't get the `channelName` parameter parsed out in the props that it receives. There's some discussion on the PR where I implemented that here: https://github.com/mitodl/open-discussions/pull/118#discussion_r135293671

I think we should revert your change and fix the regex to restore the functionality.

**Comment by aliceriot** [comment]
sorry, wrong link, discussion is here: https://github.com/mitodl/open-discussions/pull/118#discussion_r135284591
