### ISSUE TITLE
Investigate requiring a minimum length for text when searching content

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1507]
Currently the search will display all results, which may not be what we want

**Comment by pdpinch** [comment]
To clarify, the issue is that when the user visits to /search/ with no search term, we will return search results that include the entire index.

**Comment by mbertrand** [comment]
What do you think of having a `ELASTICSEARCH_MIN_QUERY_SIZE` env. variable, default value of 2. If the query term has fewer characters than that, a canned '0 results' response is sent back from the API instead of actually querying ES:
```python
    if len(query) < settings.ELASTICSEARCH_MIN_QUERY_SIZE:
        return {
            "hits": {
                "total": 0,
                "hits": []
            }
        }
```

**Comment by pdpinch** [comment]
I like that it allows us to change the minimum query length (or is it size?), but I'm not sure about the canned response. We won't be able to tell the difference between a result where the query is too short and a result when there are bona fide zero results (can that even happen). 

Remind me to bring it up in planning.

**Comment by mbertrand** [comment]
<img width="669" alt="screen shot 2019-01-08 at 12 06 35 pm" src="https://user-images.githubusercontent.com/187676/50846755-e9ebfa80-133d-11e9-8311-a9c961ec2e2f.png">

**Comment by mbertrand** [comment]
@noisecapella @rhysyngsun Peter suggested getting your opinions on the approach to use for this.
