### ISSUE TITLE
Search: hide reply button on comment cards

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1541]
The reply button doesn't make sense in search results. It should be removed from the comment card in search results. 

~~As a user, I'd like to be able to click through from a comment card on search results to the post detail page with the appropriate reply form open.~~

**Comment by mbertrand** [comment]
@pdpinch @ferdi just want to confirm that you now prefer to remove the reply button from search results rather than make it work, assuming it's not more difficult?

**Comment by pdpinch** [comment]
That's correct. I changed the title and edited the description of this issue.
