### ISSUE TITLE
migrate mail to new name: mail.open.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1546]
For more consistent branding, and to better manage the reputation of the mail server, we should migrate to a private IP and name for Open. 

### acceptance criteria
- [x] purchase private IP from Mailgun
- [x] set up MX records with MIT IS&T
- [x] check quality of existing list
- [x] change RC config 
- [ ] warm IP
- [x] test RC
- [x] change production config
- [x] test production

**Comment by pdpinch** [comment]
Test list sent to mailgun. They say it will take 3-4 days to review.

**Comment by pdpinch** [comment]
@shaidar can you confirm that the new IP is warmed?

**Comment by shaidar** [comment]
@pdpinch The dedicated IP is not warmed as the agreement was that will start warming it using the new domain and since we haven't switched to that yet, it hasn't been used.

**Comment by shaidar** [comment]
Think this is safe to close. Dedicated IP warming is configured however will take some time.
