### ISSUE TITLE
Loader during channel search is too wide

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1552]
It looks fine on the site search but in the channel search it takes up the full width

See https://share.vidyard.com/watch/T9bJBZ1DhUD1rhWJ9WX3b4?

**Comment by aliceriot** [comment]
I've noticed this too, I tried to capture this screenshot:

![wideloadingasd](https://user-images.githubusercontent.com/6207644/49594864-c1d73900-f944-11e8-8b23-aeb47f928db2.png)

**Comment by pdpinch** [comment]
I added a video to the description yesterday, if that's helpful.
