### ISSUE TITLE
Attempting to log in prior to verifying email

### ISSUE THREAD

**Issue by shaidar** [mitodl/open-discussions#1568]
When a user signs up with a non-MIT account and attempts to login with that account prior to verifying their account through the email sent to them, the following Sentry error is generated:

https://sentry.io/mit-office-of-digital-learning/discussions/issues/604126352/?query=is%3Aunresolved

```Received unexpected result: <HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/">```

Also, the user does not get any notification about this issue as they continue clicking on the `Next` button.

**Comment by pdpinch** [comment]
Sentry issue: [DISCUSSIONS-8S](https://sentry.io/mit-office-of-digital-learning/discussions/issues/604126352/?referrer=github_plugin)
