### ISSUE TITLE
BUG - Clicking on a Post on channel page links to post page scrolled down

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#157]
How to recreate this:

1. I think you will need to have a channel page (or the home page) with enough posts showing that you have to scroll down the page to click on a post.
2. Scroll down and click on a post... this links to the post detail page, and everything is normal.
3. If you click back to the channel page, then click on the post again, it links to the post detail page, but the page is scrolled down to the same place as where you were scrolled to on the channel page.

See in Mac/Chrome.

**Comment by aliceriot** [comment]
I can reproduce this on my machine (chrome on Linux). However, there is one strange thing I noticed: this only repros if (in step 3) I navigate back to the post by clicking on the 'comments' link. If I use the browser's 'forward' button instead it takes me to the post, but scrolled to the top.

I can think of at least one silly, hacky way to solve this, but I'll do a little research first to see what's going on.

**Comment by aliceriot** [comment]
here's a relevant issue: https://github.com/ReactTraining/react-router/issues/2019

**Comment by aliceriot** [comment]
relevant react-router docs: https://reacttraining.com/react-router/web/guides/scroll-restoration
