### ISSUE TITLE
ckeditor image captions are displayed in read-only mode, even if empty

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#1572]
seems like a bug in the ckeditor image caption plugin. there's an issue here on their repo:

https://github.com/ckeditor/ckeditor5-image/issues/242

It looks weird now, because when we're showing the editor in read-only mode, if the user clicks on the photo an empty caption thingy which says "add a caption" will show up, but they can't edit it.

I think we should either remove the plugin until the bug is fixed. or try to open an upstream pr to fix the above issue.

**Comment by aliceriot** [comment]
@pdpinch curious what you think

**Comment by aliceriot** [comment]
going to go ahead and remove the image caption plugin, I'll make a PR on the custom build repo to make that change and then also a PR here to upgrade to it

**Comment by aliceriot** [comment]
will do this as part of addressing #1583

**Comment by pdpinch** [comment]
What's left to do here? Do we need to bring in a new version of the ckeditor-custom-build ?
