### ISSUE TITLE
Article: UI updates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1583]
This is a mini-epic of UI adjustments to the Article editor. If any of these are more challenging they can be broken out into their own issues:

- [x] close the navigation drawer when writing (ideally for just the article, but could be for all post types)
- [x] Give the title an H1 style (can be the same for all post types) 
- [x] add a header drop down to the top WYSIWYG button bar (see [LinkedIn screenshot](https://user-images.githubusercontent.com/430126/49951538-2c015800-fec8-11e8-8124-f9a760efb319.png)) 
- [x] Remove Table, undo and redo buttons from WYSIWYG button bar
- [x] the WYSIWYG button bar should be sticky, at the top of the viewport, so users don't have to scroll up just to change some text to bold
- [x] Change the icon for the block menu from a ¶ to a + 
- [x] Cut the block menu to paragraph, image and video (we'll add embed later)
- [x] When opening the form, set the focus to the first line
- [x] Add placeholder text to the first line (suggestion "Write your article here")
- [x] remove the borders on the text area, so it's not separate from the rest of the page
- [x] make the icons smaller (appx same size as in https://zpl.io/aXME3lx) 
- [ ] After adding an image, can we also add a paragraph and set focus to it, to make it clearer how the user can continue writing after uploading and image
- [x] Can we have a "are you sure" dialog when switching between post types? 

### related issues
- #1492 Cover Image

**Comment by aliceriot** [comment]
@pdpinch I've run into one difficulty, which is that the block menu icon is unfortunately not configurable

**Comment by pdpinch** [comment]
So we're stuck with that paragraph mark? It looks like it's an inlined svg... 

In any case, just open a new issue for it. We can decide later how big a deal it is.

**Comment by pdpinch** [comment]
@aliceriot can you update the checkboxes on this, now that #1601 is merged? If we're down to just one or two checkboxes, we can open issues for them and close this one.

**Comment by aliceriot** [comment]
opened https://github.com/mitodl/open-discussions/issues/1632

**Comment by aliceriot** [comment]
does this look roughly like what we were thinking for the new title input?

![post_title_added](https://user-images.githubusercontent.com/6207644/50662142-6adc7800-0f73-11e9-96ca-87daff7e569f.png)

**Comment by aliceriot** [comment]
![post_title](https://user-images.githubusercontent.com/6207644/50662151-70d25900-0f73-11e9-9d03-369195b7b68c.png)

(empty input)

**Comment by pdpinch** [comment]
For the headline, we'd still like a white background to signal it being a form. 

Take a look at https://zpl.io/29PA8ne

**Comment by aliceriot** [comment]
ah ok, I had thought that 'h1 style' meant going with something like the linkedin 'headline' input, which looks like this:

![fofofofo](https://user-images.githubusercontent.com/6207644/50694489-015a7900-1008-11e9-8f92-29c6d9360234.png)

**Comment by pdpinch** [comment]
Sorry I wasn’t clear. 

What I meant is that the style in the editor should match the headline style in the rendered post detail page — specifically our headline style.

**Comment by aliceriot** [comment]
ok, so you mean the style for h1 tags that the user adds to the article, when they are rendered in the editor, should matched what we currently do for rendering the post's title on the post detail page?

**Comment by aliceriot** [comment]
ok, here's a little go at what we just discussed:

![headlineblank](https://user-images.githubusercontent.com/6207644/50696058-6f08a400-100c-11e9-963d-4396f8bc7f13.png)

![headlineblanknot](https://user-images.githubusercontent.com/6207644/50696061-716afe00-100c-11e9-9387-eab03b80a1ee.png)

that's using the same font styles that we use for rendering the post title currently.

one additional question, if we're going to call the post title the 'headline' now, should we make a corresponding adjustment to the validation copy? This is the current thing that pops up if you leave off the title:

![headlinemsg](https://user-images.githubusercontent.com/6207644/50696124-95c6da80-100c-11e9-81e6-d0e15be418c3.png)

the obvious option to me is "Headline is required"

**Comment by pdpinch** [comment]
Perfect. That’s what I had in mind. 

I agree that the validation copy should be updated to match.

**Comment by pdpinch** [comment]
closed via fca070d
