### ISSUE TITLE
Add widget type description to available_widgets return value

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1592]
See https://zpl.io/2jPoowr

Currently we only have the `widget_type` and `form_spec` fields. We should add something like `description` for the text under the title, and possibly a separate `title` if we don't want to display `widget_type` directly

**Comment by pdpinch** [comment]
I removed the outdated screenshot from the screenshot and replaced it with a link to a more recent version on Zeplin.

**Comment by noisecapella** [comment]
Looks like the order of widgets in the new widget selection comes from this list: https://github.com/mitodl/open-discussions/blob/master/widgets/serializers/utils.py#L17

I'll put Markdown first for convenience

**Comment by noisecapella** [comment]
While we're at it we should also pass the description of the widget fields in the spec to the REST API
