### ISSUE TITLE
Article: Cover Image editing frontend

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1594]

**Comment by aliceriot** [comment]
I have a question for this, do we want to have the cropper constrain the resolution like we do for the channel banner?

**Comment by aliceriot** [comment]
and if so, to what dimensions?

**Comment by pdpinch** [comment]
No, we'd like to give users flexibility here. We've already got a way to resize thumbnails as needed.

**Comment by aliceriot** [comment]
ok cool

**Comment by pdpinch** [comment]
That looks good to me. There is an design at https://zpl.io/2vNqzPJ but you don't need to make it look exactly like that. I'm mostly interested in the functionality at this point.
