### ISSUE TITLE
As a logged in user I would like to be able to create a channel

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#16]
The most minimal form to create a channel.  

- [x] Implement backend API (PR #39)
- [ ] Implement frontend UI
- [ ] Integrate frontend UI with API

**Comment by pdpinch** [comment]
@noisecapella did I get it right that you are already working on this?

**Comment by noisecapella** [comment]
yes

**Comment by rhysyngsun** [comment]
I'll take the rest of this
