### ISSUE TITLE
/c/:channelName/ and child routes should be nested <Route/> tags

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1623]
I think we could simplifying some of our code (particularly around data loading and UI), by nesting some of these routes.

https://github.com/reactjs/react-router-tutorial/tree/master/lessons/04-nested-routes

**Comment by aliceriot** [comment]
since I'm going to be adding another page here for #1778 I'm going to do this as well

**Comment by aliceriot** [comment]
the really nice thing would be if all the channel administration components were routed under `/c/:channelName` somehow, because there's share UI and data there too.
