### ISSUE TITLE
next parameter isn't working (touchstone)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1624]
### steps to reproduce

1. Log out of discussions, /logout
2. Go directly to a page requirement login, e.g. https://discussions.odl.mit.edu/c/general/ei
  you will be bounced to the login page, with a next parameter, i.e. https://discussions.odl.mit.edu/login/?next=%2Fc%2Fgeneral%2Fei
3. Log in, e.g. with Touchstone

### expected behavior
After you login successfully, you should be redirected to the original destination, i.e. /c/general/ei

### actual behavior
After logging in, you are directed to the home page

**Comment by rhysyngsun** [comment]
Next parameter needs to be passed to the SAML social auth begin url.
