### ISSUE TITLE
Get Heroku CI app working with ec2 reddit instance

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#163]

**Comment by pdpinch** [comment]
Sar, can you add some checkboxes to this issue, so we can see what's been done and what needs to be done?

**Comment by shaidar** [comment]
@pdpinch Do u mean odl-dicscussions-ci? I've been keeping track of that work in this [Issue#165](https://github.com/mitodl/open-discussions/issues/165) unless this is something different.

**Comment by shaidar** [comment]
The heroku CI app is configured now as part of the Heroku pipeline and I setup an ec2 reddit instance which I'm currently working on configuring and app a cert to.

**Comment by shaidar** [comment]
Reddit ec2 ci instance was built and worked with folks on testing it out which appears to be working.
