### ISSUE TITLE
look into changing the block menu icon for ckeditor

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/open-discussions#1632]
we'll most likely need to do that over in https://github.com/mitodl/ckeditor-custom-build

**Comment by ChristopherChudzicki** [comment]
Closing because of #4153.

But there's an easier way starting in v40: https://ckeditor.com/docs/ckeditor5/latest/features/toolbar/blocktoolbar.html#configuration
```
blockToolbar: { icon: "named-icon-or-svg" }
```
