### ISSUE TITLE
Add post_type to posts API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1635]
When we created the article post type, we added a post_type field to the (django) post model. However, we haven't included it yet in the API or use it in the front-end. 

https://github.com/mitodl/open-discussions/blame/master/channels/models.py#L203-L205

Currently the front-end depends on some complex logic to determine if a post is text or article. By adding the post type to the API we can simplify the front-end. There is a separate issue for the front-end change.

**Comment by noisecapella** [comment]
Fixed by #1645

**Comment by noisecapella** [comment]
Still open, wrong issue
