### ISSUE TITLE
RSS widget updates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1640]
See the Zeplin designs:
1. https://zpl.io/2Zky4ZE
2. https://zpl.io/aBq96Xp 
3. https://zpl.io/2jPorg4

### acceptance criteria
- [ ] replace the number input with a dropdown (https://zpl.io/2Zky4ZE)
- [ ] default the number of posts to 5 (https://zpl.io/2Zky4ZE)
- [x] style the item title (https://zpl.io/2jPorg4)
- [x] display 3 lines of the item description (https://zpl.io/2jPorg4)
- [x] open item links in a new tab
- [x] display the pubDate as time since (https://zpl.io/2jPorg4) 
- [ ] style the form (https://zpl.io/2Zky4ZE) (talk to Peter or Ferdi first) 
- [ ] copy:
  >  Title: “Add RSS feed widget”
  >  Box 1: “Title”
  >  Box 2: “RSS feed URL” (Placeholder) 
  >  Text 1: “Max number of items”

### related issues
- [ ] add a preview step, before adding (https://zpl.io/2jPorg4)

**Comment by noisecapella** [comment]
I'm not sure how we can neatly display three lines of an item description, cutting off after the period. Should I just use a regex for this and take a guess at how many characters "three lines" is?

**Comment by pdpinch** [comment]
Can you do the same thing Gavin did in #1722 (now that we're using a react component for rendering the RSS links)?

**Comment by noisecapella** [comment]
The PR is using react-dotdotdot which is the library that #1722 introduced

> replace the number input with a dropdown
What should the options be for the dropdown?

**Comment by noisecapella** [comment]
One other question: should we use the title from the RSS feed as the title to be shown or should we use the one provided when the user adds/edits the widget?

**Comment by Ferdi** [comment]
> What should the options be for the dropdown?

maybe 1-10

> should we use the title from the RSS feed as the title to be shown or should we use the one provided when the user adds/edits the widget?

As the title of the widget ?  It should be the one provided by the user adding/editing the widget

**Comment by noisecapella** [comment]
For the copy there is "Add RSS feed widget" for the title of the dialog. Should we also change the title for the dialog which updates the widget?

**Comment by Ferdi** [comment]
I think "Edit widget" is fine as a title of the dialog.

**Comment by noisecapella** [comment]
Does the dropdown need to have the word "posts" in it? I think it would be difficult to implement that cleanly
