### ISSUE TITLE
Refactor front-end to recognize article post type

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1652]
Currently, the front-end users the presence or absence of post text to determine whether a post is a text post or an article post (see https://github.com/mitodl/open-discussions/issues/1550#issuecomment-450967579). This approach prevents us from adding other posts types in the future. 

Instead, we should use the post type as returned by the posts API (PR #1633) to determine the post type in the front end.

**Comment by aliceriot** [comment]
blocked until #1633 merges

**Comment by pdpinch** [comment]
#1633 has merged
