### ISSUE TITLE
styling for manage widgets 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1653]
See https://zpl.io/bldlQRe

### acceptance criteria:
- [x] Edit and delete buttons should be left aligned, the reorder button should be right aligned.
- [x] Edit delete, and reorder buttons should have a square `#pale-grey` background.
- [x] Use [Reorder icon](https://thenounproject.com/term/reorder/223874/) instead of material `drag_handle`
- [x] Space for the editing buttons should be shorter - in the design there is equal white space between the line, the icons, and the bottom of the widget box, and it is a smaller amount of space than current on the RC site. (I'm not sure how to measure this in Zeplin)
- [x] Spacing between the widget title and the widget body should be consistent (again, I'm having trouble measuring this in Zeplin) 

### nice to have
- [ ] grey out and disable the rest of the interface elements
- [x] move the "Manage widgets" and "Cancel" and "Done" buttons up into the white nav bar, as designed in [this screenshot](https://user-images.githubusercontent.com/430126/50854009-f0846d00-1351-11e9-8e1a-941827e0970c.jpg)

**Comment by pdpinch** [comment]
I updated the description with a link to the screenshot I showed in planning.

**Comment by noisecapella** [comment]
@pdpinch Here's what I have so far, does this look like what you're thinking of?

![screenshot from 2019-01-09 16-58-53](https://user-images.githubusercontent.com/863262/50931464-a3c39380-1430-11e9-93ce-686f62a6aee0.png)

**Comment by pdpinch** [comment]
Since the project is open source, we should use the creative commons-licensed version. Can you download and add it. I'll get back to you about attribution (attribution in code is OK, I believe). 

I'm also going to pay for an account too.

**Comment by noisecapella** [comment]
If you're going to pay for it, it looks like we wouldn't need to attribute it anywhere. For the creative commons version it looks like attribution within the image isn't required if the image is less than 100px, but the text is still part of the downloaded SVG or PNG so we would need to clip it out

**Comment by pdpinch** [comment]
We're going to use https://material.io/tools/icons/?icon=reorder&style=baseline instead. That should already be in the material icon font.

**Comment by noisecapella** [comment]
I noticed that the "Add widget" link has a border around it in the last checkbox above, but the zeplin mockup doesn't have it. Is that part of this issue?

**Comment by pdpinch** [comment]
Yes, please use the button.dark-outlined style for "Add widget" 

> I noticed that the "Add widget" link has a border around it in the last checkbox above, but the zeplin mockup doesn't have it. Is that part of this issue?

**Comment by pdpinch** [comment]
@noisecapella when you have a chance, can you check off the boxes here? I think everything is done except for "grey out and disable the rest of the interface elements"

If that's the case we can close this and I'll open a issue just for that.

**Comment by pdpinch** [comment]
It looks like everything here is done except for "grey out and disable the rest of the interface elements". 

I'm closing this and opening a new issue for that last item, #1747
