### ISSUE TITLE
People widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1655]
The People widget combines elements of the members widget (#1054) and the moderators widget (#1053). 

There is a UX video at https://drive.google.com/file/d/1-PBt3UO4wpVuRlL5gFZMS9kQgJGjUOHi/view?usp=sharing

### MVP acceptance criteria:
- [ ] widget name is "People" not "Members" as used in the video & Zeplin
- [ ] only implement the "Select Members" option
- [ ] search for members by email address (name would be nice)
- [ ] trash can icon removes chosen member
- [ ] back button so user can change the configuration before adding it to the list

### nice to have
- [ ] reordering of selected members (use same icon as widget reorder icon)

### out of scope
- preview the widget before adding it to the list
- styling changes to "Add a widget" form
- "All moderators" option
- "All members" option
- link to "All members"

**Comment by pdpinch** [comment]
I made a couple of updates to the description:

- widget name is "People" not "Members" as used in the video & Zeplin
- preview function is out of scope for this MVP issue

**Comment by noisecapella** [comment]
I think all the checkboxes are handled by #1803 so I'm closing this
