### ISSUE TITLE
Collapse/expand widgets

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1661]
In the manage widget UI the user should be able to expand or collapse individual widgets, or expand and collapse all of them: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5c11220cdef00c2430286c96. The widgets should start off in a collapsed state.

The "Expand all" text should be shown if any of the widgets are collapsed, otherwise "Collapse all" is shown if all widgets are expanded. If there are no widgets this link will not be shown at all. @pdpinch does that sound right?

**Comment by pdpinch** [comment]
How was #1716 related to this? Was it some precursor work?

**Comment by noisecapella** [comment]
It was work I started before switching to #1640, so I made a PR to fix that issue
