### ISSUE TITLE
Follow / Unfollow button

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1663]
As a user, I'd like to be able to follow (subscribe to) a .channel, so that it will appear on my front page, in my left nav and I will get notifications of new posts. 

Similarly, I'd like to be able to unfollow a channel. 

As a moderator or a contributor, I'd like to be able to unfollow a channel and stop receiving notifications, even if I retain my moderator / contributor status. 

### acceptance criteria
- [ ] when not subscribed, display "follow" button: https://zpl.io/VQEJqKk
- [ ] when subscribed, display a "following" button with a drop down: https://zpl.io/a3K9o9Q
  - [ ] "Unfollow channel" => remove subscription
  - [ ] "Leave channel" => remove contributor status & remove subscription
- [ ] update user status in reddit and in discussions app

**Comment by gsidebo** [comment]
@pdpinch Looking at this screenshot: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5bd9df8815d2791b648ee414

Placing that follow/following button means we'll have to move the gear icon to that header row of the content window. I'm no designer, but are we sure that this is the placement we want for that gear icon? The placement of the magnifying glass at the right edge of the post listing column and the gear icon at the right edge of the widget column seems kind of arbitrary to me. If we ever decided to hide the widget column when it has no contents (something I would definitely be in favor of), then I would guess the magnifying glass and the gear would be pushed together? I can make progress on this without a decision on this, but IMO it's something we should resolve soon

**Comment by pdpinch** [comment]
No plans to move the gear at this time.

**Comment by gsidebo** [comment]
@pdpinch So we'll just put the follow/following button next to it (to the left, I'm guessing)?

**Comment by pdpinch** [comment]
after discussion with @gsidebo I edited the description to clarify that "leave" = remove contributor status and remove subscription. 

We don't touch moderator status because a) a moderator can use the channel settings UI to remove themselves and b) there's a use case for stopping notifications but maintaining one's moderator status.
