### ISSUE TITLE
allow editing of the article cover image

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1664]
see https://github.com/mitodl/open-discussions/pull/1660

### acceptance criteria
- [x] allow the user to remove the image
- [x] display the image on the post detail page for the article
- [x] allow the user to upload a new image when editing the article

**Comment by aliceriot** [comment]
on the zeplin designs I don't see anything for removing the image on the create post screen. here's a quick thing I put together, what do you think? it's just a button with a little opacity on it which goes away on hover:

![remove-image-button](https://user-images.githubusercontent.com/6207644/50911479-f768b980-13fd-11e9-979c-bddab5d2d067.png)

![remove-image-buttonhover](https://user-images.githubusercontent.com/6207644/50911483-f9cb1380-13fd-11e9-8e28-c91faf342333.png)

**Comment by pdpinch** [comment]
This will work for now. We will probably take another pass on the layout later, but we need to get this out.
