### ISSUE TITLE
Article edit form needs validation

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1682]
You can edit an article to have a blank body, whereas the post creation form does not allow that. We need to add the same validation behavior and UI to the edit form. **NOTE:** This was noticed on PR #1676. When that merges, in addition to validating the article body, we should include error behavior/UI for failed image uploads like the post creation page already has.

Post creation w/ validation message:
![ss 2019-01-10 at 15 57 24](https://user-images.githubusercontent.com/14932219/50996772-d634c580-14f0-11e9-8ae3-aba02bc5f374.png)

Post detail with article body set to blank:
![ss 2019-01-10 at 15 56 37](https://user-images.githubusercontent.com/14932219/50996774-d7fe8900-14f0-11e9-9dc1-e8ee07e6969c.png)

**Comment by aliceriot** [comment]
We should probably add validation to post editing in general, currently we have none.
