### ISSUE TITLE
Article search not working

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1685]
I'm not sure if this is a limited case or not but some results are not showing up for me. I added [this post](https://discussions-rc.odl.mit.edu/c/george/1sud/unique-text-in-this-article) on RC. When I search "unique" it shows up in the results because it matches the title. However searching "quick" does not bring up any results despite being in the article text. It looks like `article_text` is part of the index and the mapping shows it as an english language field so I don't know what's going on here.

**Comment by noisecapella** [comment]
@mbertrand This is the article search bug mentioned at standup. I'm not sure where the problem is, though it looks like `article_text` is being indexed properly which leads me to suspect it's maybe some problem with the query

**Comment by mbertrand** [comment]
The mapping in RC doesn't match what I have locally.

on RC:
```
                    "article_text": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        }
                    },
```
which is incorrect

Locally:
```
                    "article_text": {
                        "type": "text",
                        "fields": {
                            "english": {
                                "type": "text",
                                "analyzer": "english"
                            }
                        }
                    }
```
which is correct and returns expected search results.

Seems like the mapping on production is also correct.  Not sure yet why it's wrong on RC.

https://<elasticsearch_url>:443/discussions_all_default/_mapping/_doc

**Comment by noisecapella** [comment]
That's strange... I don't know what could cause `article_text` to exist and also have the incorrect mapping

**Comment by mbertrand** [comment]
Reindexing seems to have fixed it, the RC mapping now matches production/local and searching for `quick` returns the post.

**Comment by noisecapella** [comment]
Great!
