### ISSUE TITLE
Post form: error when switch channel

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1687]
As a user, when I create a post, I can currently set or change the channel after choosing the post type. 

However, not all channels allow all post types. This leads to an error when the user chooses a post type (say "article") and then chooses a channel that doesn't allow that post type.

**Comment by pdpinch** [comment]
here's a screencast of the issue: https://share.vidyard.com/watch/gJyWMtB9P383BkT4CLykif?

**Comment by pdpinch** [comment]
Sentry issue: [DISCUSSIONS-K3](https://sentry.io/mit-office-of-digital-learning/discussions/issues/841326923/?referrer=github_plugin)

**Comment by pdpinch** [comment]
@Ferdi I think you hit this bug. I'm not sure what's the best way to avoid it. We could:

- omit channels from the "Will be published in" drop-down that don't support the current post type
- discard the user's draft when they switch to a channel that doesn't support the current post type (maybe preceded by a warning)
- force the user to choose a channel before display the post types

**Comment by aliceriot** [comment]
the current implementation is supposed to do bullet point 2 of what you outlined, so this is a bug

**Comment by aliceriot** [comment]
(we don't show any warning though)

**Comment by aliceriot** [comment]
it does that locally for me, what environment did the issue show up on?

**Comment by aliceriot** [comment]
ah I think I found the issue, I'll work to repro it locally and then open a fix

**Comment by aliceriot** [comment]
could you share the allowed post type settings for the channels where this is happening?

**Comment by aliceriot** [comment]
btw this issue isn't specific to articles, it can be reproduced with the link type by having a channel which allows only text and article posts, for instance.
