### ISSUE TITLE
Text post editor doesn't handle some formatting correctly

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1696]
I made a post with one word and a combination of bold/italic text and when editing something is breaking.

The text post as it displays (this displayed correctly in the editor when I authored the post):

![screenshot_2019-01-14 test 1 mit open learning](https://user-images.githubusercontent.com/28598/51128531-16988a00-17f6-11e9-9f6c-527338f8f433.png)

What I see when I try to edit it:

![screenshot_2019-01-14 test 1 mit open learning 1](https://user-images.githubusercontent.com/28598/51128538-1e582e80-17f6-11e9-99c7-f0238d1b9c64.png)

**Comment by aliceriot** [comment]
I tried out updating the `prosemirror-markdown` package and it seems to fix the issue, I'll open a quick PR
