### ISSUE TITLE
management command for retiring users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1698]
Similar in goal to [`retire_users` in MicroMasters](https://github.com/mitodl/micromasters/blob/master/profiles/management/commands/retire_users.py)

### acceptance criteria
- [ ] mark the user as inactive
- [ ] remove any notification objects / email optins 
- [ ] delete socialauth objects 

### out of scope
- we won't remove posts or comments

### questions
**Q: What should we do about profile pages?**
**partial answer** if nothing else, we can't continue to display a profile page. Perhaps we check the `is_active` bit on the account before rendering the profile page, and return a 404 if it's false.

**Comment by rhysyngsun** [comment]
@pdpinch might be worth updating the notification code to just skip inactive users instead of changing the settings. It would be useful for other cases such as that repeated error we're getting due to an invalid email address one of the users has.

**Comment by pdpinch** [comment]
We should also delete any channel invitations.

**Comment by pdpinch** [comment]
Based on feedback in https://odl.zendesk.com/agent/tickets/29329 I think we also need to null the user's email
