### ISSUE TITLE
Article: changes to cover image upload UI

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1706]
As a user writing an article, I'd like to be able to add or remove the cover image. 

While we're at it, we can also shorten the text in the cover image UI. 

### acceptance criteria
- [x] Add an material.io add image icon https://material.io/tools/icons/?icon=add_photo_alternate&style=baseline
- [x] Remove the text "Optional: Add a cover image to your post Drag an image here or"
- [x] replace the button text "Click to select an image" with "Upload cover image"
- [x] add a link below the button "remove cover image" which hides removes the cover image from the form altogether

### nice to have
- [ ] when the cover image has been removed from the form, add a link to the button bar to "add cover image" so it can be restored (similar to LinkedIn)

**Comment by pdpinch** [comment]
I think that's what @Ferdi had in mind for the icon. 

We would also like the "remove cover image" link, below the button.

**Comment by aliceriot** [comment]
here's a go at the remove link:

![withbutton](https://user-images.githubusercontent.com/6207644/51260432-45d90380-197c-11e9-80a2-f41e863487ef.png)

then it looks like this after you remove it:

![removed](https://user-images.githubusercontent.com/6207644/51260462-59846a00-197c-11e9-9da0-40ceaea6f5f3.png)

**Comment by aliceriot** [comment]
adding the link to the bar is a little more involved, I think I'll take a stab at that after I wrap up the easier changes here and on #1704

**Comment by pdpinch** [comment]
Is everything done here except for the "nice to have" : `when the cover image has been removed from the form, add a link to the button bar to "add cover image" so it can be restored`?

If so we should close this and open a new issue just for that.

**Comment by pdpinch** [comment]
I opened #1746 for the "nice to have" feature. We can close this issue.
