### ISSUE TITLE
Add the ability to search for courses to the front-end

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#1719]
### acceptance criteria
- [x] behind a feature flag
- [x] search box
- [x] facets 
- [x] search results

### related issues (out of scope)
- course detail view (overlay)
- #1800 course index page

**Comment by mbertrand** [comment]
These are the design links I know of:
Front page
https://projects.invisionapp.com/d/main#/console/14225832/339365575/preview
Course detailed info:
https://projects.invisionapp.com/d/main#/console/16297123/337908847/preview
Course search:
https://projects.invisionapp.com/d/main#/console/16297123/337908846/preview

**Comment by mbertrand** [comment]
Should course search only be enabled from the course search page, not the general or channel-specific search pages?

**Comment by pdpinch** [comment]
For now, just the course search page.

**Comment by mbertrand** [comment]
Also should the course front page and detail view also be considered part of this issue or not?  There will be some components in common.

**Comment by mbertrand** [comment]
Front-end needs to get the list of unique course topics for the faceted search options.  I was initially thinking of using Elasticsearch for this, but the query I tried does not return the full list of topics:
```
{
    "size": "0",
    "aggs": {
        "uniq_topics": {
            "terms": {
                "field": "topics"
            }
        }
    }
}
```

So I will probably create & use a django API call instead.

**Comment by mbertrand** [comment]
@Ferdi @pdpinch the designs I've seen have different facets to filter by, I'm assuming this is the correct one:
 - [Topic, Availability, Platform, Level](https://projects.invisionapp.com/share/U5PPJZVQSAW#/337908846_Search)

and not this one:
 - [Topic (subject area), Availability (start date), Platform, Price](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5c4efd5b336414bf1f70da33)

Also there are a lot of topics, more than can fit in one very tall page:

![screen shot 2019-01-29 at 9 13 53 am](https://user-images.githubusercontent.com/187676/51914184-3f984d80-23a6-11e9-933b-d3377a62381c.png)

**Comment by pdpinch** [comment]
You have the correct facets: Topic, Availability, Platform, Level

I have a couple of thoughts on the size of the topic facet:
1. Can we reduce the white space between items?
2. When viewing search results, can we display only the topics that appear in the result set, followed by a "see more" button? This could be a future PR. 
 see, for example, [this Amazon search](https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=r2d2)

**Comment by Ferdi** [comment]
@mbertrand I suggest let's have the basics in place first and deal wit details (like long list of topics) later

**Comment by mbertrand** [comment]
Here are the current 'Level' categories.  'Both' is the value for one OCW course imported so far ("STAR: Software Tools for Academics and Researchers"), my guess is that means both 'Graduate' and 'Undergraduate'?

<img width="364" alt="screen shot 2019-01-29 at 2 37 44 pm" src="https://user-images.githubusercontent.com/187676/51935336-ac760c80-23d3-11e9-88e9-28b446adc361.png">

**Comment by mbertrand** [comment]
@Ferdi @pdpinch Latest screenshots:

**Desktop, channel sidebar closed:**

![screen shot 2019-01-29 at 3 47 22 pm](https://user-images.githubusercontent.com/187676/51939694-1d222680-23de-11e9-8f69-202bc1721f44.png)

**Desktop, channel sidebar open:**

![screen shot 2019-01-29 at 3 47 39 pm](https://user-images.githubusercontent.com/187676/51939705-201d1700-23de-11e9-92b7-69981abbb72e.png)

**Mobile, top of page:**

![screen shot 2019-01-29 at 3 48 21 pm](https://user-images.githubusercontent.com/187676/51939710-23b09e00-23de-11e9-916e-748031a71c9e.png)

**Mobile, start of results after facets:**

![screen shot 2019-01-29 at 3 48 37 pm](https://user-images.githubusercontent.com/187676/51939716-26ab8e80-23de-11e9-836e-890aaf2481b3.png)

**Comment by Ferdi** [comment]
Looks great. Do you want to call it done as a first pass?

Btw, I think we decided to remove "level" facet

Is this going to be behind feature flag?

**Comment by mbertrand** [comment]
I still need to add a feature flag, though there aren't any links to the course catalog search page from the rest of the site.  The main search page and channel search pages don't include courses.

**Comment by mbertrand** [comment]
subject facets at top, then availability, platform
facets in one card
shorten width of search field
