### ISSUE TITLE
Fix post pinning

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1727]
To reproduce:

1. Go to a channel page
1. Click the dot menu to reveal the dropdown menu
1. Click "Pin"

**Expected:** The post should be pinned and the UI should reflect that ("Pin" option changes to "Unpin", pushpin icon appears on the left side of the post card
**Actual:** Nothing happens

Dev note: the PATCH request triggered by clicking "Pin" has `sticked: false` in the request body.

**Comment by aliceriot** [comment]
this was my :woman_facepalming:
