### ISSUE TITLE
Fix awkward clickable areas in post summary dropdown menu

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1728]
Clicking on the post summary dropdown menu items can result in unexpected behavior. If you hover over the actual text of one of the options then click, the cursor changes to indicate a link/button, the expected action is executed, and the menu closes. If you click in an area of the menu that doesn't change cursor when you hover (i.e.: outside of the `<li>` elements but still inside the `<ul>`), nothing happens and the menu remains visible (also as expected). If, however, you hover to the right of the actual menu item text then click, the cursor changes to indicate a link/button, but the expected action is _not_ executed and the menu disappears. The red arrows in this screenshot indicate the 2 areas where you can hover and click to reproduce this. 

![ss 2019-01-16 at 15 07 05](https://user-images.githubusercontent.com/14932219/51276059-a6c70280-19a1-11e9-8025-6b2e7681a02d.png)

The cursor changes because the `<li>` tag, not the `<a>` tag, has a CSS rule to change the cursor. It's not clear why the menu closes when you click that area

**Comment by aliceriot** [comment]
I think there's a handler that closes the menu after a click - the intended thing was so that you didn't have to close the menu by clicking outside of it after selecting the action you wanted to take. obviously though the click target to trigger the actual callback needs to be bigger though.
