### ISSUE TITLE
Set the title

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#174]
Currently it's `open_discussions`

- [x] homepage
- [x] create channel
- [x] submit post
- [x] view post
- [x] view channel

**Comment by aliceriot** [comment]
I think we used this in MM: https://github.com/gaearon/react-document-title

**Comment by roberthouse54** [comment]
Home Page:
MIT Open Discussions | MicroMasters

Create a channel:
Create a Channel

Submit a Post:
Submit a Post

Channel:
[Channel Name]

Post
[Post Title]

**Comment by roberthouse54** [comment]
Here is another option:

Home Page:
MIT Open Discussions | MicroMasters

Create a channel:
Create a Channel | MIT Open Discussions

Submit a Post:
Submit a Post | MIT Open Discussions

Channel:
[Channel Name] | MIT Open Discussions

Post
[Post Title] | MIT Open Discussions

**Comment by pdpinch** [comment]
I like these, but if it's hard to include "MicroMasters" in the home page title, we can just do "MIT Open Discussions"
