### ISSUE TITLE
Figure out post summary styling needs and user-uploaded thumbnail dimensions

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1745]
#1733 (PR #1741) made some styling updates to post summary cards. Among the desired changes: make the thumbnail occupy more space so the cards look less sparse. This was doable with link thumbnails since we can request exact dimensions from embedly, so we increased the width and height in our requests. User-submitted article cover images, on the other hand, are uploaded in our own back-end and the thumbnails are restricted to exact dimensions (201px wide, 103px tall). As a result, we have no good way of increasing the vertical space that these thumbnails occupy.

Possible solutions:
- Batch update script to generate new thumbnails with increased dimensions
- Upload all existing thumbnails to embedly, and have them serve our thumbnails instead

EDIT (02/05/2019):
- We will be using embedly to serve the article thumbnails from S3
- As part of this issue, we also want to configure development environments to upload to S3 so we can see these images when we run the app locally

**Comment by Ferdi** [comment]
> User-submitted article cover images, on the other hand, are uploaded in our own back-end
I thought we were using a third party provider for this 

> the other hand, are uploaded in our own back-end and the thumbnails are restricted to exact dimensions (201px wide, 103px tall)
Where is this restriction imposed ?  In the detailed page view the image is bigger than 201x103

**Comment by gsidebo** [comment]
@Ferdi The restriction is imposed here: https://github.com/mitodl/open-discussions/blob/master/channels/utils.py#L24. Thumbnail images are generated from the original (which is what you see on the detail page) and the dimensions are enforced based on that variable. We are not using embedly or any other third-party provider for user image uploads. This PR changed the dimensions for that thumbnail - https://github.com/mitodl/open-discussions/pull/1608 - but it looks like the dimensions were already restricted before that.

**Comment by pdpinch** [comment]
I was surprised to learn this, but it looks like in PRs #1599 and #1608 we reused the approach we took with profile thumbnails (uploading to s3 and resizing with PIL) instead of using the approach we used with link post thumbnails (using the embed.ly image API). I think this was a mistake.

**Comment by gsidebo** [comment]
One possible solution: in two different PRs, (1) write a script that upload those images to embedly, and (2) change the logic for saving those uploaded images and change the image source paths to point to embedly. Not trivial but it can be done

**Comment by Ferdi** [comment]
I don't think you need to upload images to Embedly. Should be able to point to the original image and Embedly should resize on the fly
