### ISSUE TITLE
livestream "widget" on front page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1767]
As a user, I'd like to see what's happening at MIT right now. 

The MVP department webcasts dozens of videos every week, using livestream.com. We can embed a simple "What's happening now" from livestream.com on the front page.

**Comment by aliceriot** [comment]
it looks like there are two basic options for getting information from the livestream API about what's going on.

- we can set up an endpoint to receive webhooks from livestream, and we'll a POST request from them whenever a stream starts or ends
- we can hit the livestream 'event' API to get upcoming events, and we can process the return value to figure out if there is an event going on right now. I think with the information returned here we can then embed the stream if we want to

**Comment by aliceriot** [comment]
specifically I think we could use this API: https://livestream.com/developers/docs/api/#get-upcoming-events

it doesn't specify whether or not it includes events that are currently live, but it would be weird if it didn't...
