### ISSUE TITLE
Channel about page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1778]
As a channel moderator, I'd like to have an about page where I can explain the channel at length, using the same features as an article. 

As a user, I'd like to be able to click an about tab on the channel listing page and find out more about the channel. 

### acceptance criteria:
- [x] add a field to the channel model for storing ckeditor data (similar to article) 
- [x] display an "about" tab on the channel listing page, next to the "Home" tab. 
- [x] when clicked, display the rendered contents of the "about" field
- [x] display an edit button on the about page to channel moderators, similar to the edit button on the post detail page for articles
- [x] the editor interface should function similarly to the article editor interface

**Comment by aliceriot** [comment]
one question here - should the about page have a cover image, similar to the cover image for article type posts?

**Comment by pdpinch** [comment]
It doesn't need a cover image, because it doesn't need a thumbnail. 

I presume that, like an article, users will be able to embed images in the page. Just not at the top.

**Comment by aliceriot** [comment]
ok cool. and yeah, we'll get image embedding out of the box just from using the ckeditor.

**Comment by pdpinch** [comment]
There was a lingering question about how the user creates the about page initially. We've decided to avoid this by just displaying the about tab at all times. We know that means there will be channels with no content. Laura or I will take care of populating it after the feature goes live.

**Comment by aliceriot** [comment]
ok, what I was planning to do was to always show the about tab to users who have permission to edit it, and conditionally show / hide it based on the presence of the about field for user who do not. I can just go ahead and show it all the time though, it's slightly easier that way.

**Comment by pdpinch** [comment]
Oh, that would be nice: conditionally show / hide it based on the presence of the about field for user who do not have permission to edit. If it's not too much work, that would be better.

**Comment by aliceriot** [comment]
sure, it's not that complicated and we have helper functions already for a lot of those permissions checks

**Comment by aliceriot** [comment]
@pdpinch how does this look for a super-basic editing UI? I can try to whip up something more fancy, but since this is just going to be shown to moderators I was thinking we might be able to get away with something simple:

![basicedit](https://user-images.githubusercontent.com/6207644/52584569-5c9a3b00-2e00-11e9-9699-c2775764f778.png)
![basicsave](https://user-images.githubusercontent.com/6207644/52584588-6885fd00-2e00-11e9-8f92-d1b0cadbdad2.png)

**Comment by pdpinch** [comment]
I thought we were just going to reuse the article editor UI?

**Comment by aliceriot** [comment]
yeah I'm reusing the article editor component, I'm just checking in about the button UI, wondering if you want something fancier than that.

**Comment by pdpinch** [comment]
Nope. We don’t need anything fancy.
