### ISSUE TITLE
Bug: Rest api to add moderator returns a 201 even if moderator already exists

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#178]
This should be a 200 I think.

**Comment by rhysyngsun** [comment]
This bug also exists for adding subscribers, they could probably just be fixed in the same PR

**Comment by noisecapella** [comment]
#189 changed this behavior to return a 201 even for repeated adds of moderator, subscriber and contributor, and a 204 for repeated deletes. This is because we would need extra information from reddit to see if a user is already a moderator, which would be an extra fetch.
