### ISSUE TITLE
Create article validation UX

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1796]
I'm not sure what the prescribed fix here would be other than scrolling up to the error, but if you create an article type post and attach a cover image, the page can become long enough that if you have a validation error about the post / cover image editor (e.g. you omitted the title), you won't see the error, so the submit button will just not seem to work:

![screenshot_2019-02-01 submit a post mit open learning](https://user-images.githubusercontent.com/28598/52142537-ec80fd80-2626-11e9-9040-fa34d70a62a5.png)

**Comment by pdpinch** [comment]
Related to #1682

**Comment by aliceriot** [comment]
I @Ferdi and I discussed scrolling up to show the validation message in this case. I believe that's what we did to solve a similar issue with the profile forms on micromasters.
