### ISSUE TITLE
Course index page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1800]
As a learner, I'd like to get an introduction to what online courses are offered by Open Learning. 

See https://zpl.io/VDqmDNJ

### acceptance criteria:
- [x] behind a feature flag (can be the same for the course search interface)
- [x] omit "recommended for you" for MVP 
- [x] the list of "featured" courses can be managed manually in the django admin
- [x] there should already be an API for "upcoming courses" a date-sorted list of courses with start dates in the future
- [x] there should already be an API for "new courses," the most recently created courses
- [x] banner for course index page

### out of scope
- "recommended for you" courses

**Comment by pdpinch** [comment]
In #1888 we decided to display _all_ the course subject areas on the search result card. Should we do the same here? I don't think we'll have room. 

See [Matt's question](https://github.com/mitodl/open-discussions/issues/1888#issuecomment-467988180)

**Comment by aliceriot** [comment]
@pdpinch do we also want to add the course banner shown at the top of the mockups at the same time? does that banner also get shown on the course search page?

**Comment by pdpinch** [comment]
Yeah, we should add it here and it should be on the search results page too.

**Comment by pdpinch** [comment]
@aliceriot -- I just spoke with Ferdi about [your question](https://github.com/mitodl/open-discussions/issues/1800#issuecomment-470641554). We decided to keep the banner on the course index page, but omit it from the search results page.

**Comment by aliceriot** [comment]
one other question - when the user clicks on a course should we open the course drawer, as we do currently on the course search page?

**Comment by aliceriot** [comment]
(and is that an MVP feature, haha)

**Comment by pdpinch** [comment]
In the interests of quicker MVP, I would say "yes" -- when the user clicks on a course open the course drawer.

**Comment by aliceriot** [comment]
![courseindex_basicdrawer](https://user-images.githubusercontent.com/6207644/54285271-04c62f80-4578-11e9-9838-e7618bba6bea.png)
![courseindex_basic](https://user-images.githubusercontent.com/6207644/54285274-055ec600-4578-11e9-9e10-45c1714b1358.png)

I still need to do the banner, I might leave that off the initial PR if that's alright just so it's not too huge.

@Ferdi

**Comment by pdpinch** [comment]
@aliceriot can we close this?

**Comment by pdpinch** [comment]
Ok, I added a checkbox to the description for adding the banner, as mentioned in #1919

**Comment by aliceriot** [comment]
@pdpinch for the banner image do we want to stick with what's in the mockup or use a different image?

**Comment by pdpinch** [comment]
Can you make this work, while I look for something better?

https://ocw.mit.edu/feature-about-get-started-dome.jpg

**Comment by aliceriot** [comment]
basic mockup of the banner:

![mockupasdf](https://user-images.githubusercontent.com/6207644/54707901-8ee23b00-4b18-11e9-856e-457ae1dff1c3.png)

this is using our existing search text box (which doesn't really match the one in the mocks) - should I try to style a new one to match the mocks or just stick with what we have currently?

I'm also not sure about how good the dome image looks...
