### ISSUE TITLE
Add opengraph metadata tags for better social sharing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1801]
As user sharing an MIT Open post on Facebook, I'd like to see the correct title, description and link show up, especially for public posts.

See https://developers.facebook.com/docs/sharing/webmasters/ and https://developers.facebook.com/docs/sharing/best-practices

### acceptance criteria:
- [ ] set `og:url` to the canonical URL for the page
- [ ] set `og:title` to the post title (omit the branding "| MIT Open" as that will be displayed elsewhere)
- [ ] For public posts, set `og:description` to the first few lines of the post text.
  If possible, use `react-dotdotdot` to truncate the text. If not, just limit it to the first 4 sentences. 
- [ ] For private posts, omit the description to avoid leaking content  
- [ ] For public posts, set `og:image` to the URL for the link image (embedly) or the cover image (article). Use the full size URL. 
- [ ] For private posts, set `og:image` to the MIT dome from MicroMasters, i.e. https://do5zh7b0lqdye.cloudfront.net/static/images/lp_hero.jpg

You can test the markup with https://developers.facebook.com/tools/debug/sharing/

**Comment by gsidebo** [comment]
@pdpinch In addition to post detail pages, I'm guessing we might want to add some tags for channel pages and possibly the front page. Let me know what you think

**Comment by pdpinch** [comment]
Sure thing. 

I haven’t thought through the metadata yet, but if you want to propose something (in the PR or in the comments), go for it.

**Comment by pdpinch** [comment]
@gsidebo with #1872 merged, can we close this?
