### ISSUE TITLE
reordering widgets prevents saving

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1806]
Reordering widgets causes a similar error/behavior to #1791 

Video recording at https://share.vidyard.com/watch/wMGLJdRT49m1ygW8pReDfP?

console log: 
[discussions-rc.odl.mit.edu-1549302041952.log](https://github.com/mitodl/open-discussions/files/2829161/discussions-rc.odl.mit.edu-1549302041952.log)

**Comment by noisecapella** [comment]
This was some old data which didn't save under the new feed_display_limit validation rule. We updated the data to be under the maximum allowed on the backend.
