### ISSUE TITLE
Bump ES version to fix "more like this" bug

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1810]
#1797 introduces the related posts sidebar to the post detail page. That feature uses [Elasticsearch's More Like This query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html). Due to an ES bug, a text post with a title and an empty body will not return anything for a "more like this" query. This bug was fixed in ES 6.4. We should try bumping up to that version and test that nothing else breaks.

**Comment by aliceriot** [comment]
@mitodl/devops what do we need to do in order to test out this change?

I ran a quick test locally and rebuilt my index without any problems (I did that just to confirm that 6.4 fixed the issue we were seeing).

**Comment by blarghmatey** [comment]
We will need to upgrade the cluster in AWS. Any reason why you didn't go to 6.6?

**Comment by gsidebo** [comment]
6.4 was the release that fixed the bug in question & theoretically we're safer from breaking changes with a "closer" release, but I'm happy to try this out with 6.6. I'll keep you posted
