### ISSUE TITLE
Add embedly link preview content to the index

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1811]
Link posts cannot be found via search based on their URL nor the contents of the site being linked to. Example: if I have a link post for the url "news.mit.edu", I cannot find it by entering "mit.edu" into the search bar, nor can I find it using any text that exists in the body of that page. In addition to that, link posts can only be considered related to a given post based on the post title, channel, and author (related posts first implemented in #1748, PR #1797). Indexing the web page contents from embedly will give us a way to search for these link posts in a more meaningful way.

Tech notes: 
1. We might be able to use `plain_text` to index this content, but we should think through the implications of that
2. Obviously the contents of a web page can change, and therefore the indexed contents of a site can become stale. We'll need to decide how much we care about that staleness

EDIT (02/05/2019): For the time being we're not going to worry about updating the site preview content from embedly after we first index it.

**Comment by aliceriot** [comment]
I think from embedly we'll usually get back a "description" field, which might be useful for this

**Comment by gsidebo** [comment]
@pdpinch @Ferdi - I'm indexing the preview description block that embedly gives us, but we might also want to think about adding some other values they provide to the text that we index. Here's some partial JSON documents we get back (with their respective URLs above them):

```json
// news.mit.edu
{
  "description": "MIT News is dedicated to communicating to the media and the public the news and achievements of the students, faculty, staff and the greater MIT community.",
  "title": "MIT News | Massachusetts Institute of Technology",
  "provider_name": "Mit",
}
// https://www.theatlantic.com/science/archive/2019/02/how-to-stop-mosquito-bites/582190/
{
  "description": "NPY acts by sticking to receptor proteins, and the pharmaceutical industry has tried to develop appetite-controlling drugs that target these receptors. Duvall got her hands on some of these drugs five years ago, and fed them to Aedes mosquitoes.",
  "title": "A New Way to Keep Mosquitoes From Biting",
  "provider_name": "The Atlantic"
}
```

I could see `title` and `provider_name` being relevant to searches and for fetching related posts. If both of those values were added to the text that we index, it might look like this for the second example: `The Atlantic - A New Way to Keep Mosquitoes From Biting - NPY acts by sticking to receptor proteins, and the pharmaceutical industry...`. Let me know what you think

**Comment by pdpinch** [comment]
@gsidebo can you do a quick RFC PR for this? Since we're talking about changing the search index, I think it would be worth some wider discussion. 

Questions I have: 
- are these json snippets saved in the database, or in the ES index, or both? 
- How is re-indexing handled? 
- Are there any side effects from overloading the `plain_text` in the way you proposed, e.g. on the post summary card? 

That said, if we want to iterate on this, I can also see just mapping the contents of `"description"` into `plain_text`.

**Comment by Ferdi** [comment]
@gsidebo  how about "content" filed ? https://embed.ly/docs/explore/extract?url=https://www.theatlantic.com/science/archive/2019/02/how-to-stop-mosquito-bites/582190/

**Comment by gsidebo** [comment]
@pdpinch Sure I can write something up

@Ferdi We don't actually get the `content` field in our API call response. I think you're only getting that field b/c you're using their API explorer. Additionally, I think most of the truly relevant content that we want for searching and for finding related posts should be in the description field

**Comment by gsidebo** [comment]
@pdpinch Sorry, I wasn't clear enough. What I'm proposing doesn't involve additional fields in the search index, nor a different data type. I'm suggesting that we concatenate those relevant values from embedly's JSON response into a string (separated by dashes, et al), and use that for the `text` field on the `Post` model. The `Post` model object is eventually serialized for ES, at which point we use that `text` value to populate `plain_text`. I can write up a quick RFC but you might consider it just a sanity check. No major indexing changes happening here

**Comment by Ferdi** [comment]
@gsidebo right, I think that's the api we should use for this.  "content" is the equivalent of the content in our article / text type posts
