### ISSUE TITLE
Course search: course detail view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1820]
When the user clicks on a course in the course search results, an overlay card slides out from the right with course details and links to take the course. 

Designs for [MITx detail](https://zpl.io/VqKQ63Z) and [OCW detail](https://zpl.io/beoygPY) may be slightly out of date. In particular, we _will not_ include department.

**Comment by mbertrand** [comment]
@pdpinch @ferdi how important is the "slides out from the right' part?  The `Drawer` component in the react-materialcomponents library we're using (rmwc) would need to be overridden somehow to enable this, because sliding from the left is cooked in.  I can make it display on the right without doing so (via some css tweaks), but it still slides from the left.

**Comment by Ferdi** [comment]
@mbertrand I don't think the sliding direction is important.

**Comment by mbertrand** [comment]
@pdpinch @ferdi looks like department name is back for OCW, plus "effort" and "length" for MITx - is that right?

**Comment by mbertrand** [comment]
Regarding the "Take Course on [Mitx|OCW] buttons - presumably these are links to the course on mitx or ocw.  There is a `url` field in the `raw_json` for OCW that seems to work if `https://ocw.mit.edu/` is prepended to it.  

For MITx, there's a `marketing_url` field, for example "'Making Science and Engineering Pictures" has a `marketing_url` of https://courses.edx.org//courses/course-v1:MITx+0.111x+2T2015/course/.  But that doesn't seem as informative as this page - https://www.edx.org/course/making-science-engineering-pictures-mitx-0-111x - and there's nothing like that URL in the imported data.

**Comment by pdpinch** [comment]
argh. I can’t believe we overlooked a URL field? 

I’ll open an issue. 

You have the right approach to constructing the OCW URL. 

I’m not sure what’s going on with the MITx URL. I hope maybe that course is an edge case. It was last offered 4 years ago.

**Comment by mbertrand** [comment]
For mitx looks like I should be able to construct a URL like this: `https://courses.edx.org/courses/<course_id>/course/`

But I haven't tested every single one to make sure it works.  Also, that still leads to the less informative URL, which I think is meant for students who are enrolled.

**Comment by pdpinch** [comment]
It is edX’s intent that we use the course-level `marketing_url`

If it appears to be broken for some courses, we can try to address that upstream with edX.

**Comment by mbertrand** [comment]
The course-level `marketing_url` is either just `https://www.edx.org/course/?` with some query parameters unrelated to the specific course, or a course-specific URL which doesn't work correctly such as `https://www.edx.org/course/mitx15763x`.  

Only the course_run `marketing_url`s seem to have course-specific URL's that actually work, but they are not consistent - some go to the about page, some go to the page meant for enrolled students.

**Comment by mbertrand** [comment]
@pdpinch @ferdi Can I get the original icon files from zeplin, or should I just screenshot them?

![screen shot 2019-02-11 at 1 29 51 pm](https://user-images.githubusercontent.com/187676/52585140-00d0b180-2e02-11e9-997d-830c5d93c374.png)

**Comment by pdpinch** [comment]
https://github.com/mitodl/micromasters/blob/master/static/images/mitx_logo.png

**Comment by pdpinch** [comment]
There's probably a better place to get the OCW logo, but it's based on this: https://pbs.twimg.com/profile_images/912676696620359680/e-G5lqVs_400x400.jpg

**Comment by mbertrand** [comment]
`Effort` and `Length` fields are going to be excluded from the detail view for now, may be added later.  When they are added, they should be added as new fields for the `Course` model.    

These fields are specific to MITx as shown in the design.  The `raw_json` fields that seem relevant are `min_effort`, `max_effort`, and `weeks_to_complete` - all integers.  They are in the `course_runs` list, of the raw_json, and different course_runs often have different values for each of these fields.

`Department` is also going to be excluded.

**Comment by mbertrand** [comment]
@Ferdi @pdpinch is the `...Read More` link on the design supposed to expand the rest of the description inside the detail view, or is it supposed to be another link to the external course URL on MITX/OCW?

**Comment by mbertrand** [comment]
@pdpinch @Ferdi Screenshots of progress so far, what do you think of the mobile view in particular, the styling of the link buttons to OCW could probably use some improvement.

![screen shot 2019-02-14 at 4 52 48 pm](https://user-images.githubusercontent.com/187676/52820159-464ae400-3079-11e9-90c5-fbdd245ccd5d.png)

![screen shot 2019-02-14 at 4 53 12 pm](https://user-images.githubusercontent.com/187676/52820165-49de6b00-3079-11e9-9e89-fcebab05caa9.png)
