### ISSUE TITLE
Upgrade Elasticsearch to 6.5.4 in deployed environments

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#1828]
#1819 bumped the Elasticsearch docker image from 6.2.4 to 6.5.4. We will need to perform & test the same upgrade in our deployed environments. This issue covers the work to upgrade in CI/RC, reindex, test, then do the same in production.

**Comment by gsidebo** [comment]
We'll wait on #1783 to merge before doing this since that PR will dramatically improve reindexing performance

**Comment by shaidar** [comment]
Upgraded Elasticsearch RC cluster to `6.6.1`. Will give it a few days for testing and then do a rolling upgrade for production.

**Comment by pdpinch** [comment]
@shaidar can this be closed?

**Comment by shaidar** [comment]
Upgraded the Elasticsearch prod cluster to 6.6.1
