### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#183]
See https://github.com/mitodl/reddit-config/issues/13

**Comment by pdpinch** [comment]
@giocalitri When you have some time, can you update this issue with a brief description of what you're doing for load testing?

**Comment by pdpinch** [comment]
@giocalitri When you have some time, can you update this issue with a brief description of what you're doing for load testing?

**Comment by pdpinch** [comment]
We have multiple load tests scripts committed to the locust repo at https://github.com/mitodl/locust-tests/tree/master/open_discussions
