### ISSUE TITLE
add url field to course model

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1834]
As a user searching courses, I'd like to be able to link to them 

#### Designs and Mockups

part of #1820 

#### Acceptance Criteria:

- [ ] for OCW courses, we can construct a complete url by prepending `https://ocw.mit.edu/` to the url field in JSON files
- [ ] for MITx courses, we should use the `marketing_url` which _should_ contain a link to the "About" page on edX, which is the preferred landing page. 

#### Out of Scope

- it appears that some courses have incorrect data for the marketing URL, see https://github.com/mitodl/open-discussions/issues/1820#issuecomment-461784055

**Comment by mbertrand** [comment]
Looks like it is a mishmash for mitx marketing_url.  Most are of the form `https://courses.edx.org//courses/<course_id>/course/` and are contained in the `course_runs` section of the raw_json.

Only 150 seem to have the better URL like this:
- https://www.edx.org/course/entrepreneurship-103-show-me-the-money?utm_medium=affiliate_partner&utm_source=ocwprod-mit-opencourseware
- https://www.edx.org/course/microstructural-evolution-in-materials?utm_medium=affiliate_partner&utm_source=ocwprod-mit-opencourseware

**Comment by mbertrand** [comment]
Actually after searching through all course runs for each course, 368 have the preferred URL somewhere in there.

**Comment by mbertrand** [comment]
I added code in the `CourseSerializer` to extract a url from the raw json, so as to continue progress on the course detail view.  It could be used to assign a URL to a new `Course.url` field instead:

```python

OCW_BASE_URL = "http://ocw.mit.edu/"
MITX_BASE_URL = "https://www.edx.org/course/"
MITX_ALT_URL = "https://courses.edx.org/courses/"
```
```python
    def get_course_url(self, course):
        """
        Get the url for a course if any
        """
        if course.platform == PlatformType.ocw.value:
            urlpath = course.raw_json.get("url")
            if urlpath:
                return urljoin(OCW_BASE_URL, urlpath)
        elif course.platform == PlatformType.mitx.value:
            preferred_urls = [
                run["marketing_url"]
                for run in course.raw_json["course_runs"]
                if MITX_BASE_URL in run["marketing_url"]
            ]
            if preferred_urls:
                return preferred_urls[0].split("?")[0]
            return "{}{}/course/".format(MITX_ALT_URL, course.course_id)
        return None
```

**Comment by mbertrand** [comment]
@pdpinch did you want zagaran to work on this or should I continue with it?

**Comment by mbertrand** [comment]
@ferdi @pdpinch Out of 632 Mitx courses, the URL's I calculated for 262 are like this, going to the less-useful web page designed for enrolled students:
```
 ('MITx/EECS.6.002x/3T2013',
  'Circuits and Electronics',
  'https://courses.edx.org/courses/MITx/EECS.6.002x/3T2013/course/'),
 ('course-v1:MITx+8.421.3x+3T2015',
  'Atomic and Optical Physics I– Part 3: Atom-Light Interactions 1 -- Matrix elements and quantized field',
  'https://courses.edx.org/courses/course-v1:MITx+8.421.3x+3T2015/course/'),
```

While 370 are like this, going to the more informative about page:
```
 ('course-v1:MITx+7.28.1x+3T2018',
  'Molecular Biology - Part 1: DNA Replication and Repair',
  'https://www.edx.org/course/molecular-biology-part-1-dna-replication-and-repair'),
 ('course-v1:MITx+15.662x+1T2019',
  'Shaping Work of the Future',
  'https://www.edx.org/course/shaping-the-future-of-work-0'),
```
