### ISSUE TITLE
Embed widget not working for https://climate.mit.edu/

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1836]
For some reason embedding the URL `https://climate.mit.edu/` does not work, but `https://climate.mit.edu` (no trailing slash) does. 

### Steps to Reproduce

1. Create an embed widget
2. Enter the URL `https://climate.mit.edu/` (notice trailing slash)

### Expected Behavior

After a brief pause, a thumbnail and description from https://climate.mit.edu/ loads.

### Actual Behavior

Nothing loads

Looking at the api response, it seems like embedly isn't returning us anything. However, if I try the same URLs at https://embed.ly/code?url=https%3A%2F%2Fclimate.mit.edu%2F the card loads fine.

**Comment by aliceriot** [comment]
I'm not able to reproduce this locally:

![cliiiiimate](https://user-images.githubusercontent.com/6207644/52572773-9b22fc00-2de6-11e9-8abe-4bc629c2928f.png)

top one is with slash, bottom one is without. which environment did you see this on?

**Comment by pdpinch** [comment]
This can't be reproduced any more. Perhaps it was a caching issue with the embedly service?
