### ISSUE TITLE
Investigate removing embedly widget title 

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#1856]
If possible we should see if we can remove the title from the embedly widget. This is inside an iframe so it may be impossible, I forget what we can do with CSS and iframes. There could be some way to configure the embedly platform to omit it.

If we determine this to be difficult to do, for example, if we require switching away from the embedly card API, then @pdpinch says we should just skip it.

#### Designs and Mockups
![screenshot from 2019-02-13 16-55-36](https://user-images.githubusercontent.com/863262/52746750-403d0080-2fb0-11e9-92d3-739b74a50481.png)

#### Acceptance Criteria:

- [ ] the "wikipedia" text in the image above and logo is not visible

#### Out of Scope

- Not going to investigate switching away from the embedly card API to solve this

**Comment by aliceriot** [comment]
here are the options we can configure for embedly cards: https://docs.embed.ly/docs/cards#customize

There is no option for disabling certain fields, unfortunately.

One option that embedly does provide is using a `<style>` tag with class `embedly-css` to style the card: https://docs.embed.ly/docs/cards#css-customization

We can probably use that to hide any elements we don't want via CSS.
