### ISSUE TITLE
Course Seach: Subject area facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1887]
As a search user, I'd like to have a full-featured Subject Area facet

#### Designs and Mockups

similar to the "Country" facet of this Searchkit demo: http://demo.searchkit.co/imdb

e.g. 
![image](https://user-images.githubusercontent.com/430126/53446383-d6c1e680-39e0-11e9-8271-d124e887988d.png)

and 
![image](https://user-images.githubusercontent.com/430126/53446400-e17c7b80-39e0-11e9-9654-ee1ff3e4533b.png)

#### Acceptance Criteria:

- [ ] Display the hit count next to each subject filter
- [ ] Don't display a subject for which there are zero hits in the current result set
- [ ] Sort the Subject area filters by hit count
- [ ] Only display the first 5 Subject area filters (we may want to try different numbers for this)
- [x] When the checkbox next to a filter is checked, add it to the search filter
- [ ] When a search filter is added, display it above the search results -- as a reminder to user of which filters are active and so that they can be removed.

**Comment by mbertrand** [comment]
An `availability` field should be added to the `Course` model and search index first, in order to display facet counts properly for `Current`, 'Prior`, and `Upcoming` facets - as described in #1861

**Comment by mbertrand** [comment]
@pdpinch @ferdi: Is this supposed to apply to facets in general (including platforms, availabilities, etc)? Or only subject areas?

Assuming all facets, a consequence of only displaying facet choices contained in the current result set is that it is no longer possible to select more than one facet choice for platform and availability - as soon as one option is selected for either of those, the counts for all other options will be 0 in the results.  For example, selecting "Upcoming" for availability => 0 results with Prior, Current, and Coming Soon, so a user won't be able to select both "Current" and "Upcoming".
