### ISSUE TITLE
Course Search: display all Subject areas on Course card

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1888]
As a search users, it would make more sense to see all subject areas for a given course in the search results. 

Currently, we only show one of the subject areas on the Course Card. 

#### Designs and Mockups

none

#### Acceptance Criteria:

- [ ] Find out which course(s) have the maximum number of Subject areas and include them in the screenshot of the PR
- [ ] Clicking a course subject on the Course card in the search results should link to a search with that filter applied.

**Comment by mbertrand** [comment]
`Clicking a course subject on the Course card in the search results should link to a search with that filter applied.` 
- Including any other current search filters?  (I'm assuming yes).
- The `CompactCourseDisplay` component will presumably be used on the non-search course index page as well, should the topics still link to search results?
- Should the availability and price for each course also link to search results with that facet applied?

**Comment by mbertrand** [comment]
Some courses have 8 topics, which will be a problem at narrow/mobile browser widths.

![screen shot 2019-02-27 at 2 21 22 pm](https://user-images.githubusercontent.com/187676/53516806-2c5ac980-3a9b-11e9-8b75-e1ac91f0e208.png)

![screen shot 2019-02-27 at 2 21 45 pm](https://user-images.githubusercontent.com/187676/53516811-31b81400-3a9b-11e9-838c-0d9ce5abd976.png)

**Comment by mbertrand** [comment]
@pdpinch @Ferdi  The current PR for the course detail view makes a click anywhere on the card (including the subject areas) open the detail view.  Should this be restricted to just the title and thumbnail?

**Comment by mbertrand** [comment]
I went ahead and made the availability and platform on each card update the facets as well.

Should they appear with a different background color if the facet is already selected? And if so, should clicking it unselect the facet? For example:

![screen shot 2019-02-28 at 12 40 49 pm](https://user-images.githubusercontent.com/187676/53586441-2e359300-3b56-11e9-93d1-60a473a0a716.png)

**Comment by pdpinch** [comment]
Good questions @mbertrand 

> `Clicking a course subject on the Course card in the search results should link to a search with that filter applied.` Including any other current search filters?  (I'm assuming yes).

Yeah. I'd like to see how this feels. 

> The `CompactCourseDisplay` component will presumably be used on the non-search course index page as well, should the topics still link to search results?

I'm not sure, but I'm going to move this question to the index page issue, #1800 

> Should the availability and platform for each course also link to search results with that facet applied?

Out of scope for this PR -- since we can't make the "Free" label a facet, I'd like to hold off on making them all clickable. 

> Should they [course card labels] appear with a different background color if the facet is already selected? And if so, should clicking it unselect the facet? [For example](https://user-images.githubusercontent.com/187676/53586441-2e359300-3b56-11e9-93d1-60a473a0a716.png)

I don't think so. 

@Ferdi let us know if you disagree
