### ISSUE TITLE
Course Search: 11.384 has a corrupted JSON

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1896]
JSONDecodeError: Extra data: line 260 column 2 (char 21982)

https://sentry.io/organizations/mit-office-of-digital-learning/issues/878018771/?project=216201&referrer=github_plugin

```
JSONDecodeError: Extra data: line 260 column 2 (char 21982)
  File "course_catalog/task_helpers.py", line 230, in safe_load_json
    loaded_json = json.loads(json_string)
  File "json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)

PROD/11/11.384/Spring_2018/11-11-384-malaysia-sustainable-cities-practicum-spring-2018/0/3.json has a corrupted JSON
```

**Comment by sesterki** [comment]
This is the currently intended behavior when course_catalog encounters data that json.loads() fails to parse. How should this behavior change?

**Comment by pdpinch** [comment]
Thanks Sean. It looks like we need to fix the JSON file upstream.

**Comment by pdpinch** [comment]
Duplicate of #2129
