### ISSUE TITLE
Course Search: bad file name in CMS.611

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1897]
It looks like there are some extra spaces at the end of "index.html" for CMS.611

https://sentry.io/organizations/mit-office-of-digital-learning/issues/878059812/?project=216201&referrer=github_plugin

```
Could NOT upload index.html  
```

**Comment by sesterki** [comment]
Can I get access to Sentry, or see the full error report? Why do you think the extra spaces in one of the files is causing a failed upload?

**Comment by sesterki** [comment]
From the sentry report it looks like the file in question does not exist. I think the solution is to remove the link to it from the OCW course data in the original JSON.

**Comment by pdpinch** [comment]
I think this is a duplicate of https://github.com/mitodl/open-discussions/issues/2129
