### ISSUE TITLE
Course search: when a course is auditable, don't show the price

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1901]
### Steps to Reproduce

Search results that include MOOCs with verified certificates display the verified price instead of the audit price. This is misleading because the course is available for free. 

### Expected Behavior

For now, display "free" similar to OCW courses. (We may qualify this in some way in the future with a tooltip or similar)

### Screenshot or Screencast

<img width="653" alt="image" src="https://user-images.githubusercontent.com/430126/53853322-fe8ded00-3f92-11e9-9397-a80ad671d99d.png">

**Comment by pdpinch** [comment]
@kyfantaz can you guys take care of the change in business logic?

**Comment by mbertrand** [comment]
@pspinch Currently all the prices are stored for each course, in the database and in the search index. The front end code is what displays the max price.  Could be changed to show minimum or a range of minimum to maximum.

**Comment by mbertrand** [comment]
@pdpinch Currently all the prices are stored for each course, in the database and in the search index. The front end code is what displays the max price.  Could be changed to show minimum or a range of minimum to maximum.

**Comment by pdpinch** [comment]
Oh, in that case @kyfantaz never mind. We'll address this in the front-end.
