### ISSUE TITLE
home page: new courses "widget"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1902]
As a user, I'd like to see a short list of new courses on the home page

#### Designs and Mockups

tbd

#### Acceptance Criteria:

- [ ] not part of the widget framework; always visible on the home page
- [x] use the [course-catalog/new API endpoint](https://github.com/mitodl/open-discussions/blob/master/course_catalog/views.py#L67-L74)

#### Testing

- We haven't used this API yet and we may need to adjust the query after we see it in action

**Comment by aliceriot** [comment]
@pdpinch is there a basic mockup of what information this should have about the courses?

super basic initial version:

![supebraisdfasdfff](https://user-images.githubusercontent.com/6207644/54376005-79709b00-4658-11e9-9464-badb8aa0d100.png)

also I'm guessing we want the course titles or something to link somewhere - should that link to the course content externally?

**Comment by pdpinch** [comment]
I don't think the "Available Now" label is doing us much good. Maybe price is a better field to use, if we must have something there -- although everything in the catalog should say "free" for now because everything is auditable. 

Can we use the "offsite link" icon to link to the marketing URL? I think we use that elsewhere like the related content widget and links to source pages on the post detail page. 

I don't think we want such a long list. Maybe 4 or 5 courses.

**Comment by Ferdi** [comment]
@aliceriot and I talked a bit . Suggested to use one of our earlier designs 
![off](https://user-images.githubusercontent.com/125561/54388537-4a682280-4674-11e9-8d9d-b19eba136271.png)

without "enroll now" maybe.  Offsite link sounds good.  I think a longer list of courses is fine since currently we dont have much else there.

**Comment by aliceriot** [comment]
![fjffjfjvzxcvn](https://user-images.githubusercontent.com/6207644/54458718-0c820180-473b-11e9-8e94-13256be88e63.png)

how's this look?

**Comment by pdpinch** [comment]
Is that using the existing grid, with one column for the thumbnail and two for the text?

It would be nice to see the thumbnail and the text aligned somehow -- I guess having the top of each aligned would be good, but I'm not sure. 

What's clickable? 

I still don't see the value of "Available Now" "Upcoming" in this case.

**Comment by aliceriot** [comment]
the title, availability info, and platform info are a link to the external location of the course. It's not using the grid because it's living inside of a card, I basically just have a defined width for the photos and then the rest of the info fills in the rest of the space.

I can take off the availability info if we don't want it, I just included it because it was in the mockup above

**Comment by Ferdi** [comment]
What courses are actually displayed in the list ?   whats the order?
I think there should be a better title , like "Learn at MIT". In that case course availability would be good.   The idea of this widget is to serve as an connection between discussion and courses.   So maybe a "more" link at the end that links to /courses would be great. 

*unrelated* What options do we have to make the right column wider . Not just here, but in every page in discussion. It's too narrow imo.

**Comment by aliceriot** [comment]
for the columns we can make them whatever width we want. we basically have a grid in the center of the screen with margins on the left and right, we can reduce the size of those margins and increase the overall width of the grid however we want.

For the courses, it's the result of the `new` courses API endpoint. Looking at the code it looks like it just grabs the ten most recently created courses in the DB

**Comment by Ferdi** [comment]
great, we can talk about width later

> grabs the ten most recently created courses in the DB

it's not ideal.  Some sort of combination between "Upcoming" and "new"  would be better. @pdpinch what do you think ?

**Comment by pdpinch** [comment]
Hm. How about 1/2 upcoming, sorted by the courses starting soonest and 1/2 new sorted by most recently added to the db?

**Comment by aliceriot** [comment]
sure, we have both of those API's already so that's not too difficult

**Comment by aliceriot** [comment]
should there be a title or similar in between those two sections?

**Comment by aliceriot** [comment]
ok here's an updated version:

![mfmfmfmasdf](https://user-images.githubusercontent.com/6207644/54537398-c9a57100-4968-11e9-91a7-93e82578e303.png)

for the list of courses it's pulling 5 courses from the 'new' list and 5 from the 'upcoming' list and mooshing them together.
