### ISSUE TITLE
course search page responsiveness needs improvement

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#1923]
### Steps to Reproduce

Just typing in a search term often leads to perceptible lag in the interface, because the search is updated and the UI is re-rendered on every keystroke. To me it's a noticeable lag locally (in development) and also on the RC environment.

### Expected Behavior

I think that we should debounce the search updates so that we only fire off the request and re-render when the user pauses for a second in typing (like a 250ms debounce would probably do it).

**Comment by Ferdi** [comment]
I think in this case we should keep it simple and do search only onenter or button click.  @mbertrand
