### ISSUE TITLE
Can't embed Twitter feed in embed widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1931]
### Steps to Reproduce

1. Add an embed widget
2. embed a twitter feed URL, such as https://twitter.com/mitopenlearning/

### Expected Behavior

I was expecting some basic embed, like the feed avatar and a link to twitter.

### Actual Behavior

Nothing is displayed, probably because the embedy API doesn't return any text. 

### Screenshot or Screencast

(Optional)

**Comment by aliceriot** [comment]
I tried this locally, and got an exception in the console with this link in it: https://twittercommunity.com/t/deprecating-widget-settings/102295

**Comment by aliceriot** [comment]
so it seems like it's an issue with the way that embedly Cards created the embed for this type of link

**Comment by Ferdi** [comment]
Any idea why it seems to be working here ? https://embed.ly/code?url=https%3A%2F%2Ftwitter.com%2Fmitopenlearning%2F

**Comment by aliceriot** [comment]
no idea, I tried that as well but :woman_shrugging:

**Comment by pdpinch** [comment]
Weird. It seems like the trailing slash might make a difference?

https://embed.ly/code?url=https%3A%2F%2Ftwitter.com%2Fthemovemit%2F works for me. 

https://embed.ly/code?url=https%3A%2F%2Ftwitter.com%2Fthemovemit does not.

**Comment by aliceriot** [comment]
oh jeez

**Comment by pdpinch** [comment]
replaced by #1951, in order to handle twitter feeds as expected
