### ISSUE TITLE
Article: anchor the toolbar to the top of the viewport when scrolling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1933]
As a user writing an article, I'd like to have the toolbar stay in the view port as I scroll down. 

When writing long articles, it is very frustrating to have to scroll up to the top of the page to access the toolbar. 

#### Acceptance Criteria:

- [ ] don't let the toolbar scroll off the top of the page

#### Related issues

- #1703 Move toolbar above cover image

**Comment by aliceriot** [comment]
can you describe where you're seeing the problem? currently the toolbar is set up to stay at the top of the screen when the user scrolls down, like this:

![toolbar](https://user-images.githubusercontent.com/6207644/54928686-b0fa0580-4eea-11e9-9bb9-00c902710b41.png)

it's working locally and on RC for me, so if it's not working for you something is broken

**Comment by pdpinch** [comment]
This appears to be old news. Glad it's working now!
