### ISSUE TITLE
Viewing course object in Django admin throws 500 error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1942]
Trying to access /admin/course_catalog/course/4387/change/ and /admin/course_catalog/course/4492/change/ on RC throws a 500. 

I believe this is the related Sentry error: 

OperationalError: cursor "_django_curs_140197480089344_3" does not exist

https://sentry.io/organizations/mit-office-of-digital-learning/issues/966638626/?project=216201&referrer=github_plugin

```
OperationalError: cursor "_django_curs_140197480089344_3" does not exist

  File "django/db/utils.py", line 96, in inner
    return func(*args, **kwargs)

OperationalError: cursor "_django_curs_140197480089344_3" does not exist

  File "django/db/models/sql/compiler.py", line 1466, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "django/db/models/sql/compiler.py", line 1466, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "django/db/utils.py", line 96, in inner
    return func(*args, **kwargs)
  File "django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "django/db/utils.py", line 96, in inner
    return func(*args, **kwargs)

OperationalError: cursor "_django_curs_140197480089344_3" does not exist

(65 additional frame(s) were not displayed)
...
  File "django/forms/widgets.py", line 577, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "django/forms/models.py", line 1139, in __iter__
    for obj in queryset:
  File "django/db/models/query.py", line 332, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "django/db/models/query.py", line 63, in __iter__
    for row in compiler.results_iter(results):
  File "django/db/models/sql/compiler.py", line 1469, in cursor_iter
    cursor.close()

OperationalError: cursor "_django_curs_140197480089344_3" does not exist

```

**Comment by sesterki** [comment]
Can this be reliably replicated, and if so can I have access to the RC Django admin?

**Comment by sesterki** [comment]
Possibly caused by https://sentry.io/organizations/mit-office-of-digital-learning/issues/363023427/?project=216201&query=is%3Aunresolved

This is a weird bug. I never see a 500 on the RC Django admin. I can sort of reliably make the error occur by refreshing the page a bunch of times. My guess is it has something to do with a bunch of simultaneous queries hitting the same thing?

I remember seeing the OSError on another project in the same circumstances (refreshing the page etc). We never figured out what was happening but it also didn't seem to be breaking anything.

**Comment by pdpinch** [comment]
/admin/course_catalog/course/4387 is working now and it looks like admin/course_catalog/course/4492 was deleted (possibly because it didn't have valid data?)

I'm closing this.
