### ISSUE TITLE
API for moderator to remove post / submission

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#195]
As a moderator, I need to be able to remove posts / submissions that don't mean the channel guidelines. 

[PRAW docs](http://praw.readthedocs.io/en/latest/code_overview/other/submissionmoderation.html?highlight=remove#praw.models.reddit.submission.SubmissionModeration.remove)

**Comment by pdpinch** [comment]
@rhysyngsun Let me know if this needs to be split into multiple issues:

1. add an API for removing posts 
2. update channel API to retrieve deleted posts
3. update posts API to appropriately display deleted posts

**Comment by rhysyngsun** [comment]
@pdpinch yes, please split those into separate issues because #2 and #3 don't seem related to this (nor would I have known to do them based on the limited description).

**Comment by pdpinch** [comment]
I updated the title and description to limit this issue to moderators removing posts. I'm not sure yet if this requires changes to the `channel` API.
