### ISSUE TITLE
Support custom HTML embed code in embed widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1951]
As a channel moderator, I'd like to be able to use custom embed code in the embed widget, instead of relying on embedly's service. 

In particular, I'd like to be able to create a custom Twitter embed using code generated by https://publish.twitter.com/

#### Designs and Mockups

- [wireframe for updated default embed form](https://user-images.githubusercontent.com/430126/56174403-52431b80-5fc0-11e9-83c1-ad449fdf5c56.png)
- [wireframe for form with custom form expanded](https://user-images.githubusercontent.com/430126/56174419-6c7cf980-5fc0-11e9-8062-34b8e171546e.png)

#### Acceptance Criteria:

- [x] add instructions for existing "Url" field
- [x] add instructions "for more specific embeds" 
- [ ] clicking "below" link reveals an additional form feed for custom 
- [x] validate embed code for whitelisted sites before posting to back end, i.e. Twitter and Instragram
- [ ] "contact us" link opens an email to the support address

**Comment by aliceriot** [comment]
on the mockup it says instragram as well - is that something we want to support? one issue is that the instagram embeds created their own cards, which doesn't play so well with our ui:

![fjfjfjfjfjfvvvczxcv](https://user-images.githubusercontent.com/6207644/57160754-b5ea8880-6db7-11e9-8562-960ce0253490.png)

twitter is working well though:

![twittttterrrr](https://user-images.githubusercontent.com/6207644/57160826-ec280800-6db7-11e9-9976-d1cc703471b7.png)

**Comment by Ferdi** [comment]
ok, we can ignore Instagram for now but this reminds me again that we definitely should see if we can increase the width of the right sidebar.
