### ISSUE TITLE
stop raising validation errors to Sentry

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1954]
If we are handling the validation error properly in the UI and the user can correct their mistake, there's no reason to raise it to sentry. 

ValidationError: {'email': [ErrorDetail(string='email does not exist', code='invalid')]}

https://sentry.io/organizations/mit-office-of-digital-learning/issues/911977526/?project=216201&referrer=github_plugin

```
ValidationError: {'email': [ErrorDetail(string='email does not exist', code='invalid')]}
  File "rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/generics.py", line 244, in post
    return self.create(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "rest_framework/serializers.py", line 244, in is_valid
    raise ValidationError(self.errors)

ValidationError: {'email': [ErrorDetail(string='email does not exist', code='invalid')]}
```

**Comment by rhysyngsun** [comment]
A `git revert` of this commit should do the trick: https://github.com/mitodl/open-discussions/pull/1823/commits/ff7df1f737ad58af493ef70ddb812553c0b2a3b8
