### ISSUE TITLE
Courses: handle retired OCW courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1969]
The current courses index page includes a featured course http://ocw.mit.edu/courses/science-technology-and-society/sts-010-neuroscience-and-society-fall-2008 but this courses on the OCW has been retired (and replaced with https://ocw.mit.edu/courses/science-technology-and-society/sts-010-neuroscience-and-society-spring-2010/)

**Comment by sesterki** [comment]
My understanding is that the feature flag is set manually by a open-discussions admin. It sounds like the fix here should be changing this through the Admin panel. Do you think this should be a code change?

**Comment by pdpinch** [comment]
@sesterki Sorry for being vague. I think retired courses need to be removed from the database and the search index. I think this would incidentally remove them from the featured courses listing as well.

**Comment by kyfantaz** [comment]
@pdpinch  Do we have a method by which we determine retired OCW courses? (for example, pinging the main course page and getting a 404). And if not, should we be maintaining a list of known retired courses in the codebase (if the course set is small and non-growing)?

**Comment by pdpinch** [comment]
replaced by #2125
