### ISSUE TITLE
New users aren't getting subscribed to default channels

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1974]
### Steps to Reproduce

1. As an anonymous user, visit the home page with default public channels enabled (e.g. on RC or production). Note that public channels are visible. 
2. Create a new account and login

### Expected Behavior

Default channels should still be visible in side nav after logging in, and public posts should display on the home page. 

### Actual Behavior

No channels and posts appear on the home page. If the user navigates directly to a public channel, they can view posts. Clicking the follow button adds the channel to the front page nav and posts.

**Comment by aliceriot** [comment]
related: https://github.com/mitodl/open-discussions/issues/1965
