### ISSUE TITLE
Course Search: add professional ed metadata to courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1979]
As a course search user, I'd like to know which courses are part of a professional education program. 

When importing courses from edx.org we'll use a json look-up document to determine which, if any, professional ed program they belong to. 

When importing courses from edx.org we need to add Prof. Ed Program information 

#### Acceptance Criteria:

- [x] augment the course metadata for any courses that are in a professional ed program
- [x] set program_type = "Professional"
- [x] set program_name = the name of the relevant program

#### Questions

- **Q:** should we include a links to the professional education program page?

**Comment by pdpinch** [comment]
@sesterki does #1993 close this?

**Comment by sesterki** [comment]
Yes
