### ISSUE TITLE
Course Search: add MicroMasters metadata to courses

### ISSUE THREAD

**Issue by sesterki** [mitodl/open-discussions#1981]
As a course search user, I'd like to know which courses are part of a MicroMasters program.

When importing courses from edx.org we'll pull a list of MicroMasters course keys and programs from the MicroMasters API to determine which, if any, MicroMasters program they belong to.

When importing courses from edx.org we need to add MicroMasters information

#### Acceptance Criteria:
- [x] augment the course metadata for any courses that are in a MicroMasters program
- [x] set program_type = "MicroMasters"
- [x] set program_name = the name of the relevant program

**Comment by pdpinch** [comment]
@sesterki what's left to do here now that #1993 is merged?

**Comment by sesterki** [comment]
There is no work left to do on this issue so I will close it.
