### ISSUE TITLE
Update course Home Page design

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1997]
#### acceptance criteria

- [x] InVision mock-up for review

**Comment by aliceriot** [comment]
@abdulkdawson how's this look for the top bar logo?

![tobar](https://user-images.githubusercontent.com/6207644/59287625-06b79180-8c40-11e9-8b57-e3294d972572.png)

**Comment by abdulkdawson** [comment]
@aliceriot Looks good to me.

**Comment by pdpinch** [comment]
@aliceriot can you give me an idea of what remains on this issue? It looks like you are still making commits related to it?

**Comment by aliceriot** [comment]
yeah, for the home page I think right now what remains is

- restyling the cards in the carousel
- fiddling with the stuff in the banner image (the search box and so on)

I should have a PR for the card restyle tomorrow, then I'll work on the search box stuff

**Comment by pdpinch** [comment]
@aliceriot do you think we can close this now? 

I plan to open a new issue for the card restyling which is coming soon.

**Comment by aliceriot** [comment]
I think we have separate issues for pretty much everything, so we should be good to close it
