### ISSUE TITLE
add spacer for headers when drawer is minimized

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1998]
### Steps to Reproduce

1. Minimize the navigation drawer by, for example, clicking the menu icon

### Expected Behavior

Menu collapses, showing the icon for each channel in the same vertical location the full title was. 

### Actual Behavior

"Channel" and "Channels you Moderate" disappear, shifting channel icons up, making them jump up when the drawer is minimized. 

### Screenshot or Screencast

Do we need a screencast?

**Comment by aliceriot** [comment]
what do we want to show in the place of the title headers? the reason I left them out was that I just wasn't sure what we wanted - we can do an icon, just blank space, anything.

**Comment by aliceriot** [comment]
for now I went with a blank spacer that takes up the same height as the titles:

![closesfodpff](https://user-images.githubusercontent.com/6207644/57145858-136bde80-6d92-11e9-9510-eeecebb08446.png)
![closes](https://user-images.githubusercontent.com/6207644/57145859-136bde80-6d92-11e9-8eb8-1e3636487394.png)
