### ISSUE TITLE
UI for users who are not logged in

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#200]
We should redirect anonymous users to micromasters to login, or at least show a message saying they need to log in to see content. Currently it just looks like an empty set of posts

**Comment by pdpinch** [comment]
Is this the same as #211 ?

**Comment by noisecapella** [comment]
No, this is for users who never logged in

**Comment by roberthouse54** [comment]
OK, let's go with a simple UI like this:

![image](https://user-images.githubusercontent.com/20047260/31031189-fe2b86f0-a525-11e7-9ade-d53c33b93ecc.png)

MIT Open Discussions is a forum for MIT students and global learners. 
To use this site you need to log in with a MicroMasters account.

![discussion_icon](https://user-images.githubusercontent.com/20047260/31031245-1c6125b2-a526-11e7-8bdc-c712c0e18d31.png)

**Comment by noisecapella** [comment]
Sounds good
