### ISSUE TITLE
Channel nav is missing from post detail page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2005]
Compare the detail page to the channel listing page

<img width="45%" align="left" alt="post detail page" src="https://user-images.githubusercontent.com/430126/57374549-294e1a80-7169-11e9-8722-366ce0cb87dc.png">

<img width="45%" alt="channel listing screenshot" src="https://user-images.githubusercontent.com/430126/57374587-38cd6380-7169-11e9-9c98-ae7d9553784c.png">

### Expected Behavior

Both templates should have the channel nav

**Comment by aliceriot** [comment]
related question: currently we also do not render the channel nav on the channel search page - should we add it there as well?

**Comment by aliceriot** [comment]
oops, sorry disregard that last comment! haha
