### ISSUE TITLE
Open Discussions Column width resizing.

### ISSUE THREAD

**Issue by abdulkdawson** [mitodl/open-discussions#2022]
We are looking to have discussion left and right columns resized as well as the content container itself. 

The container should be reduced to 1100px from 1440px. 
The left column should be reduced to a 632px width.
The Right should be reduced to a 350px width.

[https://discussions-rc.odl.mit.edu/](https://discussions-rc.odl.mit.edu/)

**Comment by aliceriot** [comment]
the width of the two columns isn't set as a fixed pixel width but as a fraction of twelve columns - the whole thing is 12 columns. Currently the left column is 7 columns wide and the right column is 5 - do we want to keep those proportions? Before https://github.com/mitodl/open-discussions/pull/2019 we had 8 columns on the left and 4 on the right.

**Comment by aliceriot** [comment]
ah, so the thing was that before we had 8/4 but a max-width on the grid of 960px!

**Comment by aliceriot** [comment]
@ferdi @abdulkdawson here's what it looks like with 1100px max-width on the grid and 8/4 columns:

![asdfffnno](https://user-images.githubusercontent.com/6207644/58891566-baf26e80-86ba-11e9-8f1f-ffce51cd39bf.png)
