### ISSUE TITLE
update profile layout to match designs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2026]
<img width="300" align="left" alt="image" src="https://user-images.githubusercontent.com/430126/58434230-a09c0d80-8088-11e9-81a1-77d242a0d703.png"><img width="300" alt="image" src="https://user-images.githubusercontent.com/430126/58434392-6bdc8600-8089-11e9-9c2d-d93090b5706e.png">

#### acceptance criteria 
- [x] update name styling: `color: #03152D; font-size: 24px; font-weight: bold;`
- [x] reduce white space between avatar and name
- [x] make headline font color grey 
- [x] move location below headline
- [x] move edit button onto card

**Comment by aliceriot** [comment]
I just realized we don't have a place on the profile edit form for the user to set their location - should we have one?

**Comment by aliceriot** [comment]
updated (pretend the profile image is there haha):

![updatedddddd](https://user-images.githubusercontent.com/6207644/58816391-7225b180-85f7-11e9-9d8b-576bf7a5b7dc.png)
