### ISSUE TITLE
"Join MIT Open" pop-ups displays in the wrong place

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2046]
### Steps to Reproduce

1. Log out
2. Navigate to the home page
3. Click on an upvote button

### Expected Behavior

"Join MIT Open" pop-up appears below the upvote button so that the arrow at the top left of the pop-up points at the upvote button. 

### Actual Behavior

(Optional)
<img width="374" alt="image" src="https://user-images.githubusercontent.com/430126/59072075-33aa2400-888f-11e9-85f3-91bfed309938.png">

**Comment by aliceriot** [comment]
this is related to #1299, should be able to address it when we address that
