### ISSUE TITLE
update logo and name on prod 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2051]
#### Summary

Describe where/how to generate these new values

- `FEATURE_USE_NEW_BRANDING` - `True` (we are ready to switch the branding in production)

#### Applicable Environments

- [x] Apply configuration to Production

#### future plans

I opened #2052 to remove the feature flag, which we'll work on once we're confident the new branding will stick around.

**Comment by shaidar** [comment]
Added feature flag

**Comment by pdpinch** [comment]
I updated the authenticated sites with the "MIT Open" name.
