### ISSUE TITLE
Error importing MITX course if marketing_url == None in JSON

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2068]
### Steps to Reproduce

Run `course_catalog.tasks.sync_and_upload_edx_data(force_overwrite=True)`

### Expected Behavior

All the MITX courses are imported.

### Actual Behavior

An exception occurs because one of the courses now has `{"marketing_url": None}` in its course run JSON, which will raise an exception in [course_catalog.utils.get_course_url](https://github.com/mitodl/open-discussions/blob/e710b62e1f39d02ec1dc065d745a87be6551b89b/course_catalog/utils.py#L99):
```python
if settings.MITX_BASE_URL in run.get("marketing_url", "")
```

Also there is an unused dupe `get_course_url` in `course_catalog.task_helpers`.

**Comment by pdpinch** [comment]
@mbertrand do you think we can close this now that #2068 has merged?
