### ISSUE TITLE
Channel drop-down doesn't display list of channels

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#207]
Using Firefox. 

### steps to reproduce: 

1. Click "Submit a New Post"
2. Inspect the Channel drop-down

### expected behavior

List is populated with the same channels that appear in the side navigation (the list of channels that I have permission to post to?)

### actual behavior

The list is apparently populated, but no channel titles are visible:

<img width="1280" alt="screenshot 2017-09-28 13 25 50" src="https://user-images.githubusercontent.com/430126/30980897-9551de8e-a450-11e7-8fa6-bc4d4a665ba8.png">

**Comment by aliceriot** [comment]
I can repro this, it's a firefox / chrome difference type issue. Will fix it.
