### ISSUE TITLE
Hide Link type post

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#209]
To focus on the MicroMasters MVP, we'd like to omit the link type post.

<img width="436" alt="screenshot 2017-09-28 14 18 09" src="https://user-images.githubusercontent.com/430126/30983289-003d9efc-a458-11e7-99a6-28819d8ddd21.png">

**Comment by aliceriot** [comment]
It's fully implemented and all the work for it is done, what's the reason for hiding it?

**Comment by pdpinch** [comment]
Not sure yet if we're going to do this. 

The concern is mostly that we want to focus on a smaller set of features as we're starting out.

**Comment by roberthouse54** [comment]
If we decide to do this, we should get rid of the tabs, and use a standard Modal title that says "Submit a New Post"

**Comment by roberthouse54** [comment]
@Ferdi said we can close this and revisit the "Post link" later if need be.
