### ISSUE TITLE
Update frontend code to additionally search for `program` and `pathway` record types

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2101]
As a user searching for learning resources, I'd like to be able filter on programs 

#### Designs and Mockups

See https://invis.io/XRRX2PH5KZM#/367253746_Open_Courses_with_List_Filter_wAnnotations

#### Acceptance Criteria:

- [ ] Add programs filter to Learning Resources facet
- [ ] Add pathways filter to Learning Resources facet

**Comment by mbertrand** [comment]
In the design for programs/learning paths, [a description is shown](https://projects.invisionapp.com/share/XRRX2PH5KZM#/screens/367253745).  The Program/List model does not currently have a description field. Should I add one?

**Comment by mbertrand** [comment]
@pdpinch @ferdi - the current elasticsearch index document mapping for programs and pathways includes title and short description, but none of the items in each list.  Is that okay?  The consequence is that if you search for a particular course title, the results won't include any program or path that the course is a part of, unless it just happens to be included in the program/pathway title or description.

**Comment by pdpinch** [comment]
@mbertrand can this be closed?
