### ISSUE TITLE
Re-authenticate user when token expires

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#211]
Ferdi saw this, but we're not sure the steps to reproduce yet. 

It seems that when you have a stale session and try to upvote, comment or make a post, you get a 401 error. 

Re-authenticating by visiting micromasters/discussions appears to address the issue.

**Comment by noisecapella** [comment]
@rhysyngsun said this should be implemented already

**Comment by pdpinch** [comment]
Looks like this was already fixed. We'll open it again if we see it in the wild.
