### ISSUE TITLE
mitx course catalog import should write to course runs

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2115]
How we write course and course run data needs to be updated the data model changes introduced in #2114 when importing from mitx. We should safely be able to make this change without any feature flag branching because it will actually get us to our desired behavior of having one result per logical course immediately, with the problem that the course run metadata isn't searchable. It may break some facets in the short term, but it shouldn't in theory cause any errors in the application.

We should put values available in the top level course object into `Course` and the values from the `course_runs` list into `CourseRun` with the foreign key to `Course` set.

As part of this, we should have a command that repairs the `Course` table by dropping all MITX `Course` records and kicking off the task to reimport them.

**Comment by mbertrand** [comment]
For EdX some `Course` field values are determined at the course run level, and will/may change from run to run.   These include `instructors`, `prices`, `level`, `availability`, and various date fields.  Should these fields be left blank in the Course object?

**Comment by rhysyngsun** [comment]
Yeah I think that's the best, if the frontend needs to display these in some way in a course-centric UI, it can use the logic in #2124 to decide which one to use

**Comment by mbertrand** [comment]
@pdpinch @ferdi There's some edx courses with no runs, I think these should probably be excluded - they're currently excluded anyway since the original import task treats the edx runs as the courses.  Here's the list if you're interested:
```
MITx+6.00.1-x Introduction to Computer Science and Programming Using Python
MITx+6.00.1x_5 Introduction to Computer Science and Programming Using Python
MITx+6.00.1x_6 Introduction to Computer Science and Programming Using Python
MITx+6.00.2x_5 Introduction to Computational Thinking and Data Science
MITx+6.041x_3 Introduction to Probability - The Science of Uncertainty
MITx+CTL.SC1x_2 Supply Chain Fundamentals
MITx+CTL.SC2x_2 Supply Chain Design
MITx+CTL.SC2x_3 Supply Chain Design
MITx+6.004.2x_2 Computation Structures 2: Computer Architecture
MITx+16.101x_1 Introduction to Aerodynamics
MITx+11.132x_3 Design and Development of Educational Technology
MITx+CTL.SC0x_2 Supply Chain Analytics
MITx+6.041x_4 Introduction to Probability - The Science of Uncertainty
MITx+6.00.1_3x Introduction to Computer Science and Programming Using Python
MITx+6.00.1_4x Introduction to Computer Science and Programming Using Python
MITx+6.00.1x_7 Introduction to Computer Science and Programming Using Python
MITx+6.00.1x_8 Introduction to Computer Science and Programming Using Python
MITx+6.00.1x_9 Introduction to Computer Science and Programming Using Python
MITx+6.00.2_2x Introduction to Computational Thinking and Data Science
MITx+6.00.2x_3 Introduction to Computational Thinking and Data Science
MITx+6.00.1x_11 Introduction to Computer Science and Programming Using Python
MITx+6.00.2x_7 Introduction to Computational Thinking and Data Science
MITx+ENX_1 Entrepreneurial Negotiations: The MIT Way
MITx+6.00.2x_4 Introduction to Computational Thinking and Data Science
MITx+ESD.SCM1x Supply Chain and Logistics Fundamentals
MITx+6.004.1x_3 Computation Structures 1: Digital Circuits
MITx+6.004.3x_2 Computation Structures 3: Computer Organization
```

**Comment by mbertrand** [comment]
The following are always null for MITx courses (the info is contained within the course runs) so I plan to remove them from the MITx course serializer's `to_internal_value` method :
```
start_date
end_date
enrollment_start
enrollment_end
availability
year
language
instructors
prices
```
