### ISSUE TITLE
Clicking the comment upvote button highlights the submit button 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#212]
See https://share.vidyard.com/watch/fkpH6VAgbMrbnjPFzN28KT

**Comment by pdpinch** [comment]
@aliceriot can you take a look into this?

**Comment by aliceriot** [comment]
it's disabled because we have no way (currently) to tell whether the `PATCH` operation in progress for a `Post` object was initiated to upvote a comment or to make a comment. We could try to add some state to keep track of which one it is.
