### ISSUE TITLE
Index UserList objects to Elasticsearch when created/updated

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2120]
`UserList` objects should be added to the ElasticSearch index whenever they are created or modified (and removed if deleted).

#### Designs and Mockups
Add a post-save signal to `UserList` that triggers a celery task to add/modify that UserList in the Elasticsearch index.
Add a post-delete signal to `UserList` that triggers a celery task to remove that UserList from the Elasticsearch index.

**Comment by mbertrand** [comment]
@pdpinch maybe the same applies to Programs too?  Not sure if the plan is to import them from an external file like bootcamps or create them manually via django admin.

**Comment by pdpinch** [comment]
@mbertrand I think you took care of this some time ago. Can we close this issue?
