### ISSUE TITLE
Update Availability facet to work with revised search index structures

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2123]
In #2116 the `Course`s from MITX are being indexed with the nested `CourseRun` data having the actual values this facet needs to filter on for the Availability facet.

ES Documentation on nested documents and search: https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html

Also as part of this, we discussed that we probably need different options in this facet than are currently present (we decided we're not going to allow searching for courses only in the past):

- **Current** - defined as:
  - A course with a run with an `enrollment_start` in the past and `enrollment_end` in the future
  - A course with all runs having `enrollment_start` and `enrollment_end` in the past
- ** Future** - defined as:
  - A course with any runs with an `enrollment_start` in the future
- ??

Screenshot of new design:
https://projects.invisionapp.com/d/main#/console/17477251/377721258/preview

**Comment by mbertrand** [comment]
- Availability will no longer be determined by a single field value, but by comparing the current date to `enrollment_start` and `enrollment_end` dates.  Since the mitx course import task runs on a daily basis, maybe the `availability` field can be updated based on enrollment dates if necessary as part of this task, and the index updated accordingly?

- For EdX courses the availability will be in the course run info, for OCW courses and Bootcamps it will be in the course info.  How do we make this seamless so that filtering by "Available Now" will return both OCW courses and the MITX courses that have 'Available Now' runs, with the correct number of counts shown in the facet category?  Maybe OCW courses and bootcamps should also be indexed with a single virtual course run?

**Comment by mbertrand** [comment]
Example of how to aggregate by course_run:
```
        "course_runs": {
        	"nested": {
        		"path": "course_runs"
        	},
        	"aggs": {
		        "availability": {
		            "terms": {
		                "field": "course_runs.availability",
		                "size": 10000
		            }
		        }        		
        	}
        },
```

**Comment by mbertrand** [comment]
Date range aggregation might be useful for redefining availability: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html

**Comment by Ferdi** [comment]
@mbertrand, I thought we were adding runs for ocw

**Comment by mbertrand** [comment]
@Ferdi @pdpinch @rhysyngsun some course runs have a start_date and no enrollment_start date or vice versa.  So I'm thinking of adding some calculated fields to the ElasticSearch documents: 'earliest_start' and 'earliest_end' to base the availability on:

`earliest_start`: equal to `enrollment_start` if not None or `start_date` if not None or a rough date based on semester and year if not None
`earliest_end`: equal to `enrollment_end` if not None or `end_date` if not None or a rough date based on semester and year if not None

**Comment by pdpinch** [comment]
Are these courses coming from edX? Can you give some examples?

**Comment by mbertrand** [comment]
Yes, from edX.

A course having at least 1 run with `start_date` but no `enrollment_start`: https://discussions-rc.odl.mit.edu/api/v0/courses/4919/

A course with null `start_date` and null `enroll_start` but having `semester` and `year`: https://discussions-rc.odl.mit.edu/api/v0/courses/5195/

**Comment by mbertrand** [comment]
@pdpinch @Ferdi Another minor(?) issue with faceting by course run availability is that the facet counts will be based on number of runs, and therefore greater than the number of courses.  For example, in my database for a general search on MITx courses, I get back a facet count of 95 courses, but the facet counts for availability are:

Available Now: 318
In the next 30 days: 5
In the next 60 days: 19
In the next 90 days: 9
Beyond 90 days: 52

**Comment by rhysyngsun** [comment]
@mbertrand you need to use a reverse nested aggregation to make that work the way we want: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-reverse-nested-aggregation.html

**Comment by mbertrand** [comment]
Thanks Nathan, got it working:
```javascript
"availability": {
  "doc_count": 393,
  "runs": {
    "buckets": {
      "Available Now": {
        "to": 1565973776427.0,
        "to_as_string": "2019-08-16T16:42:56.427Z",
        "doc_count": 309,
        "courses": {
          "doc_count": 88
        }
      },
      "In the next 30 days": {
        "from": 1565973776427.0,
        "from_as_string": "2019-08-16T16:42:56.427Z",
        "to": 1567296000000.0,
        "to_as_string": "2019-09-01T00:00:00.000Z",
        "doc_count": 5,
        "courses": {
          "doc_count": 5
        }
      },
      "In the next 60 days": {.....
```
