### ISSUE TITLE
Update course drawer and search results to use an appropriate course run

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2124]
The changes in #2115, #2116, and #2122 mean that the data used by the drawer has moved into a nested `course_run` list. This means for MITX courses we need to pick an appropriate `CourseRun` out of this list to open the drawer for. 

The appropriate `CourseRun` differs depending on the user's current search criteria on the Availability facet (note the changes to the Availability facet in #2123):

- **No filter** the first `CourseRun` found in this priority order:
  - The current course run (as defined below)
  - The first future course run (as defined below)
  - The most recent past course run
- **Current** - the first `CourseRun` found in this priority order:
  - A course run with `enrollment_start` in the past and `enrollment_end` in the future
  - The most recent course run with `enrollment_start` and `enrollment_end` in the past
- ** Future**
  - The course run with the lowest `enrollment_start` set in the future

We should open the drawer with that course run displayed.

We also want a dropdown to switch between the other course runs on the course.

**Comment by mbertrand** [comment]
@abdulkdawson is there a design for this that includes a dropdown for selecting an alternate run?

**Comment by abdulkdawson** [comment]
@mbertrand Yes it is being tweaked as we speak.

**Comment by mbertrand** [comment]
[In the design](https://projects.invisionapp.com/d/main#/console/17477251/382578136/preview), semester and year are shown in the course run dropdown.  What should the alternative be for runs that have neither course nor year?  There are about 12 of them, and 6 of those are also lacking any start/enrollment date.  Show the start date if available (or convert it to a semester/year), and if start date is also missing show the course run id instead?

```
'course-v1:MITx+6.002x+2013',
 'course-v1:MITx+6.002x+MITx_2012_Alumni',
 'course-v1:MITx+CTL.CFx+2T17U8',
 'course-v1:MITx+CTL.CFx+1T18MU',
 'course-v1:MITx+CTL.CFx+1T18U1',
 'course-v1:MITx+CTL.CFx+1T18U5',
 'course-v1:MITx+CTL.CFx+1T18U8',
 'course-v1:MITx+HR3+2017_Q3',
 'course-v1:MITx+CTL.CFx+2T17MU',
 'course-v1:MITx+CTL.CFx+2T17U1',
 'course-v1:MITx_PRO+ENx+InternalOnly',
 'course-v1:MITx+CTL.CFx+2T17U5'
```

**Comment by mbertrand** [comment]
edx, xpro - use start date if available, else best available date
ocw - semester/year
bootcamp - don't show?

**Comment by Ferdi** [comment]
Can we do start date for bootcamps (not as a dropdown) ?

**Comment by mbertrand** [comment]
@ferdi 'Start date' is already shown as a different field:

<img width="503" alt="Screen Shot 2019-09-09 at 11 50 25 AM" src="https://user-images.githubusercontent.com/187676/64616995-9853ae00-d3ab-11e9-84c4-703841c169e5.png">

**Comment by Ferdi** [comment]
ok, but still for consistency we should have it on top as well @abdulkdawson
