### ISSUE TITLE
OCW courses that are deleted should be viewable directly, but not searchable

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2125]
We need to be able to reflect the fact that some OCW courses are deleted, but support the fact that these courses may show up in lists and we don't want to break those.

This means:

- [ ] Don't delete OCW courses from the `Course` table so that it is still available via the `/api/v0/course/:ID:/` API
- [ ] Instead we should flag the course in such a way that we don't index it (maybe set `published = False`? this probably requires some investigation into how OCW reflects a course deletion)
- [ ] Kick off a task to remove it from the index

**Comment by pdpinch** [comment]
For example, search on https://discussions-rc.odl.mit.edu/courses/search?q=Linear%20Algebra and click on 18.06 (currently 3rd from the top). 

There are 3 course runs. The oldest one (2002) links to a 404 page on OCW. Undoubtedly it has been unpublished. The 2nd oldest one (2005) has a working link, but it is redirected by the OCW server to the 2010 version. It has been archived and/or unpublished as well. Neither of these runs should be in our index.

**Comment by noisecapella** [comment]
I'm going to double check with other people tomorrow but from reading the code and stepping through, I think all the logic to determine if a course is unpublished or not is already there and I think it stores the result in the `published` field already? If so I think this could be as simple as rerunning `./manage.py backpopulate_ocw_data --force`. But I want to double check that this wouldn't harm anything before trying it out.

**Comment by rhysyngsun** [comment]
@noisecapella I think one change is necessary here: https://github.com/mitodl/open-discussions/blob/master/course_catalog/api.py#L161

Specifically, `upsert_course` should only be called if the course is published, otherwise `delete_course` helper should be called to evict the record from ES. See the newer version of the same code: https://github.com/mitodl/open-discussions/blob/master/course_catalog/etl/loaders.py#L96-L99

**Comment by rhysyngsun** [comment]
^ we might only need a simple reindex once that's fixed, but you'd need to verify

**Comment by noisecapella** [comment]
I don't think a simple reindex will work here since the logic change is in the `digest_ocw_course` function which looks like it's only called in the `backpopulate_ocw_data` management command, and the user would need to use the force overwrite option to get to that point in the code.
