### ISSUE TITLE
Highlight the active channel in the side nav

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#214]
The current channel should be highlighted in the left sidenav. The link should be clickable when the user is on the Post Details page, but not clickable when the user is on the channel page.

![image](https://user-images.githubusercontent.com/20047260/31091601-93d57c10-a779-11e7-8008-f0c34d4a7dcb.png)

**Comment by pdpinch** [comment]
@aliceriot can you implement this?

**Comment by aliceriot** [comment]
sure
