### ISSUE TITLE
Display a default course image if a course doesn't have one of its own

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2141]
### Steps to Reproduce

Search courses for 'The Human Brain'.  

### Expected Behavior

There should be a default image shown if the imported course doesn't have one of its own.

### Actual Behavior

One of the results will have a broken image link.

### Screenshot or Screencast

<img width="244" alt="Screen Shot 2019-08-07 at 9 37 05 AM" src="https://user-images.githubusercontent.com/187676/62627269-17f6e480-b8f7-11e9-9941-7160b116f0e9.png">

**Comment by mbertrand** [comment]
@pdpinch @Ferdi is a blank image okay or do you want something generic like a platform logo?

**Comment by abdulkdawson** [comment]
Here is a default image to use when there is no image available. 
![Default_Course_Image](https://user-images.githubusercontent.com/49685474/64887225-2642c980-d636-11e9-8744-26a40ed9a015.jpg)

**Comment by pdpinch** [comment]
Works for me.

**Comment by abdulkdawson** [comment]
@mbertrand 
![Default_Course_Image](https://user-images.githubusercontent.com/49685474/64966743-588a3c00-d86d-11e9-9672-c232c48d7f4d.jpg)
