### ISSUE TITLE
Deleting a LearningResource (course, bootcamp) etc doesn't delete favorites for that resource

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2145]
### Steps to Reproduce

Favorite a `Course`.  Delete that `Course`.  The course is gone but the `FavoriteItem` remains.

### Expected Behavior
`FavoriteItem` objects for deleted items should get deleted too.

### Actual Behavior
`FavoriteItem` objects for deleted items do not get deleted.

**Comment by rhysyngsun** [comment]
Closed in favor of #2125
