### ISSUE TITLE
Update course drawer to open for programs

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2152]
When clicking on a search result card for a `Program`, the course drawer should open and show the contents of that program/list.

#### Designs and Mockups

Program:
https://projects.invisionapp.com/d/main#/console/17477251/376322443/preview

**Comment by mbertrand** [comment]
@pdpinch the [design for the Program drawer](https://projects.invisionapp.com/d/main#/console/17477251/376322443/preview) has many fields that still do not exist for the Program model, should they? - length, effort, language, video transcript, instructors.  Nathan is working on adding price.  I think the topics list will always be empty for programs at the moment.  If necessary I could query for all the instructors and topics from all the program's course runs to display on the fly, instead of storing them as part of the Program model.

**Comment by mbertrand** [comment]
@pdpinch I talked with @rhysyngsun about above, the info for the missing fields does not exist, except instructors, which should be imported assuming the CMS is populated correctly.  So the program drawer should include the following fields: title, short description, offered by, instructors, # courses, cost.

**Comment by mbertrand** [comment]
@pdpinch mind if I split out the learning paths into a new issue?

**Comment by pdpinch** [comment]
Yeah, that would be fine. The design for learning paths iis still in progress.
