### ISSUE TITLE
Courses should be able to be offered by multiple platforms

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2163]
As a User I'd like to be able to see that a course is offered by multiple platforms (e.g. mitx and micromasters).

#### Designs and Mockups

List view: https://invis.io/XRRX2PH5KZM#/378191756_Open_Courses_list_View_3_test
Grid view: https://invis.io/XRRX2PH5KZM#/377036772_Open_Courses_with_List_FilterV2

#### Acceptance Criteria:

- [x] Data schema is updated and migrated to reflect this
- [x] Search indexing is updated to support this
- [x] Frontend is updated to support this in search and the drawer

#### Out of Scope

- Not going to do

**Comment by pdpinch** [comment]
In the designs for this, we've decided to go with just text. The only combination of "offered by" brands that we expect in production is `["MicroMasters","MITx"]` which should always be rendered at "MITx MicroMasters" 

I will update the description with links to InVision
