### ISSUE TITLE
Back to site link

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#219]
As a MicroMasters user, I'd like to have a "back to MicroMasters" link in the side nav. 

Ideally, this link would be back to whatever site the user arrived from, possibly leveraging the jwt cookie. But for now, we only have one integration, with MicroMasters, so a simpler solution is OK.

**Comment by roberthouse54** [comment]
Clicking this link will go back to the Micromasters portal. I think it is fine if this just goes to the dashboard page, without opening a new tab.

![image](https://user-images.githubusercontent.com/20047260/31094080-da796232-a781-11e7-8823-810eb1650930.png)

**Comment by pdpinch** [comment]
We implemented the link in the breadcrumbs, which is enough for now.
