### ISSUE TITLE
Bug: can't change vote on your own post or comment

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#220]
When a user create a post or comment, they automatically upvote it. 

After that, removing the upvote or changing it to a downvote doesn't seem to change the score. 

This behavior is different from what we have observed on reddit.com

**Comment by noisecapella** [comment]
I'm seeing this behavior on my local reddit instance. Is this issue about figuring out how to configure reddit differently?

**Comment by noisecapella** [comment]
reddit.com appears to have the same behavior to me. When you upvote or downvote your own comment there's an immediate change of score, but when you refresh it goes back to the way it was before
