### ISSUE TITLE
When anonymous user clicks favorite button, ask them to Join MIT Open

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2209]
As an anonymous user, I'd like to get a prompt to join when I try to click on a Favorite button

#### Designs and Mockups

Should be similar UX to when an anonymous user clicks on the the vote button:

<img width="346" alt="Untitled" src="https://user-images.githubusercontent.com/430126/64862596-ef9e8c00-d600-11e9-9b4d-abd6c561aaff.png">

I'm not sure if we need to update the text of this pop-up: 

> As a member, you can share your ideas, subscribe, vote, and comment on educational content that matters to you.

#### Acceptance Criteria:

- [ ] Show standard "Join" pop-up when anonymous user clicks on favorite.

**Comment by abdulkdawson** [comment]
@mbertrand 
![Default_Course_Image](https://user-images.githubusercontent.com/49685474/64963775-cd5a7780-d867-11e9-87f5-c931169a8d27.jpg)

**Comment by abdulkdawson** [comment]
@pdpinch 
[https://projects.invisionapp.com/d/main#/console/17477251/384127154/preview](https://projects.invisionapp.com/d/main#/console/17477251/384127154/preview)

![Screen Shot 2019-09-16 at 10 47 15 AM](https://user-images.githubusercontent.com/49685474/64967991-6e98fc00-d86f-11e9-82c2-d513056126be.png)

**Comment by aliceriot** [comment]
we have this existing issue too: https://github.com/mitodl/open-discussions/issues/1299

basically the current approach for rendering these popups isn't very good, so as part of this I'll look to see if there's an easy simpler approach we can use. I had started implementing a different solution a while ago but never finished it.
