### ISSUE TITLE
show spinner when updating score

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#221]
We've noticed that changing a vote can be slow to update. 

As a stopgap measure we can show a spinner while the score is being updated.

**Comment by Ferdi** [comment]
I think we should update ui first and then make the api call

**Comment by pdpinch** [comment]
@loemerdotcom reported this issue again, noting that when the score doesn't update it's tempting to click the button again which results in the voting being removed.

**Comment by aliceriot** [comment]
just to update this, the current state of upvoting / downvoting for comments is that which arrow is selected changes immediately after upvoting *but* the score doesn't change until after the request comes back. wouldn't be terribly hard to fix that so the score changes pre-emptively as well.
