### ISSUE TITLE
Cropping breaks animated GIFs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2210]
### Steps to Reproduce

Compare [this cropped GIF](https://i.embed.ly/1/display/crop/?key=ffaa860a1ed5405994f0ee0e880e36f5&url=https%3A%2F%2Fopen-learning-course-data-rc.s3.amazonaws.com%2F22-06-engineering-of-nuclear-systems-fall-2010%2Fa840f7793ae49c039f8e5bc827b4102e_22-06f10.gif&height=130&width=306&grow=true&errorurl=https://discussions-rc.odl.mit.edu/static/images/blank.png) to [the original](https://ocw.mit.edu/courses/nuclear-engineering/22-06-engineering-of-nuclear-systems-fall-2010/22-06f10.gif)

### Expected Behavior

Ideally, we should just grab one frame of the GIF for the thumbnail. Animated thumbnails are not good.

I'm not sure if this is an option from the embedly image service, or if we have to process the images on import.

**Comment by mbertrand** [comment]
Set `animate=false` in embedly call

https://docs.embed.ly/docs/crop
https://docs.embed.ly/docs/resize
