### ISSUE TITLE
Courses: Display "OCW" instead of "MIT OpenCourseWare" 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2216]
It's redundant to call it "MIT OpenCourseware" since all the courses are from MIT. 

Also, "OCW" is more consistent with the branding on ocw.mit.edu than "OpenCourseware"

#### Acceptance Criteria:

- [ ] update the card display in search results
- [ ] update the card display on the courses home page
- [ ] update the facet display

**Comment by rhysyngsun** [comment]
This was done at some point, so closing
