### ISSUE TITLE
Courses: searching for a course number should return the course

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2220]
As a member of the MIT community (faculty or student), I often know courses best by number. If I search for a course number, I expect it to be displayed in the results, in the top position. 

#### Acceptance Criteria:

- [ ] index the course number, which is stored in `course.course_id` (more or less)
- [ ] Searching for "18.06" should return "Linear Algebra" (https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/)
- [ ] Searching for "6.002x" should return Prof. Anant's "Circuits and Electronics" course
- [ ] The course_id field should be boosted enough so that the course with that number will appear above a course that just mentions the number in its description.

**Comment by mbertrand** [comment]
@pdpinch you can try this on CI now

**Comment by mbertrand** [comment]
@pdpinch the course id for "Circuits and Electronics" is actually "MITx+EECS.6.002x".  So a search for just "6.002x" will put other courses on top of the list that ES thinks is a closer match, such as "2.002" and "MITx+6.00.2x_6".  If course id and course number are not the same, then the model is going to need another field and we'll need a function to accurately parse the course number from the course_id.

**Comment by mbertrand** [comment]
PS There's actually multiple "Circuits and Electronics" courses:
MITx+EECS.6.002x - Prof. Anant Argarwal
MITx+6.002_4x  - Prof. Anant Argarwal
MITx+6.002x - No instructors
