### ISSUE TITLE
Courses: loading loop for course home page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2224]
As a user, I'd like to know that something is happening while I wait for the course home page to load. 

#### Designs and Mockups

tbd

#### Acceptance Criteria:

- [ ] display the loading loop while the various courses are populated

#### Related issue

- #2167 course search loading loop

**Comment by abdulkdawson** [comment]
@pdpinch @aliceriot Here is the loading loop[ mock for the home page. 

[https://projects.invisionapp.com/d/main#/console/17477251/384372969/preview](https://projects.invisionapp.com/d/main#/console/17477251/384372969/previewl)

**Comment by pdpinch** [comment]
Link isn't working for me?

**Comment by abdulkdawson** [comment]
@pdpinch Try this one. [https://projects.invisionapp.com/d/main#/console/17477251/384372969/preview](https://projects.invisionapp.com/d/main#/console/17477251/384372969/preview)
