### ISSUE TITLE
Set ELASTICSEARCH_INDEXING_CHUNK_SIZE to 75

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2234]
#### Summary

Set the following (I already did this manually via heroku website):

- `ELASTICSEARCH_INDEXING_CHUNK_SIZE ` to 75

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

Related to #2187

**Comment by pdpinch** [comment]
@mitodl/devops what's the status of this?

**Comment by shaidar** [comment]
Deployed and closing
