### ISSUE TITLE
Change display of course/program link on Drawer

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2253]
Change the layout of the `ExpandedLearningResourceDisplay` external link from:

<img width="291" alt="Screen Shot 2019-09-27 at 11 25 52 AM" src="https://user-images.githubusercontent.com/187676/65781536-c4945c00-e119-11e9-9f57-58c449c130b4.png">

to:

<img width="570" alt="Screen Shot 2019-09-27 at 11 27 02 AM" src="https://user-images.githubusercontent.com/187676/65781552-ccec9700-e119-11e9-908f-427153c4fd60.png">

Design at https://projects.invisionapp.com/d/main#/console/17477251/376322443/preview

**Comment by mbertrand** [comment]
@pdpinch @ferdi @abdulkdawson will need to know which logos should be used for which source.

**Comment by abdulkdawson** [comment]
@mbertrand can we move the logo closer to the button?

**Comment by mbertrand** [comment]
@abdulkdawson sure, if you update the design I'll take a fresh screenshot of it.

**Comment by abdulkdawson** [comment]
@mbertrand actually now that I look at it this is where we moved it to on our last design updates. So no worries this is fine where it is.

**Comment by aliceriot** [comment]
@abdulkdawson this is what the button currently looks like: 

![ocwbutton](https://user-images.githubusercontent.com/6207644/70453409-b39b8b80-1a76-11ea-929d-a36ee173fa3c.png)

do we need to change it? just not clear based on the discussion above if we still need to do something here or not, haha

**Comment by abdulkdawson** [comment]
@aliceriot We were talking about the logo that is to the right of the button. Although we should change the button color to blue. #126F9A

**Comment by aliceriot** [comment]
Ok so just want to confirm a few things:

- do we only want this for courses and programs? we also show a "take bootcamp" button on bootcamps, so we might want a logo for that too
- courses can be on OCW, MITx, xpros
- programs can xpro, micromasters

also do we have assets that we want to use for all of these things right now? we have this assortment of logos in the repo already:

![ocw-logo](https://user-images.githubusercontent.com/6207644/70641615-e2973600-1c0b-11ea-87be-9bf6246ec5d9.png)
![mitx-logo](https://user-images.githubusercontent.com/6207644/70641617-e2973600-1c0b-11ea-8853-be42548b31b8.png)
![mit-xpro-logo](https://user-images.githubusercontent.com/6207644/70641618-e2973600-1c0b-11ea-8e65-33305fb5f77f.png)
![mit-ocw-logo-square](https://user-images.githubusercontent.com/6207644/70641620-e2973600-1c0b-11ea-848b-ebf177ce6160.png)
![mit-micromasters-logo](https://user-images.githubusercontent.com/6207644/70641621-e2973600-1c0b-11ea-9b12-0088b9b9617f.png)
![mit-bootcamp-logo](https://user-images.githubusercontent.com/6207644/70641622-e2973600-1c0b-11ea-88d0-492a52809a06.png)

**Comment by Ferdi** [comment]
@aliceriot the icon should correspond to the "platform" field. So, one would take mitX courses on edx.Org.

**Comment by aliceriot** [comment]
just realized that for edx.org we don't currently have a logo in the repo, is there a particular one we want to use, or should we just grab one off their site?

**Comment by aliceriot** [comment]
added in the logos:

![bootcampfffxpro](https://user-images.githubusercontent.com/6207644/70727228-50576680-1ccd-11ea-8f77-2e836fc6412e.png)
![bootcampffffffasdf](https://user-images.githubusercontent.com/6207644/70727229-50576680-1ccd-11ea-850f-c0b5913fd0ca.png)
![bootcampfff](https://user-images.githubusercontent.com/6207644/70727230-50576680-1ccd-11ea-84f6-abd3458307bc.png)

**Comment by aliceriot** [comment]
@abdulkdawson working on wrapper this up for #2466, final question I have is do we have a logo asset for edx.org?

**Comment by Ferdi** [comment]
@aliceriot how is this https://micromasters.mit.edu/static/images/edx_logo.png

**Comment by abdulkdawson** [comment]
@aliceriot here is another version of the logo if you need it.
![edx_logo](https://user-images.githubusercontent.com/49685474/70915512-f5cd4b80-1fe7-11ea-9a08-86ccd16a67b2.png)

**Comment by pdpinch** [comment]
When are we displaying an edX logo instead of an MITx logo?

**Comment by aliceriot** [comment]
the courses that say "offered by" MITx have edX as a "platform" value, so we want to show the edX logo so the user knows where they're going to take the course. it's for this UI:

![foaosdfasdfasdf](https://user-images.githubusercontent.com/6207644/70917981-4f377980-1fec-11ea-9c30-878d78dad44e.png)

**Comment by abdulkdawson** [comment]
@aliceriot in this case we want to show the edX logo as this is representative of the platform the course would be taken on. Am I correct @pdpinch ?

**Comment by pdpinch** [comment]
Thanks for the clarification. There's a bit of conflict between UX and branding here, but it makes sense to favor UX and let the user know what web site they will land on when they click the button.
