### ISSUE TITLE
Hide empty fields in detail drawer view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2257]
### Steps to Reproduce

1. go to /courses/search
2. use the "Offered By" facet to filter down to xPRO courses
3. click on a course to view the detail drawer

### Expected Behavior

- any fields that are empty or null are omitted from the detail drawer

### Actual Behavior

- The drawer includes a "Level:" field with a value of "Unspecified"

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/65922387-173c7500-e3b3-11e9-8123-25b39d771108.png)

**Comment by mbertrand** [comment]
Already fixed as part of #2251
