### ISSUE TITLE
Navbar is hidden when viewing a post

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#2274]
### Steps to Reproduce

You can see the issue here: https://discussions-rc.odl.mit.edu/c/everybody/1sw4/using-ml-to-fool-ml

### Expected Behavior

Navbar and post should not overlap

### Actual Behavior

They overlap

### Screenshot or Screencast

![Screenshot from 2019-10-08 14-49-29](https://user-images.githubusercontent.com/863262/66424143-0d31fc00-e9db-11e9-9029-b51813643a18.png)

**Comment by aliceriot** [comment]
I have a pr to fix already, just haven't merged yet: https://github.com/mitodl/open-discussions/pull/2268
