### ISSUE TITLE
Offered By facet is hiding bootcamps behind a "view more"

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2287]
### Steps to Reproduce

See the screenshot, the "view more" link is taking up one line, which could just be the text "Bootcamp" instead since that's also one line

### Expected Behavior
I think we maybe shouldn't truncate the facet values for now since we don't have a huge number of values?

### Screenshot or Screencast
![Screenshot_2019-10-11 MIT Open Learning](https://user-images.githubusercontent.com/28598/66681553-f5f44800-ec40-11e9-8c34-afecae1e4ca5.png)

**Comment by aliceriot** [comment]
I think the only one where we really have a lot of options is the subject area, which can get pretty long:

![subjecccasdf](https://user-images.githubusercontent.com/6207644/66854815-10376a00-ef50-11e9-9d09-8083452de349.png)

so probably we can get rid of the view less / view more behavior everywhere except for the subject area?

**Comment by Ferdi** [comment]
>  so probably we can get rid of the view less / view more behavior everywhere except for the subject area?

Is that the same as something like "if number of items > N  , who the 'view more'  , where N is some reasonable number for our use case (like 10 ?)

**Comment by aliceriot** [comment]
yeah, exactly, here I implemented that behavior where N is 15:

![facetsfffdafsdfasdf](https://user-images.githubusercontent.com/6207644/66856068-6ad1c580-ef52-11e9-8740-4484ab0bfe72.png)
