### ISSUE TITLE
series of tweaks for course search, course home page

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#2294]
from our meeting today:

- [x] remove extra dollar sign from course price (only on the card, not in the drawer)
- [x] values in the card description for platform, topic, etc should be links to a search for that value (e.g. clicking the 'Math' subject on a course should take you to a search for the 'Math' subject')
- [x] only the favorite button in the bottom row of the card should have a 'link' cursor
- [x] cards all over the site should have a hover state, where a box-shadow shows up (see designs)
- [ ] the whole card should be clickable to open the learning resource drawer
- [x] course home page search 'magnifying glass' icon should redirect to search with the text the user has entered (currently this behavior happens when you hit the enter key but not when you click the little icon)
- [x] change home page link text from "View All" to "Explore"

**Comment by aliceriot** [comment]
@pdpinch @Ferdi did I miss anything?

**Comment by pdpinch** [comment]
That was everything on my list, except for changing the favorite icon from https://material.io/resources/icons/?icon=star_border&style=baseline to https://material.io/resources/icons/?icon=bookmark_border&style=baseline  -- but I was going to talk to Abdul about that.

**Comment by aliceriot** [comment]
should we get rid of the dollar sign here too, in the drawer?

![whatdoweanthere](https://user-images.githubusercontent.com/6207644/67027539-bb266000-f0d7-11e9-8407-741f87b8b032.png)

**Comment by Ferdi** [comment]
@aliceriot probably not

**Comment by aliceriot** [comment]
@pdpinch any final decision on that icon?
