### ISSUE TITLE
Show user name and image in UI for Open Discussions

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#230]
Design is TBD

**Comment by pdpinch** [comment]
IIRC, we have a few issues to solve here:

- [ ] need to specify mobile layout
- [ ] need to decide what, if anything, comes under the user  menu
- [ ] Do we need all these words "Logged in as" ?

**Comment by roberthouse54** [comment]
![image_1024](https://user-images.githubusercontent.com/20047260/37047632-883e89b6-2139-11e8-9265-a7beb29b9798.png)

![image_960](https://user-images.githubusercontent.com/20047260/37047633-88490080-2139-11e8-8962-2d4f061a11b8.png)
