### ISSUE TITLE
Create a basic page to view lists/pathways

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2310]
As a user, I'd like to have a page where I can view and edit my lists/pathways.

#### Designs and Mockups
https://projects.invisionapp.com/d/main#/console/18704964/389244472/preview
https://projects.invisionapp.com/d/main#/console/18704964/389406547/preview

#### Acceptance Criteria:

- [ ] User can view lists
- [ ] User can view learning resources in a list

#### Out of Scope
- Different issue: edit lists/pathways
- Different issue: reorder LR's in list

**Comment by abdulkdawson** [comment]
@aliceriot I think that should work.
