### ISSUE TITLE
Create a page to edit lists/pathways

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2311]
As a user, I'd like to edit my lists/pathways

#### Designs and Mockups

https://projects.invisionapp.com/d/main?origin=v7#/console/18704964/389244474/preview
https://projects.invisionapp.com/d/main?origin=v7#/console/18704964/389439354/preview
https://projects.invisionapp.com/d/main?origin=v7#/console/18704964/389406547/preview
https://projects.invisionapp.com/d/main#/console/18704964/389244472/preview

#### Acceptance Criteria:

- [x] Delete lists & pathways
- [x] Delete items from a list/pathway
- [x] Reorder learning resources in pathways

**Comment by aliceriot** [comment]
@pdpinch is there anything else we need to do for this issue?

**Comment by aliceriot** [comment]
If not I think we can close it. Currently from the "detail" page for a list (`/courses/lists/:id`) you can edit the list's permissions, reorder it (if it's a learning path), and change things like the title.
