### ISSUE TITLE
Search: view less / more does not collapse when facet collapsed

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2318]
### Steps to Reproduce

- Collapse the Subject Area facet when there are enough values to cause "show more" to appear
- The "view more" link is still visible

Same applies for "view less"

### Expected Behavior

- "view less/more" links collapse with the rest of the facet content

### Screenshot or Screencast

![Screenshot_2019-10-21 MIT Open Learning](https://user-images.githubusercontent.com/28598/67239433-30b66700-f41d-11e9-830a-b09931c4231f.png)

**Comment by aliceriot** [comment]
gonna fold this into #2315 to avoid merge conflicts
