### ISSUE TITLE
User can Edit their own comment

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#232]
Design [below](https://github.com/mitodl/open-discussions/issues/232#issuecomment-334805536)

If a user has edited a comment, we will show a little text that says [edited by author].

**Comment by roberthouse54** [comment]
We will show an edit link under the comment. This will only be shown to the author of the post. 

![image](https://user-images.githubusercontent.com/20047260/31288277-37fe3bc2-aa92-11e7-8640-e45c5ef6c23d.png)

Editing is done inline. 

![image](https://user-images.githubusercontent.com/20047260/31288285-3f38feae-aa92-11e7-88a3-53cd36988402.png)

After the comment has been edited we will add "[edited by author]" at the end of the text.

![image](https://user-images.githubusercontent.com/20047260/31288307-5a4ebb20-aa92-11e7-8409-d86b91d3044f.png)

**Comment by pdpinch** [comment]
@aliceriot Can this be closed?

**Comment by pdpinch** [comment]
Need to add flag to indicate that the comment has been edited.
