### ISSUE TITLE
Sizing of channel banner and avatar is too narrow

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2328]
### Steps to Reproduce

Go to Channel Settings > Appearance and open each of these dialogs

### Expected Behavior

The dialog is a reasonable width

### Screenshot or Screencast

![Screenshot_2019-10-24 Edit Channel MIT Open Learning](https://user-images.githubusercontent.com/28598/67505443-431ce480-f659-11e9-9bec-5190d3a75f5a.png)

**Comment by aliceriot** [comment]
whoops! that happened as a result of https://github.com/mitodl/open-discussions/pull/2286, I thought I fixed all the dialogs but I guess I missed this one
