### ISSUE TITLE
User can delete their own comments

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#233]
API issue is #280

We will show a delete link under all of a user's own comments. 

![image](https://user-images.githubusercontent.com/20047260/31288372-a925ab5a-aa92-11e7-965a-0672b351620a.png)

We will show a delete confirmation modal:

![image](https://user-images.githubusercontent.com/20047260/31288386-bbca27ea-aa92-11e7-9e69-820b47434aed.png)

After the comment has been deleted, we will delete the content of the comment, and show the text "[comment deleted by author]" or "[comment deleted by moderator]". The comment will stay in the comment tree. The user name and avatar will no longer be shown, nor will the upvoting arrows or the score. There is no way to un-delete a comment.

![image](https://user-images.githubusercontent.com/20047260/31288455-0443861a-aa93-11e7-8d3d-605290ab01d1.png)

![image](https://user-images.githubusercontent.com/20047260/31288462-0cbb6628-aa93-11e7-9e73-cb50f8a16b21.png)

**Comment by pdpinch** [comment]
Same question as https://github.com/mitodl/open-discussions/issues/234#issuecomment-334763483 will regular users be allowed to delete their own comments?

**Comment by roberthouse54** [comment]
Yes, regular users can also delete their own comments. We might as well just do both in one issue.

**Comment by roberthouse54** [comment]
We will show a delete link under a comment. We will only show this under the user's own comments. Moderators will see a delete link under all comments.

![image](https://user-images.githubusercontent.com/20047260/31288372-a925ab5a-aa92-11e7-965a-0672b351620a.png)

We will show a delete confirmation modal:

![image](https://user-images.githubusercontent.com/20047260/31288386-bbca27ea-aa92-11e7-9e69-820b47434aed.png)

After the comment has been deleted, we will delete the content of the comment, and show the text "[comment deleted by author]" or "[comment deleted by moderator]". The comment will stay in the comment tree. The user name and avatar will no longer be shown, nor will the upvoting arrows or the score.

![image](https://user-images.githubusercontent.com/20047260/31288455-0443861a-aa93-11e7-8d3d-605290ab01d1.png)

![image](https://user-images.githubusercontent.com/20047260/31288462-0cbb6628-aa93-11e7-9e73-cb50f8a16b21.png)
