### ISSUE TITLE
course search page search state should be refactored

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#2333]
when working on #2294 I realized that there are some issues with how the search state (i.e. which filters are selected) is stored on the search page. basically, we are storing the state in two places - in the URL and also in `this.state` on the search page component. But at different times there is a different source of truth: when you first load the page we read from the URL to populate the state. thereafter, changes are first persisted to the state and then echoed back to the URL, but changing the URL (without reloading the whole page) doesn't affected the state.

I'm not exactly sure the best way to do this, but I think this should be rethought. The problem I ran into was that I wanted to use a react-router `<Link>` component to link to a particular search from the `LearningResourceCard`. This would change the URL, and my expectation was that doing that would cause the search to change. Instead it doesn't trigger any search, and then changing a filter or scrolling down the page actually causes the values in the URL to be overwritten, because the current values from `this.state` on the page component are echoed into the URL.

In my mind if we can get away with driving the whole search state off of the URL and using that as the consistent source of truth that would be nice and might let us refactor some of the state-based code.

Anyhow, in working on #2294 I didn't want to take the time to do this so I just ended up using normal `<a>` tags and forcing a full-page refresh, which gave me the behavior I wanted, but that is a hack that I'd like to be able to un-do later.

**Comment by rhysyngsun** [comment]
Some other odd behavior is arising out of our implementation, specific steps I've seen are:

1) Check User Lists option:
![Screenshot_2019-10-25 MIT Open Learning](https://user-images.githubusercontent.com/28598/67588340-e3d7d680-f723-11e9-86bc-9a0b110353d7.png)
2) Reload the page and note that the unchecked facet options disappear:
![Screenshot_2019-10-25 MIT Open Learning(1)](https://user-images.githubusercontent.com/28598/67588362-f0f4c580-f723-11e9-81c5-83868bd59357.png)
3) Uncheck the checked option and note the sort of the options is wrong:
![Screenshot_2019-10-25 MIT Open Learning(2)](https://user-images.githubusercontent.com/28598/67588394-00740e80-f724-11e9-9fdf-b366faefed86.png)

**Comment by aliceriot** [comment]
a side benefit of this is that, after conslidating `/learn` routes into a sub-router for #2360 this would let us also consolidate the course header into one file, instead of having it replicated across all learn pages like we do now. with the search state as it is we can't do this, though, because the search bar needs access to callbacks on the search page.
