### ISSUE TITLE
Post owner can delete posts

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#234]
There is a separate issue, #273 for the API work necessary for this, which includes deleting a post and retrieving the deleted post from a channel. 

We will show a delete link under a post. We will only show this under the user's own posts. 

![image](https://user-images.githubusercontent.com/20047260/31289321-5494b7bc-aa96-11e7-8bee-ebbec5641644.png)

We will show a delete confirmation modal:

![image](https://user-images.githubusercontent.com/20047260/31289335-5f9f039c-aa96-11e7-8716-5fd403a2ea73.png)

After the post has been deleted, we will delete the content and the title of the post, and show the text "[post deleted by author]" or "[post deleted by moderator]" in the post title. The user name and avatar will no longer be shown, nor will the upvoting arrows or the score. The post will no longer be displayed in the channel page or on the home page. But if a user has a link to the post, they will be able to link to the page and see the comments tree, but the post itself will be displayed as shown.

![image](https://user-images.githubusercontent.com/20047260/31289420-b0fc867e-aa96-11e7-8d56-bdff2be43ec0.png)

**Comment by pdpinch** [comment]
Just double-checking: will it only be moderators who can delete posts? 

Can regular users delete their own posts?

**Comment by pdpinch** [comment]
Just double-checking: will it only be moderators who can delete posts? 

Can regular users delete their own posts?

**Comment by roberthouse54** [comment]
I think regular users can also delete their own posts. We might as well just do both in one issue.

**Comment by roberthouse54** [comment]
We will show a delete link under a post. We will only show this under the user's own posts. Moderators will see a delete link under all posts.

![image](https://user-images.githubusercontent.com/20047260/31289321-5494b7bc-aa96-11e7-8bee-ebbec5641644.png)

We will show a delete confirmation modal:

![image](https://user-images.githubusercontent.com/20047260/31289335-5f9f039c-aa96-11e7-8716-5fd403a2ea73.png)

After the post has been deleted, we will delete the content and the title of the post, and show the text "[comment deleted by author]" or "[comment deleted by moderator]" in the post title. The user name and avatar will no longer be shown, nor will the upvoting arrows or the score. The post will no longer be displayed in the channel page or on the home page. But if a user has a link to the post, they will be able to link to the page and see the comments tree, but the post itself will be displayed as shown.

![image](https://user-images.githubusercontent.com/20047260/31289420-b0fc867e-aa96-11e7-8d56-bdff2be43ec0.png)

**Comment by pdpinch** [comment]
Updated the description to reflect [Rob's comment](https://github.com/mitodl/open-discussions/issues/234#issuecomment-334813403)
