### ISSUE TITLE
Index user lists and paths in Elasticsearch when they are created/updated via the API

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2347]
As a user, the user lists and learning paths I create should be searchable by me (if private) or everyone (if public)

**Comment by mbertrand** [comment]
@pdpinch @Ferdi do you foresee any need to ever change/delete a user's lists from django admin or the console?  If not, I can implement this in the serializers, otherwise I should override the model's save/delete methods.

**Comment by pdpinch** [comment]
As long as a user can delete their list, I think we should be OK.
