### ISSUE TITLE
Implement "Add New List" button on "Add To List" Dialog

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2357]
Triggering the 'Create New List' dialog from the 'Add to List' dialog did not work seamlessly as expected, only one dialog can be open at a time. Here is the approach suggested by @aliceriot:

- refactor the create user list form so that it's a self-contained component and not tied to the dialog
- clicking a 'Create List' button  will change what form is displayed in the add to list dialog to 'create new list' instead
- have a 'back' button up on the corner to back out of creating a new list(that would go back to the list of already-created lists)
- then if the user wanted to create a list they could create it there and then we could back them out to the initial screen in the dialog

**Comment by aliceriot** [comment]
@abdulkdawson this is what we were thinking as a way to workaround a little limitation in the existing implementation - does that make sense to you from a user-experience perspective?
