### ISSUE TITLE
UI for Pinning posts

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#236]
There is a separate API issue for this: #194

Moderators will see a "pin" link under every post. Clicking the link will pin posts to the top of the channel. We will display pinned posts with a blue background, and the pin icon. If multiple posts are pinned, we will show the latest pinned post at the top. There will be an "unpin" link for pinned posts, which will return the post to the regular list of posts.

![image](https://user-images.githubusercontent.com/20047260/31397009-da499c5a-adb2-11e7-937c-689cdce79cdb.png)

**Comment by rhysyngsun** [comment]
I assume we're following Reddit's UI pattern and only returning these on the first page?

**Comment by roberthouse54** [comment]
Yes, we should follow reddit's UI here. Also, just to clarify... pinning only seems to work on channel pages. So the home page with all the aggregated posts will not show any pinned posts.

**Comment by aliceriot** [comment]
one thing to note is that Reddit does not allow pinning of URL posts, only of text posts
