### ISSUE TITLE
Move /courses to /learn

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2360]
@pdpinch commented on [Fri Nov 01 2019](https://github.com/mitodl/mitxpro/issues/1283)

As a user, it's confusing that I can search for videos in a URL with the path /course

#### Acceptance Criteria:

- [x] `/courses` ⇒ `/learn`
- [ ] add a 301 redirect from `/courses` ⇒ `/learn` since we have shared the URL on RC with some people for testing.

**Comment by aliceriot** [comment]
when we do this I think we should refactor the routing for `/learn` to have a separate router component, so we can render stuff like the header in one place, have one place to fetch any data we'll want across the whole `/learn` section, etc. We have a set up like this currently for the channel pages (`<ChannelRouter />`)
