### ISSUE TITLE
When clicking on "reply" for a comment, the focus should go in the text area

### ISSUE THREAD

**Issue by giocalitri** [mitodl/open-discussions#237]
It does not go automatically there and it is confusing.

![screen shot 2017-10-02 at 3 10 19 pm](https://user-images.githubusercontent.com/1005204/31094718-1b33e778-a784-11e7-8f08-53b080403600.png)

**Comment by giocalitri** [comment]
@roberthouse54 What do you think?

**Comment by roberthouse54** [comment]
Yes, it should.
