### ISSUE TITLE
VIdeo Search: Functions to download and parse transcripts

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#2375]
The transcript download functionality of the official youtube api requires channel owner permissions and uses a lot of quota so we will download transcripts using pytube, an external api.

Since transcript downloads are significantly slower than other  video fetch and update commands
we will have separate tasks for populating and uploading transcripts 

- Create a function to pull the captions from pytube for a video
- Parse the captions to generate a transcript

Tasks to generate and update transcripts will be added once https://github.com/mitodl/open-discussions/pull/2343 is merged

**Comment by pdpinch** [comment]
What's involved with "Parse the captions to generate a transcript" ?

**Comment by abeglova** [comment]
@pdpinch Captions are returned as xml with timestamps for the caption and the caption text. The PR extracts and joins the text part of the captions to form a transcript

**Comment by rhysyngsun** [comment]
Fixed in #2368
