### ISSUE TITLE
API response for list of user lists gets too large

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2378]
### Steps to Reproduce

- Make some user lists with many courses
- Add those user lists to other user lists

### Expected Behavior

View 'My Lists', it should load quickly

### Actual Behavior

It takes awhile to load because the API response is so large.  

The API response should be simplified to exclude most of the list item data when retrieving all lists.  That information is only required when viewing the details of a specific list.

**Comment by aliceriot** [comment]
this is a good idea to address now I think, users could have lists with hundreds of items in them so it could get pretty bad.

for the UI on the list index page (`/courses/lists/`) the only piece of data we'll need about the items _in_ the list to display the UI we're currently displaying is how many items and the cover image for the first one

**Comment by aliceriot** [comment]
@mbertrand is there more to do in order to simplify / smallify the response?

**Comment by mbertrand** [comment]
If/when we figure out a way to get the star button to work without requiring all favorites/lists at once, then reducing the page size, but maybe that should be a separate issue and I can close this one.
