### ISSUE TITLE
Many comments break the UI

### ISSUE THREAD

**Issue by giocalitri** [mitodl/open-discussions#238]
It looks like it depends on the resolution and dimension of the browser page, but this happens.
![screen shot 2017-10-02 at 4 33 00 pm](https://user-images.githubusercontent.com/1005204/31098094-8401a942-a78f-11e7-943f-4296bd9f04d9.png)

**Comment by giocalitri** [comment]
@roberthouse54 Not sure what we should do

**Comment by aliceriot** [comment]
probably after a certain point we would need to stop indenting, but then we need to figure out a different way in the UI to show that a comment is a reply to another comment. On reddit they seem to indent to a point, and then they do 'continue this thread' which opens the sub-comments in a different view, like this:

![fofofofofofofofofofofof](https://user-images.githubusercontent.com/6207644/31178794-1c31395e-a8e8-11e7-8ef8-b144ce9c5d12.png)

(from [this post](https://www.reddit.com/r/food/comments/7404ve/i_ate_the_super_full_english_breakfast/?st=j8d2x358&sh=abaf0311))

Reddit also indents a bit less than we do currently, so we could turn that down a little bit as a temporary fix for this problem.

**Comment by roberthouse54** [comment]
I am going to indent less for comments. We have discussed limiting the depth of nesting to 10 levels, and at that level, just hide the reply link. Or we can do what @aliceriot suggests above, although I am guessing that is more work, and probably overkill for our purposes. @Ferdi ?

**Comment by giocalitri** [comment]
This is actually a pretty important issue also for the implementation of #78 
How do we expand the comments: Reddit has 2 approaches:

1. expands in the same page for comment at a deepness <= 10
2. expands in a new page for comments at a deepness > 10

If we do not want to handle deepness >10 than we avoid a big chunk of problems, but we limit the conversation deepness.

I have no strong opinions, but depending on what we decide to do, I might implement the comments expansion in a different way.

@pdpinch @Ferdi

**Comment by Ferdi** [comment]
Even 10 levels deep is too much.  Definitely not more than 10

**Comment by giocalitri** [comment]
so how will a "flame" look like?

**Comment by roberthouse54** [comment]
The indentation has been fixed by https://github.com/mitodl/open-discussions/pull/252

**Comment by pdpinch** [comment]
This should be avoid by https://github.com/mitodl/open-discussions/issues/269
