### ISSUE TITLE
Next parameter not set in login / sign up dialog

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2390]
### Steps to Reproduce

1. Logout 
2. Go to `/courses/search`
3. Click on the save/bookmark icon on the first search result
4. In dialog that pops-up, click on "Log in"
5. Enter a correct email and password to log in

### Expected Behavior

- user should be redirected to the page they were on

### Actual Behavior

- user is redirected to the home page

**Comment by rhysyngsun** [comment]
This is also happening in other places this ui is used - create a post button, new comment ui, etc. The PR will fix all of those in one go.
