### ISSUE TITLE
Display similar learning resources in drawer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2436]
As a search user, I'd like to see a list of similar resources when I open the drawer to view the details of al learning resource.

#### Designs and Mockups

https://projects.invisionapp.com/d/main#/console/18704964/392640678/preview

#### Acceptance Criteria:

- [ ] Add "Similar Learning Resources" header below learning resource details in drawer
- [ ] Display list of 3 similar resources when expanded
- [ ] Clicking a resources replaces current drawer contents with resource details
  - [ ] display back button so user can return to prior item (similar to user list UX)

**Comment by mbertrand** [comment]
@pdpinch seems like Elasticsearch's 'more like this' query could be used to get the similar resources - https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html

**Comment by mbertrand** [comment]
@pdpinch @ferdi Based on the design, it looks like similar resources can be of any type (video, course, bootcamp, etc) and not necessarily match the type of the resource in the drawer, is that correct?

**Comment by Ferdi** [comment]
@mbertrand that's correct

**Comment by mbertrand** [comment]
>display back button so user can return to prior item (similar to user list UX)

That sounds the same as #2440 currently being worked on by @aliceriot

**Comment by aliceriot** [comment]
yeah when #2440 is finished that should be all set. also currently I'm working on #2466 and refactoring the CSS for the drawer pretty extensively, just fyi :grimacing:
