### ISSUE TITLE
Cards in drawer have no visual separation

### ISSUE THREAD

**Issue by Ferdi** [mitodl/open-discussions#2438]
![cardsindrawer](https://user-images.githubusercontent.com/125561/70022646-e3bcc900-1562-11ea-9cde-0d23d2e01304.png)

**Comment by aliceriot** [comment]
the designs are a little inconsistent so I just want to confirm what we want. I think we discussed in planning that we wanted the separators to be like what is show in this design:

https://projects.invisionapp.com/d/main#/console/18704964/392253636/preview

![separtor](https://user-images.githubusercontent.com/6207644/70157535-c2073300-1683-11ea-95a3-695fe751cdc4.png)

The current implementation is based on what's shown in this design:

https://projects.invisionapp.com/d/main#/console/18704964/392640678/preview

![separtorffff](https://user-images.githubusercontent.com/6207644/70157578-ce8b8b80-1683-11ea-8526-786af6e6b040.png)

do we want to have the title style in the second design, with the grey background for the text?

**Comment by abdulkdawson** [comment]
@aliceriot The InVision files have been updated to reflect what we want. Here is the link [https://projects.invisionapp.com/d/main#/console/18704964/393473372/preview](https://projects.invisionapp.com/d/main#/console/18704964/393473372/preview)

[https://projects.invisionapp.com/d/main#/console/18704964/392640678/preview](https://projects.invisionapp.com/d/main#/console/18704964/392640678/preview)
