### ISSUE TITLE
Home page card title should be "Home" instead of "Home Page" 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#244]
The default page at / should have a title of "Home" instead of "Home Page"

**Comment by aliceriot** [comment]
which title is this referring to? The title should be 'MIT Open Discussions'

**Comment by roberthouse54** [comment]
This is, I believe, referring to the title that is in the card here:

![image](https://user-images.githubusercontent.com/20047260/31186808-bc967c50-a8fd-11e7-9fb7-212237b12360.png)

And this also applies to the breadcrumb text.

**Comment by aliceriot** [comment]
Gotcha,
