### ISSUE TITLE
UI: horizontal scrollbar in sorting options

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2450]
### Steps to Reproduce

Click the dropdown to sort the frontpage or a channel

Noticed this on firefox / ubuntu

### Actual Behavior

Dropdown has a scrollbar

### Screenshot or Screencast

![Screenshot_2019-12-04 Settings MIT Open Learning](https://user-images.githubusercontent.com/28598/70161116-8ec7a280-1689-11ea-8b1f-f3e7e7d443df.png)

**Comment by aliceriot** [comment]
seeing it in chrome too:

![Screenshot from 2020-01-14 10-40-42](https://user-images.githubusercontent.com/6207644/72358301-579dd580-36ba-11ea-8d5a-18fa276a8626.png)
