### ISSUE TITLE
Learn: update drawer styling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2466]
#### Designs and Mockups

[InVision](https://projects.invisionapp.com/d/main#/console/17477251/392253808/preview)

#### Acceptance Criteria:

- [x] #2253 change course button and logo
- [x] Update font and size of title
- [x] Update text styling of description
- [x] Hide "Read More" link when there is nothing more to read
- [x] remove "Info" header"
- [x] Change styling of metadata section
  - [x] text color
  - [x] two-column layout
  - [x] change "topics" label to "subjects" 
  - [x] remove button styling for topics/subjects

**Comment by aliceriot** [comment]
@pdpinch @Ferdi @abdulkdawson how's this looking? still need to add the platform logo next to 'take course'

![ffnfnfnfnf2](https://user-images.githubusercontent.com/6207644/70645669-67d21900-1c13-11ea-8852-6444ce0de5ba.png)
![ffnfnfnfnf](https://user-images.githubusercontent.com/6207644/70645670-67d21900-1c13-11ea-820e-1f474e9004f8.png)

**Comment by Ferdi** [comment]
In the metadata section the labels are to far from the values. It makes it hard to read imo. I'd bring them as close as possible

**Comment by Ferdi** [comment]
@aliceriot I like better the treatment of "subjects" in the current design /cc @pdpinch @abdulkdawson

**Comment by aliceriot** [comment]
sure, I can do either way as soon as we decide how we want to go

**Comment by abdulkdawson** [comment]
@aliceriot @pdpinch This is looking good so far but I do agree that there is too much spacing between the metadata labels and the values.

**Comment by aliceriot** [comment]
yeah, I was going based on the designs which have a two-column layout for the metadata. I could try out a 1/3 - 2/3 split on the column widths instead of 50 / 50 or something, whatever we want to go with.

do we have a decision on what we want to do with the subjects?

**Comment by abdulkdawson** [comment]
@aliceriot both the metadata labels and values should be left-justified and lined up accordingly as its shown in the design we can just try to reduce the white space between the labels and values. As for the topics or "Subjects", I agree with @Ferdi that the current treatment feels better to me.

**Comment by aliceriot** [comment]
how's this look?

![fjfjfndfasdfasdf](https://user-images.githubusercontent.com/6207644/70828275-12d00780-1db9-11ea-80ed-5f4d3230245a.png)

**Comment by abdulkdawson** [comment]
@aliceriot This looks good but I feel that we could increase the width of the button. What the width of the button?

**Comment by aliceriot** [comment]
right now it's based on the width of the text, which can change, i.e.

![bootcamp](https://user-images.githubusercontent.com/6207644/70828784-0ac49780-1dba-11ea-99f8-922473339ff2.png)

so it's doesn't have a fixed width. here's the padding it has:

![buttonpadding](https://user-images.githubusercontent.com/6207644/70828777-05ffe380-1dba-11ea-9294-f4baa7e4f506.png)

**Comment by abdulkdawson** [comment]
@aliceriot Can we increase the padding to widen the button?

**Comment by aliceriot** [comment]
sure, here's with `45px` horizontal padding:

![buttonwidth](https://user-images.githubusercontent.com/6207644/70829535-fe413e80-1dbb-11ea-8260-4c58a8d1092e.png)

Ferdi also suggested adding a little header for the "Metadata" section as well (although that could easily be "Info" or "Details" instead)

**Comment by aliceriot** [comment]
here, with "Info":

![fnfndfasdfadfpppfnfn](https://user-images.githubusercontent.com/6207644/70829706-5bd58b00-1dbc-11ea-8491-22d6a671f021.png)
![fnfndfasdfadfppp](https://user-images.githubusercontent.com/6207644/70829707-5bd58b00-1dbc-11ea-9ff6-b8a4a9ca412d.png)

**Comment by abdulkdawson** [comment]
@aliceriot This looks great. Thank you.
