### ISSUE TITLE
Change header to "MicroMasters Discussions" and link back to MicroMasters

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#247]
As a user, I'd like to know that I'm taking part in a MicroMasters discussion and be able to link back to my dashboard. 

We can change the header from "Open Discussions" to "MicroMasters Discussions" and link back to the MicroMasters site. Ideally this would be done using the MicroMasters cookies so that, in the future, we can make it work with other sites.

**Comment by roberthouse54** [comment]
The header was changed in https://github.com/mitodl/open-discussions/pull/252

The link back to MM is being done in https://github.com/mitodl/open-discussions/pull/259

**Comment by pdpinch** [comment]
Looks like this is done
