### ISSUE TITLE
Courses: blacklist degenerate courses 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2492]
As a user, I don't want to see courses in search that I can't view or are otherwise somehow degenerate. 

In some cases, these courses should be removed from the upstream APIs (like edX, or OCW) but it will take us to long to get them removed and we need a simple way to hide them from our search. 

#### Acceptance Criteria:

- [ ] maintain a simple list of course ids that should be omitted from search

#### Related Issues

#2490 
#2439

**Comment by mbertrand** [comment]
@pdpinch do you think we'll ever need to blacklist videos, programs, etc or just courses?

**Comment by mbertrand** [comment]
Also, do you want this list maintained via django admin, via a 'BlacklistedCourse' object that you can create with a specified course id?  

Another option is to add a 'blacklisted' boolean field to the 'Course' model, but if for any reason we need to delete and reimport all courses then this field would need to be repopulated again afterward.
