### ISSUE TITLE
Add "play" icon over video thumbnails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2493]
As a user, I'd like to easy see which learning resources are videos in search results. 

#### Designs and Mockups

https://invis.io/XRRX2PH5KZM#/375097415_Open_Courses_Videos

#### Acceptance Criteria:

- [ ] layer play button on top of all video thumbnails

**Comment by abdulkdawson** [comment]
Here is the "play" icon for video. 
![Youtube_Icon](https://user-images.githubusercontent.com/49685474/71190915-688e2f00-2253-11ea-9f43-cb65271072e1.png)

**Comment by abdulkdawson** [comment]
Here is the link to the Invision file for the placement of the Youtube Icon. [https://projects.invisionapp.com/d/main#/console/17477251/390731424/preview](https://projects.invisionapp.com/d/main#/console/17477251/390731424/preview)

The icon is to be placed over the video thumbnail to inform users that the Learning Resource is a Video. The icon has no additional behavior as the video will only play once the drawer is opened.
