### ISSUE TITLE
Include "created by" field on learning list cards

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2495]
As a user, I'd like to know who created the learning list and learning pathways that show up in my search results. 

#### Designs and Mockups

https://invis.io/XMUOHOGE6GN#/391800495_Open_Courses_with_Learning_Path_Drawer

#### Acceptance Criteria:

- [ ] Display "created by" on cards in the same location as "offered by" on course and video cards.

**Comment by aliceriot** [comment]
this is present on master already:

![onmasteralready](https://user-images.githubusercontent.com/6207644/71104728-41b7f600-218a-11ea-979e-20ca4b1c11bf.png)
