### ISSUE TITLE
Learn: course cards in grid view should always be the same height

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2496]
### Steps to Reproduce

1. On the current front page of learn, the 3rd course card is shorted than the others: 

![image](https://user-images.githubusercontent.com/430126/71054279-6b880300-211f-11ea-80e5-7fdedf456e54.png)

2. In the grid view of https://discussions-rc.odl.mit.edu/learn/search?q=the%20human%20brain the same course card is also shorter than the others: 

![image](https://user-images.githubusercontent.com/430126/71054303-822e5a00-211f-11ea-8ef6-10837601b1a8.png)

### Expected Behavior

- All cards should be the same height

**Comment by aliceriot** [comment]
@abeglova was this closed by #2532?

**Comment by abeglova** [comment]
@aliceriot Yes! Closed
