### ISSUE TITLE
Learn: allow user to dismiss search text

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2498]
As a search user, I would like an easy way to remove the search term I entered without changing the filters

#### Designs and Mockups

TBD, but maybe we can just reuse the "x" button from the Open site search: https://discussions-rc.odl.mit.edu/search/?q=human%20brain

#### Acceptance Criteria:

- [ ] after user has typed at least one letter, display the "x" button 
- [ ] after the button is pressed, update the search results and hide the button

**Comment by abdulkdawson** [comment]
@pdpinch Here is a mock for dismissing search text. I went with the x button used in Discussions.

[https://projects.invisionapp.com/d/main#/console/17477251/364881478/preview](https://projects.invisionapp.com/d/main#/console/17477251/364881478/preview)
