### ISSUE TITLE
Learn: support quoted search terms

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#2499]
As a user, I'd like to be able to use a quoted phrase to narrow my search results. 

#### Acceptance Criteria:

- [ ] For example searching for [`"Zied Ben Chaouch"`](https://discussions-rc.odl.mit.edu/learn/search?c=paid&q=%22Zied%20Ben%20Chaouch%22&t=Math&type=course) should not return more results than searching for [`Chaouch`](https://discussions-rc.odl.mit.edu/learn/search?c=paid&q=Chaouch&t=Math&type=course)

**Comment by mbertrand** [comment]
```
{
  "query": {
    "query_string": {
      "query": "\"mechanical engineering\""
    }
  }
}
```

**Comment by mbertrand** [comment]
@rhysyngsun do you happen to have any notes on your research into this topic?

**Comment by rhysyngsun** [comment]
@mbertrand we use the fuzziness option here for the contributor search: https://github.com/mitodl/open-discussions/commit/449e92bd41a1acf4f195e30b7de6d6a90d8be436#diff-eb5b7e9628779c867533584db6e7b917R204

The ES docs indicated that's incompatible with the quoted string search. That's about as far as i'd looked into it.

**Comment by mbertrand** [comment]
@Ferdi should this work with any type of quote (``` ` | ' | " ```) or just double quotes ```"``` ?
