### ISSUE TITLE
Learn: support ‘did you mean’ search suggestions

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2506]
As a user, I'd like to to see 'did you mean' search suggestions under particular circumstances (for example, no results or less than a minimum number of results returned for a search term query).

#### Acceptance Criteria:

- [ ] Requirement

#### Out of Scope

- Not going to do

**Comment by mbertrand** [comment]
@pdpinch @Ferdi do you think it makes sense to show suggested search terms under the following conditions:
- A search term is used, and
- No results or less than X (configurable via .env) results are returned for the search term

I think the [ES phrase suggester](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/search-suggesters-phrase.html) is probably the best one use since it can handle both single word and multiple word terms.

**Comment by mbertrand** [comment]
Some additional UI questions besides above: how many suggestions to display, where to display them, whether each suggestion should be a link that reruns the search with that term - @abdulkdawson @Ferdi @pdpinch

**Comment by pdpinch** [comment]
I like Matt's criteria:

> - A search term is used, and
> - No results or less than X (configurable via .env) results are returned for the search term
 
I'd like Abdul's input on the other questions, but my opinion is that one suggestion should be enough, and that a link to re-run the same search with the suggested search term(s) makes sense.

**Comment by abdulkdawson** [comment]
@mbertrand @pdpinch @Ferdi As far as suggestions are concerned I guess it depends on the length of the search term. If the search term is 3 or more words then yes we can return 1 suggestion. If the search term is 1 word then we can possibly provide a max of 3 suggestions. We have to assume that if a person searches a single word term than there is also a potential for there to be at most 3 very similar words to the one that was searched.

**Comment by pdpinch** [comment]
@mbertrand I'm happy with your implementations. We can close this.
