### ISSUE TITLE
Add Terms of Service link to footer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#256]
- [x] Add link to Community Guidelines: https://discussions.odl.mit.edu/content_policy/
- [x] Add link to MicroMasters Terms of Service https://micromasters.mit.edu/terms_of_service/ (conditionally, if possible)

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/34835197-2937a7fa-f6c2-11e7-8999-5fde9858b6ba.png)

**Comment by aliceriot** [comment]
what's the link for 'give to MIT'?

**Comment by aliceriot** [comment]
I'm going to go with what we use in MicroMasters (https://giving.mit.edu/explore/campus-student-life/digital-learning)
