### ISSUE TITLE
OCW_ITERATOR_CHUNK_SIZE

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2573]
#### Summary

Describe where/how to generate these new values

- `OCW_ITERATOR_CHUNK_SIZE` for ocw course import

#### Applicable Environments

- [x] Apply configuration to CI - value of 5000
- [x] Apply configuration to RC - value of 1000
- [x] Apply configuration to Production - value of 1000

**Comment by mbertrand** [comment]
@shaidar @blarghmatey  this should be in place before the current RC is released to production

**Comment by shaidar** [comment]
Added to all envs

**Comment by shaidar** [comment]
This is in place. Closing now.
