### ISSUE TITLE
Race condition when creating a new channel

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#258]
When I created a channel I was redirected to discussions and got an error message due a 500 error on the discussions posts API, due to a 403 error from reddit. When I refreshed it worked fine.

**Comment by noisecapella** [comment]
I think the root cause here is that the adding of moderators was moved to a task, since there may be an arbitrary number of moderators and we don't want to increase the time of the request. One workaround is to add the creating user as a moderator immediately

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/discussions/issues/362196650/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/discussions/issues/357295935/
