### ISSUE TITLE
Tika env settings

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2588]
#### Summary

- `TIKA_SERVER_ENDPOINT`
- `TIKA_ACCESS_TOKEN`

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by shaidar** [comment]
Deployed to CI/RC. Haven't built/deployed production instances yet and will deploy it there once those instances are in place

**Comment by shaidar** [comment]
The Tika cluster for production is in place and the keys are in pillar. Closing.
