### ISSUE TITLE
Collapse Comment Tree

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#261]
As a user, it would be useful to be able to hide particularly long comment trees.

**Comment by roberthouse54** [comment]
We will show a [-] or [+] link to the left of the user name in the comments tree. Clicking [-] collapses all comments under that parent. Clicking [+] opens the children of the parent comment.

![image](https://user-images.githubusercontent.com/20047260/31288575-7c898714-aa93-11e7-956d-0ef4f92ecc24.png)

**Comment by aliceriot** [comment]
@pdpinch do you think we can close this?
