### ISSUE TITLE
S3-triggered webhook to import/update OCW courses

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2612]
Currently a daily celery task is run to crawl through all OCW S3 subfolders looking for updated content.  Replace with an S3 event on the OCW source bucket that sends an SNS message to `../api/v0/ocw_webhook` whenever an S3 object is added, updated, or deleted.  This webhook endpoint should then trigger a task to process that particular OCW course/run.

- The event should be triggered by any S3 object creation/deletion event having a suffix of `0/1.json`
- There should be a small delay between reception of the webhook call and import of the affected OCW course/run, to make sure all relevant JSON files have been created/updated on S3.

**Comment by mbertrand** [comment]
@blarghmatey @shaidar @markbreedlove what do you think of an S3 event on the OCW bucket ("ocw-content-storage"), triggered by all create and delete events for object keys with a suffix of "0/1.json", that sends an SNS message to "../api/v0/ocw_webhook/"?

**Comment by markbreedlove** [comment]
I don't have any objection. Would it work on update, too?

The cron job that executes [export_courses.json](https://github.com/mitocw/ocwcms/blob/eb290f6ba1b71b700d1dec932a1a155877e264ce/publishing/export_courses_json.sh) runs every morning at 9 AM.

**Comment by mbertrand** [comment]
@markbreedlove I think S3 considers an update to be the same as create (create a new object overwriting the old object of the same key).

**Comment by blarghmatey** [comment]
I don't see any problems with adding event notifications to the bucket.

**Comment by markbreedlove** [comment]
@mbertrand I'll add this. Can you tell me the full URL to the API endpoint that it should request?

**Comment by mbertrand** [comment]
Eventually I think it will be:

https://discussions-ci.odl.mit.edu/api/v0/ocw_webhook/
https://discussions-rc.odl.mit.edu/api/v0/ocw_webhook/
https://open.mit.edu/api/v0/ocw_webhook/

but when the event notification is created, it sends a confirmation message with a link that needs be visited before it becomes active.  So maybe it's best to wait until the code is in place?  Unless you can retrieve that confirmation message from the console and visit the link manually.

**Comment by mbertrand** [comment]
@markbreedlove ^

**Comment by mbertrand** [comment]
@markbreedlove also, for the SNS subscription, is it ok to set "Raw message delivery" to True?

**Comment by markbreedlove** [comment]
@mbertrand I'm not sure about "Raw message delivery." I've read about it in [their docs](https://aws.amazon.com/sns/faqs/) but I didn't see that option when creating an email subscription.

For test purposes, I have created an email subscription to my new topic (named `ocw-content-storage-bucket-update`). I will create a subscription for you, as well. My idea is that this gives us the chance to see that it's being triggered and to see the message contents. You can then add the notification endpoint in the discussions app at your own pace, while knowing what to expect for message contents.

The final step is to set the event in the bucket that will message the topic. I'll do that, too.

**Comment by markbreedlove** [comment]
I've set up the S3 event now, so we can keep an eye out for emails when the bucket is updated. I hope it doesn't flood our inboxes.
