### ISSUE TITLE
Moderation: About this channel 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#263]
As a channel moderator, I'd like to display some information about the channel, such as rules for posting, along side the list of posts. 

### acceptance criteria
- [ ] Store description in reddit, if possible <- let's discuss before implementing
- [ ] Use existing PRAW APIs, if possible

Be sure to discuss the approach on this ticket before implementing.

**Comment by roberthouse54** [comment]
The "About" card will appear in the right column. The about text comes from the "Description" field in the Create New Channel modal. [Nice-to-have]: If possible, display the # of users that have access to the channel, and the # of users currently active in the channel.

TBD: Not sure what to do with this card in the mobile view.

![image](https://user-images.githubusercontent.com/20047260/31397720-c2f9dd7e-adb4-11e7-8641-4bd796427537.png)

**Comment by rhysyngsun** [comment]
@roberthouse54 your mockups don't show the channel list on the left side, which is currently there on larger browsers. Also, how is this handled for mobile?

**Comment by roberthouse54** [comment]
Yes, that will be ok. We will have a three column layout for large browsers.

**Comment by roberthouse54** [comment]
OK, for mobile, let's just move it underneath the posts card. We can revisit this later if we want to.

**Comment by rhysyngsun** [comment]
We decided in planning yesterday that for the sake of delivering this sooner we'll implement the description edit on a full page so we don't have to deal with pulling in a new dialog component.
