### ISSUE TITLE
Moderation: Add / remove moderators

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#265]
When channels are created via MicroMasters, the program staff are normally added as moderators. However, as a channel moderator I'd like to be able to add (and remove) additional moderators. For example, I might like to appoint a moderator from the community.

**Comment by rhysyngsun** [comment]
Issue moved to [mitodl/micromasters #3759](https://github.com/mitodl/micromasters/issues/3759) via [**ZenHub**](https://www.zenhub.com/)
