### ISSUE TITLE
Moira env variables for open-discussions

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2681]
#### Summary

Describe where/how to generate these new values

- `MIT_WS_CERTIFICATE ` - value of x509 certificate (as in OVS)
- `MIT_WS_PRIVATE_KEY` - value of x509 private key (as in OVS)
- `FEATURE_MOIRA` - True on RC/CI first, & production once #2627 deployed

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by shaidar** [comment]
@mbertrand Let me know if all looks good on CI and then I'll go ahead and apply it to RC

**Comment by mbertrand** [comment]
Looks good to me but I haven't had a chance to test it yet, will let you know after the PR is merged.

**Comment by mbertrand** [comment]
@shaidar working fine on CI

**Comment by shaidar** [comment]
Deployed on Prod
