### ISSUE TITLE
Use mimetypes with Content-Type header for OCW tika ingestion

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#2682]
As a end user, I'd like to have search results be more meaningful by looking at the file extension and passing a Content-Type based on that to the tika cluster.

cc @pdpinch @mbertrand. What do you think?

**Comment by pdpinch** [comment]
Sorry, I'm not exactly sure what you're suggesting, and what the user value might be?

**Comment by mbertrand** [comment]
👍 This should help tika parse data correctly when the data is not well-formed (for example, html snippets not contained in an `<html>` tag, or xml that doesn't start with `<?xml version="1.0"`)

**Comment by noisecapella** [comment]
@pdpinch What @mbertrand said. Instead of autodetecting, it would use the file extension to tell tika what kind of file it is so it can do better ingestion
