### ISSUE TITLE
As a logged in user I would like to view all comments of a particular post

### ISSUE THREAD

**Issue by Ferdi** [mitodl/open-discussions#27]

**Comment by pdpinch** [comment]
So the API is done for this but @aliceriot is still working on the front-end?

**Comment by aliceriot** [comment]
yeah that's right

**Comment by pdpinch** [comment]
Is this done now that #79 has merged?

**Comment by gsidebo** [comment]
@pdpinch That PR is showing generated comments. I'm guessing this issue covers the work to fetch comments via API and render them in the same way

**Comment by rhysyngsun** [comment]
@aliceriot merged her PR for the API integration last night, so this should be considered done
