### ISSUE TITLE
OCW_WEBHOOK_KEY

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2706]
#### Summary

Describe where/how to generate these new values

- `OCW_WEBHOOK_KEY ` - any hard to guess string value
- `FEATURE_WEBHOOK_OCW` - True

Required for #2687

#### Applicable Environments

- [ ] Apply configuration to CI
- [ ] Apply configuration to RC
- [ ] Apply configuration to Production

**Comment by markbreedlove** [comment]
I just did this:
```
head  -1 /dev/urandom | base64
```
... And then copied and pasted part of the first line of the output.

**Comment by markbreedlove** [comment]
@mbertrand Do you think that's good enough?

**Comment by markbreedlove** [comment]
For the record, this doesn't provide super high security, but it's enough for this purpose. SNS supports digest authentication over SSL, where you put `https://user:password@domain/` and the credentials are not sent in any way that would be logged, but that seems like too much for this case.

**Comment by pdpinch** [comment]
@mbertrand @markbreedlove what's the status of this? Can it be closed now?

**Comment by mbertrand** [comment]
I think so?  It's on heroku production and I didn't enter it there manually.

**Comment by markbreedlove** [comment]
Yes, this can be closed.
