### ISSUE TITLE
permalinks for comments

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#272]
For research purposes, and for SEO, it would be helpful for comments to have permalinks. 

Presumably, the template for a comment looks similar to a post, but the requested comment is at the root instead of a post.

**Comment by pdpinch** [comment]
This should be a simple design, based on how reddit handles comment permalinks.

**Comment by roberthouse54** [comment]
We want to copy exactly what reddit does here. So we will add a "permalink" link under each comment. The permalink UI will:

- Display the title and basic info of the post itself, but not display the post content, or the "Post a comment" UI.
- Display the permalinked comment **AND** all the comments beneath that comment in the thread. (See below)

![image](https://user-images.githubusercontent.com/20047260/34791261-782b9796-f612-11e7-8bfc-96197e4572ea.png)

**Comment by aliceriot** [comment]
what do we think for a URL for this? some options:

`/channel/:channel_name/:post_id/:comment_id`
`/channel/:channel_name/:post_id/comment/:comment_id`
`/comment/:post_id/:comment_id`

idk!

**Comment by aliceriot** [comment]
I think I'm going to do `/channel/:channel_name/:post_id/:comment_id`

**Comment by Ferdi** [comment]
How hard is to follow reddit convention ?   

Otherwise, something like `/channel/:channel_name/:post_id/comments/:comment_id`

**Comment by aliceriot** [comment]
I think the reddit convention will be a little tricky because we need to have the `postID` in the URL as well for our APIs, so I think the best option is `/channel/:channel_name/:post_id/comments/:comment_id`

**Comment by Ferdi** [comment]
ok, thx

**Comment by pdpinch** [comment]
This appears to be In Progress. I'll move it.
