### ISSUE TITLE
update posts API to allow post owner to delete post

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#273]
As the owner of a post, there may be times when I would like to delete my post.

**Comment by pdpinch** [comment]
What is standard reddit behavior for deleted posts? Are they included in the channel listing? Can they still be individually addressed?

**Comment by rhysyngsun** [comment]
they are not included in the listing but can be linked to

**Comment by aliceriot** [comment]
@rhysyngsun it looks like, if I call the `.delete` method on a post it no longer will come back in the Reddit API. When we do moderator post deletion we use `post.mod.remove`, which seems to do a different thing than `post.delete` - have you poked at that before? is there something I'm missing?

**Comment by rhysyngsun** [comment]
@aliceriot delete is the nuclear option, it removes the data permanently and can only be done by the object owner AFAIK, `remove` would be more aptly named `hide`.

**Comment by aliceriot** [comment]
ok cool, I will implement the user delete API using `.hide`

**Comment by roberthouse54** [comment]
I think we want the user to actually use .delete dont we?

**Comment by aliceriot** [comment]
It depends, do we want the post to be able to be un-deleted? should the comments on a post still be there? if we use the `.delete` method the post will be totally blown away and we can't get it back. `.hide` is more of a soft delete and can be un-done.

**Comment by aliceriot** [comment]
Alternatively we could add both behaviors, but we'd need to be sure to explain clearly to the user what the difference between them is

**Comment by roberthouse54** [comment]
My main thought was to stick as closely as possible with what reddit does by default. If anyone disagrees with that, we can discuss it.

**Comment by rhysyngsun** [comment]
For clarification:

`hide` - only hides the post for the user doing the hiding
`delete` - permanent removal of the post, only doable by the user who wrote it
`remove` - only doable by moderators, hides the post in channel listings for all users

**Comment by aliceriot** [comment]
Yeah, I think we'll go with `.delete` for this, I misunderstood Nathan's initial explanation of what `.hide` does.

**Comment by aliceriot** [comment]
This is actually already implemented, so for the delete posts feature no API work will be necessary. The `.delete` action is destructive though, it doesn't replace the post with a `[deleted]` placeholder or anything like that, it just blows it away completely.
