### ISSUE TITLE
Moderator can remove comments

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#278]
Remove is similar to delete, but slightly different. Only moderators can remove comments. Moderators can remove any comments, including their own. Moderators can also delete their own comments, hence moderators will see both "remove" and "delete" links on their own comments. On all other comments, moderators only have the remove option.

When a comment is removed, it still appears in the comment tree, with a  message saying "[comment removed]". Removed comments can be un-removed by moderators by clicking "Approve". Moderators will still be able to see the text of removed comments, although they will be grayed out.

(See mocks below)

The API issue for this is #196

![image](https://user-images.githubusercontent.com/20047260/31553718-5f0a3230-b009-11e7-8f02-54dd428eba25.png)

![image](https://user-images.githubusercontent.com/20047260/31553733-6d13ec54-b009-11e7-8f1a-8c9436eb558b.png)

**_NOTE: After the comment is removed, we will show a standard "Toast" message saying "Post Removed" (no mock for this.)_**

Removed comment as seen by moderator:
![image](https://user-images.githubusercontent.com/20047260/31553761-7e06d562-b009-11e7-8360-41b3711a94f0.png)

Removed comment as seen by user:
![image](https://user-images.githubusercontent.com/20047260/31553774-883edf5c-b009-11e7-9926-1721ae7a391b.png)

**Comment by rhysyngsun** [comment]
@pdpinch @roberthouse54 is there a confirmation for approving a comment? if yes, what message should that display?

**Comment by roberthouse54** [comment]
I assume you mean for removing a comment. If that is right, let's go with "Are you sure you want to remove this comment?" Yes | Cancel

**Comment by roberthouse54** [comment]
Sorry, scratch that..... I forgot we had "Approve". I don't think we need a confirmation for this.

**Comment by rhysyngsun** [comment]
Note: removed comments don't come back from the reddit API at all for non-moderator users, so they just won't show up for them (as opposed to the mockup above where you seen an indicator it was removed).
