### ISSUE TITLE
Post titles longer than ~75 chars get clipped

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#283]
This happens on both the frontpage, channel page, and post page:

post page:
![selection_087](https://user-images.githubusercontent.com/28598/31452984-76b7fae8-ae7e-11e7-81f6-851b251ceb77.png)

channel/front pages:

![selection_086](https://user-images.githubusercontent.com/28598/31452985-76c1bbf0-ae7e-11e7-8674-c472c5a76188.png)

**Comment by Ferdi** [comment]
A bit of an edge case cause you dont have spaces, right ?

**Comment by rhysyngsun** [comment]
yeah, fair enough, I didn't think that it was because of one big word, seems to format fine otherwise so I'll close.
