### ISSUE TITLE
Add Rest APIs for channels, posts

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#29]

**Comment by noisecapella** [comment]
Here's the API outline for channels:

    GET api/v0/channels - returns list of channels the user is subscribed to. Just list of detail views
    GET api/v0/channels/{subreddit}/
    {
        "name": "subreddit", # this is a unique identifier, what comes after /r/
        "title": "Title of the subreddit",
        "theme_type": "private" or "public",
    }
    
    POST api/v0/channels
    {
        "name": "subreddit",
        "title": "Title",
        "theme_type": "private" or "public"
    }
    
    PATCH api/v0/channels/{subreddit}/
    {
        "title": "Title",
        "theme_type": "private" or "public",
    }
    
    # No DELETE, not sure if reddit offers this

**Comment by noisecapella** [comment]
The API outline for posts:

    
    POST api/v0/channels/{subreddit}/posts/
    {
      "title": "post title",
      "text": "text",  # only one of these two should be present
      "url": "url",
    }
    
    Returns same as GET
    
    GET api/v0/channels/{subreddit}/posts/
    Just a list of posts, same format as detail view
    
    
    GET api/v0/channels/{subreddit}/posts/{post_id}/
    {
        "id": "post_id",
        "title": "post title",
        "upvotes": upvotes,
        "downvotes": downvotes,
        "author": "reddit username goes here",
        "text": "text",  # Only one of these should be present
        "url": "url",
    }
    
    PATCH api/v0/channels/{subreddit}/posts/{post_id}/
    Only `text` field allowed to replace text context. No URL editing allowed. Return value is `{ "text": "your text here" }`
    POST api/v0/channels/{subreddit}/posts/{post_id}/upvote
    Returns new upvotes, downvotes values in dict as { upvotes: 456, downvotes: 123 }
    POST api/v0/channels/{subreddit}/posts/{post_id}/downvote
    Returns new upvotes, downvotes values in dict as { upvotes: 456, downvotes: 123 }

    DELETE api/v0/channels/{subreddit}/posts/{post_id}/
    Deletes a post

**Comment by aliceriot** [comment]
How do we deal with fetching the comments? I was just thinking about this and realized I hadn't seen anything about it yet.
