### ISSUE TITLE
Make moderator API idempotent

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#290]
@rhysyngsun got an error which I was unable to reproduce: https://github.com/mitodl/micromasters/pull/3616#issuecomment-335538028

but this is now showing up on sentry: https://sentry.io/mit-office-of-digital-learning/discussions/issues/364467281/

Maybe there is a race condition between checking the moderator list and adding the new moderator?

**Comment by pdpinch** [comment]
Moving this to in progress
