### ISSUE TITLE
Search: facet options don't wrap well

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2938]
### Screenshot or Screencast

See that multiple lines of text aren't padded correctly, i'm guessing the row has a fixed height:
![Screenshot_2020-05-18 MIT Open Learning](https://user-images.githubusercontent.com/28598/82342568-c3bd7c80-99bf-11ea-981f-cb5c6aba1f27.png)

**Comment by aliceriot** [comment]
wondering about @abdulkdawson's opinion about what we should do in this case. there is an additional complication that there are some facets where they don't overflow normally but they *do* overflow when you hover over them, leading to a weird jumping feel.

for example:

![thingy](https://user-images.githubusercontent.com/6207644/83145471-d53f0c80-a0c2-11ea-8299-84e9e8e13e3a.png)
![thingy2](https://user-images.githubusercontent.com/6207644/83145478-d6703980-a0c2-11ea-839d-6481e7908ff4.png)

**Comment by aliceriot** [comment]
@Ferdi suggested we just clamp it to one line, like this:

![thingy23](https://user-images.githubusercontent.com/6207644/83299398-15d27f00-a1c4-11ea-8e96-5a23e4050f84.png)
