### ISSUE TITLE
Link URL validation requires http(s) prefix but placeholder omits it

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#297]
We should either change the validation or change the placeholder text so they match

**Comment by aliceriot** [comment]
@roberthouse54 what do you think about this?

**Comment by roberthouse54** [comment]
I do not know about whether it is important for some reason that links have http(s) prefix. So whether we should change the validation, I do not know. But yeah, if it is required the placeholder text should display "http://www.example.com" or something like that.

Does that answer the question?

**Comment by aliceriot** [comment]
yep :)
