### ISSUE TITLE
Podcasts: Episode Read More/Less Link Appears When Not Needed (and Remembers State)

### ISSUE THREAD

**Issue by briangrossman** [mitodl/open-discussions#3046]
### Steps to Reproduce
Note: This is a sneaky one...
1. Go to the Podcasts home page: [`https://open.mit.edu/podcasts/`](https://open.mit.edu/podcasts/)
2. Click on the `MIT Bootcamps` podcast (you'll need to scroll a little)
3. Click on the oldest episode in the drawer (`Deep Dive: Q&A Session 7 Working with Universities`)
4. ***Note*** that there is (appropriately) no `Read More` link because the description is short enough to be displayed
5. Click the arrow on the top-left of the drawer to return to the list of episodes for the drawer
6. Click on the 2nd oldest episode in the drawer (`Introduction to Deep Technology`)
7. ***Note*** that this episode requires the `Read More` link. Click it to view the full episode description.
8. Click the arrow on the top-left of the drawer to return to the list of episodes
9. Click on the oldest episode in the drawer (`Deep Dive: Q&A Session 7 Working with Universities`) again
10. Two things to ***note***:
   - The `Read Less` link is now present. It doesn't need to be because the description is so short. 
   - The link remembered its state. It says `Read Less`. In fact, if you go to another episode that actually requires the link, it will be in the fully expanded, `Read Less` state. It should default to `Read More` when you view new episodes.

### Screenshot or Screencast

![Screen Shot 2020-07-10 at 1 43 47 PM](https://user-images.githubusercontent.com/21342568/87184245-ab7a2780-c2b5-11ea-8d76-4ec0beb6c1a4.png)

**Comment by aliceriot** [comment]
that is a weird bug - I think I have an idea of what's going on, will try to dig into it
