### ISSUE TITLE
Don't spam check MIT users

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#3086]
We want to have the option of being able to exempt MIT users from spam checking. For the time being checking against `@mit.edu` emails should do the trick. This should also be behind a feature flag so that we can easily turn this on/off without a code change.

**Comment by mbertrand** [comment]
@rhysyngsun @pdpinch should this be configurable via something like the current `authentication.models.BlockedEmailRegex` model so that additional email addresses can be made exempt if necessary?  Or just hardcode the `.mit.edu` exemption for now?

**Comment by pdpinch** [comment]
I’d like it to be able to add additional email addresses (or partial addresses). 

I don’t have an opinion about the UI and data model. 

> @rhysyngsun <https://github.com/rhysyngsun> @pdpinch <https://github.com/pdpinch> should this be configurable via something like the current authentication.models.BlockedEmailRegex model so that additional email addresses can be made exempt if necessary? Or just hardcode the .mit.edu exemption for now?

**Comment by rhysyngsun** [comment]
@mbertrand I think long-term what we're probably going to want to have this permission-driven (e.g. a `can_post_without_spamcheck` permission) that's assigned to groups (e.g. we'd have an MIT group), but that's a huge lift here since we don't have any of that remotely in place. Maybe split the difference between that and hardcoding it and have a list of suffixes via environment variable w/ `["@mit.edu"]` as the default?

**Comment by mbertrand** [comment]
@rhysyngsun sounds good, I can start this afternoon unless you'd prefer to tackle it.

**Comment by rhysyngsun** [comment]
@mbertrand go ahead with it
