### ISSUE TITLE
Password reset flow works but appear to fail to the user

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#3095]
- On the password reset form, when you submit it display an error due to a 204 response, even though you still get the reset email.
- On clicking the link, the form submits and changes the password but nothing happens form the user perspective

**Comment by pdpinch** [comment]
There's a password reset form in Open? How do you get to it? 

Maybe I can't reach it with my user because my account was created through MM and/or Touchstone.

**Comment by rhysyngsun** [comment]
It's on the login page

**Comment by briangrossman** [comment]
Peter noticed this may have worsened. Here's a test case:

- Created a new user on Open: mit.odl.test+Open082420@gmail.com
- Logged out
- Went to log in page and clicked `Forgot your password?`
- Got an error: `Error resetting password`
![Screen Shot 2020-08-24 at 1 20 54 PM](https://user-images.githubusercontent.com/21342568/91076111-015c2200-e60d-11ea-9c21-cf25ae731a9e.png)
- Similar to above, I still received an email
- Clicked on the `Reset Password` link in the email
- Entered a new password and there was no feedback for the user. The browser reports a `400 Bad Request` and `Invalid token for user` in the response.
![Screen Shot 2020-08-24 at 1 21 58 PM](https://user-images.githubusercontent.com/21342568/91076479-93fcc100-e60d-11ea-8ca7-1083f4e42ead.png)
![Screen Shot 2020-08-24 at 1 22 06 PM](https://user-images.githubusercontent.com/21342568/91076488-9828de80-e60d-11ea-9721-795e827831dd.png)
