### ISSUE TITLE
API around SpamCheckResult

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#3100]
In cases where a post/comment is classified as spam and isn't and vice versa, we want to provide feedback to Akismet to hopefully it can get a little smarter about that in the future.

We should expose this as a new moderator-only API around the `channels.models.SpamCheckResult` model. _Don't_ overload the post/comment api with yet another mutable parameter please! It's easier to assert moderator permissions on an entire api rather than a field.

- Should be able to `GET` and individual spam report or a paginated (and ideally filterable by `content_type`) list of all of them.
- For a `POST` request, moderator should be able to change `is_spam` only, which would then:
  - If changing `is_spam` from `True` to `False`
    - Change the value in the record
    - In a celery task call to https://github.com/Nekmo/python-akismet#submit-ham
  - If changing `is_spam` from `False` to `True`
    - Change the value in the record
    - In a celery task call to https://github.com/Nekmo/python-akismet#submit-spam
  - Otherwise no changes

**Comment by briangrossman** [comment]
First step would be to create a management command for marking spam as ham or ham as spam. 

It would additionally be helpful to be able to `retire_user` and/or adding their email to the `Blocked email regexs` with an optional flag when marking a post / comment as spam.
