### ISSUE TITLE
Content policy link is broken

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#314]
Copy for the Content Guidelines is at https://docs.google.com/document/d/1gcTsTdYFggcTGTw5hZAR89UEP8_4phEBtxbMY0g2_HU

Design is below.

**Comment by pdpinch** [comment]
Needs copy and a (simple) design before it can be implemented.

**Comment by roberthouse54** [comment]
![screen shot 2017-11-07 at 4 12 47 pm](https://user-images.githubusercontent.com/20047260/32518086-90341f52-c3d6-11e7-98f9-005abbe13871.png)

**Comment by pdpinch** [comment]
Is that a modal?

Can we at least have a unique URL for it?

**Comment by roberthouse54** [comment]
That is not a modal. It is a page with a card on it. So we can have a URL.

**Comment by pdpinch** [comment]
I added a link to the copy and removed the blocked label. This is ready to be worked on.

**Comment by rhysyngsun** [comment]
Blocked pending corrections on the copy.

**Comment by rhysyngsun** [comment]
If someone other than me picks this up, I've already carved out a react page for this in a branch here: https://github.com/mitodl/open-discussions/tree/nl/content_policy

**Comment by rhysyngsun** [comment]
@roberthouse54 here's a screenshot of the page with the correct content, do you feel this needs anything beyond the current styling?

![localhost_8063_content_policy_](https://user-images.githubusercontent.com/28598/32955900-4cf6c1fc-cb85-11e7-8f47-30326db87d44.png)

**Comment by roberthouse54** [comment]
I think this looks ok. I may do a follow up PR to tweak the styles. The main thing is that I would make the page title smaller, with less padding above it.

**Comment by rhysyngsun** [comment]
Ok, I can actually fix the padding since I just noticed I inadvertently included a css class that's not relevant to this page.
