### ISSUE TITLE
Spam Mitigation: List post_id and comment_id rather than id for Posts and Comments in Spam check results in the admin

### ISSUE THREAD

**Issue by briangrossman** [mitodl/open-discussions#3166]
As an MIT Open site administrator, I'd like to know the `post_id` or `comment_id` of posts and comments marked as spam. I need these values to be able to report spam or ham. 

Currently, the admin displays the `id` field as `OBJECT ID`. Please change it to `post_id` for posts and `comment_id` for comments. 

#### Designs and Mockups

![image](https://user-images.githubusercontent.com/21342568/93802884-08794e80-fc12-11ea-9879-ff5ae3fa521c.png)

#### Acceptance Criteria:

- [ ] Update the admin to display `post_id` and `comment_id` rather than `id` field

**Comment by abeglova** [comment]
The management command will use the object ids for the posts/comments and report to Akismet automatically. Closing the issue

**Comment by briangrossman** [comment]
Thanks for clarifying. 
👍
