### ISSUE TITLE
Elasticsearch course results should not include unpublished runs, and runs should be in order.

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#3211]
### Steps to Reproduce

Search for "18.01"

### Expected Behavior

The top result will have 2 published runs in descending order by best_start_date.

### Actual Behavior

The top result will have 3 runs (2 published, 1 unpublished) and might not be in the above order.

**Comment by pdpinch** [comment]
@mbertrand I can't reproduce this on Open RC or Open Prod. However, I _do_ see something like the described behavior on ocwnext. 

i.e. in this screenshot from Open, the 2003 course doesn't show up in the "run" dropdown:

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/430126/98260172-ff89d580-1f50-11eb-95eb-1a6401098f0e.png">

but in this screenshot from OCW Next, the course card links to (a non-existent) 2003 run:

<img width="933" alt="image" src="https://user-images.githubusercontent.com/430126/98260328-32cc6480-1f51-11eb-9064-fea478c5d569.png">

**Comment by mbertrand** [comment]
@pdpinch you have to look at the raw result from Elasticsearch to notice it in open-discussions.  The course drawer does not use the ES result, it gets the data independently from the database and filters out the unpublished run there.   In ocw, the link to the course comes from the 1st run in the ES result, which should be the most recent run but sometimes is not.

**Comment by mbertrand** [comment]
@pdpinch PS instead of making changes to how open-discussions indexes course runs here, I could modify the ocw-nextgen frontend to find the most recent published run instead of just assuming the first run is the correct one, if you prefer.

**Comment by mbertrand** [comment]
I decided to address this on the OCW front end for now (https://github.com/mitodl/hugo-course-publisher/pull/305) but it might be good to fix this here as well eventually.
