### ISSUE TITLE
Each OCW run should be a distinct course

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#3243]
Currently, all OCW `LearningResourceRuns` with the same course number are grouped under the same `Course`.  Instead, each run should be treated as a separate course.  

- Write a function to split existing runs into separate courses and update the index.
- Modify the OCW import function to create 1 course per run.
- Modify the `course_id` of OCW courses to be a combination of run id and course number.

**Comment by pdpinch** [comment]
Do you think it’s better to update the index rather than recreate it? 
> Write a function to split existing runs into separate courses and update the index.

**Comment by mbertrand** [comment]
That's my initial thinking, since this involves a change in one subset of data (OCW courses/runs/resources) rather than a change in the Elasticsearch schema.  But I might change my mind depending on how it goes as I continue working on it.

**Comment by mbertrand** [comment]
Also, splitting existing runs into their own courses should be faster than deleting everything and reimporting them all from scratch.
