### ISSUE TITLE
last_active_on is not being updated in profiles

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#3266]
last_active_on is null for users with recent logins

**Comment by pdpinch** [comment]
Is that field visible to users anywhere?

**Comment by abeglova** [comment]
No it shouldn't be. I noticed that the field isn't being populated because  populate_notification_settings ignores inactive profiles based on that field

**Comment by abeglova** [comment]
Looks like that field is only used in `populate_notification_settings` . The functionality is also duplicated with `last_login` in the  Django user model. I made a pr to delete the field entirely.

**Comment by pdpinch** [comment]
Well, I found another dependency on this field. It was being used in a [BI report](https://bi.odl.mit.edu/queries/360/source#571). I'll have to see if the report can be changed to `auth_user.last_login`
