### ISSUE TITLE
There are about 30% fewer page views with the new g-tag

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#3335]
(Optional)

### Screenshot or Screencast

(Optional)

**Comment by abeglova** [comment]
All the extra pageviews are hits to the front page from Ashburn Virginia, so this is a script that gtag.js is filtering out.

**Comment by pdpinch** [comment]
Is there any other information available about these requests, like a user agent, browser or os?

**Comment by abeglova** [comment]
Here is the report filtered by location:
https://analytics.google.com/analytics/web/#/report/visitors-geo/a5145472w172515091p172027647/geo-table.plotKeys=%5B%5D&_r.drilldown=analytics.country:US,analytics.region:21178,analytics.city:1027028&geo-segmentExplorer.segmentId=analytics.city

**Comment by abeglova** [comment]
I clicked around the "Seconday Dimension". We don't get a user agent but looks like the os is Linux and browser is Safari
