### ISSUE TITLE
Missing feature links on CHP

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#3369]
### Steps to Reproduce

Compare [legacy 5.08J S16](https://ocw.mit.edu/courses/chemistry/5-08j-biological-chemistry-ii-spring-2016/) to [next gen 5.08J S16](https://ocwnext.odl.mit.edu/courses/5-08j-biological-chemistry-ii-spring-2016/)

### Expected Behavior

- [searching for "Biological Chemistry ii"](https://ocwnext.odl.mit.edu/search/?f=Recitation%20Videos&l=Undergraduate&q=%22biological%20chemistry%20ii%22) should include a result with the Lecture Videos Facet
- CHP should have icon and link for "lecture videos" 

### Actual Behavior

- No results [searching for "Biological Chemistry ii" with the "Lecture Videos" facet](https://ocwnext.odl.mit.edu/search/?f=Lecture%20Videos&q=%22biological%20chemistry%20ii%22)
- No icon, no link on the CHP

**Comment by abeglova** [comment]
The issue is that AV recitations and AV lectures are the same in the raw json for the run
```
   {
            "ocw_feature": "AV lectures", 
            "ocw_subfeature": "Video", 
            "ocw_feature_url": "/courses/chemistry/5-08j-biological-chemistry-ii-spring-2016/lecture-recitation-videos/index.htm", 
            "ocw_feature_notes": "", 
            "ocw_speciality": ""
        }, 
        {
            "ocw_feature": "AV recitations", 
            "ocw_subfeature": "", 
            "ocw_feature_url": "/courses/chemistry/5-08j-biological-chemistry-ii-spring-2016/lecture-recitation-videos/index.htm", 
            "ocw_feature_notes": "", 
            "ocw_speciality": ""
        }, 
```
And OCW data parser overwrites the feature tag if there are multiple tags to the same page (Lecture and Recitation Videos).

**Comment by abeglova** [comment]
The most straight forward fix to this is just listing the page twice in the "course_feature_tags" section of the master_json with the two seperate tags. If there are no changes in ocw-to-hugo, this will result in two links to the same page in the course "Course Features" section. I think that's probably what we want though
