### ISSUE TITLE
Support deleting course documents from index

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#3422]
Currently there isn't a mechanism for deleting course documents from the search index. We will support deleting course documents by adding a `published` field to ContentFiles and checking for no longer present files in the course import

**Comment by pdpinch** [comment]
Is this still relevant?

in particular, regarding issues like https://github.com/mitodl/ocw-studio/issues/1189

**Comment by abeglova** [comment]
This can be closed. We now have a published key for ContentFiles and unpublish remove missing ContentFile objects during course updates
