### ISSUE TITLE
Make OCW courses searchable and sortable by extra course numbers

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#3453]
"Biological Chemistry II" is listed primarily in in the Chemistry department as course 5.08J but is also crosslisted in the biology department as  7.08J
https://ocwnext-rc.odl.mit.edu/courses/5-08j-biological-chemistry-ii-spring-2016/

Searching for `5.08J` returns the course
https://ocwnext-rc.odl.mit.edu/search/?q=5.08j

But searching for `7.08J` does not
https://ocwnext-rc.odl.mit.edu/search/?q=7.08j

Also when you filter for `biological chemistry` and filter to the Biology department, the course is returned and sorted as 5.08J and not 7.08J
https://ocwnext-rc.odl.mit.edu/search/?d=Biology&q=biological%20chemistry

We want the course to be searchable as `7.08J` and be sorted as `7.08J` in the search results when Biology is selected as the department.

**Comment by pdpinch** [comment]
related issue: https://github.com/mitodl/open-discussions/issues/3381

**Comment by pdpinch** [comment]
Scratch that. They are two different data sources.

**Comment by abeglova** [comment]
https://docs.google.com/document/d/e/2PACX-1vTY2NedCSD6PYQxFGROX--1DQUmZbhWxpbklDbDfAKS7SMtnpJtjLmTx8AEnHL0fV4LUiq9gRGCPa9U/pub
