### ISSUE TITLE
Add importer code for ocw-next resources 

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#3486]
The ocw importer will look through the entries in course_resourse_data.json from each course’s folder in the ocw-content-live-<env> bucket on s3 and import the resources.
Again, we can largely reuse existing code for creating ContentFile objects from ocw resources, parsing the content of text resources with tika, and importing them into elasticsearch. Again, we need to be mindful about how often we reindex, so while we are still republishing all courses multiple times a week, this should be a periodic task.

**Comment by pdpinch** [comment]
@abeglova we have a feature enhancement that I think should be easy to include with this issue. 

Currently, file-type resources in search results link directly to the file. Instead, they should be linking to the HTML container for the file. For example, in [this search](https://ocwnext.odl.mit.edu/search/?q=problem%20set%201&type=resourcefile), the first result links to:

https://open-learning-course-data-production.s3.amazonaws.com/hst-950j-medical-computing-spring-2003/2c53f7d4941f1e6a83888b053fb50f80_assignment1.pdf

when it should link to:

https://ocwnext.odl.mit.edu/courses/hst-950j-medical-computing-spring-2003/resources/assignment1/
