### ISSUE TITLE
Upgrade postgres to 12.x

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#3488]
> We just got a notification from AWS that we're still running Postgres 9.6 for both Reddit and the open app and they're going to upgrade us to >=12.x on the 18th whether we like it or not.

#### Acceptance Criteria:

- [ ] #3490
- [x] If there are no breaking changes, deploy to RC (heroku) 
- [x] snapshot and update RC (heroku) to 12.x (@mitodl/devops) 
- [x] snapshot and update reddit-rc to user 12.x 
- [x] Test on RC
   - [x] Mark a post (all kinds) 
   - [x]  upvote / downvote
   - [x] make a comment 
   - [ ] create a channel
   - [x] create a user from MicroMasters
   - [x] create a user from open 
   - [x] search on new created posts and comments 
   - [x] test course ingestion, especially OCW courses 
- [x] deploy to prod
- [x] snapshot and update Heroku  postgres on prod
- [x] snapshot and update reddit postgres on prod

**Comment by pdpinch** [comment]
We started getting this error in Sentry, soon after we upgraded the Reddit db on RC: https://sentry.io/organizations/mit-office-of-digital-learning/issues/669606987/?project=216201&referrer=slack

**Comment by briangrossman** [comment]
This was just published to prod. Did some quick testing and things seem to be behaving properly. 

- [ ] Mark a post (all kinds)
- [ ] upvote / downvote
- [ ] make a comment
- [ ] create a channel
- [ ] create a user from open
- [ ] search on new created posts and comments

**Comment by pdpinch** [comment]
So we did everything except update the development environment. There's a separate issue for that now, so I think it's safe to close this.
