### ISSUE TITLE
Search: display instructors' full name

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#3524]
Instructors sometimes have middle names, which should display on the search results card. 

For example, on this [CHP](https://ocwnext.odl.mit.edu/courses/11-139-the-city-in-film-spring-2015/) the instructor's name is "Ezra Haber Glenn" but in [this search result](https://ocwnext.odl.mit.edu/search/?q=11.139) it only displays "Ezra Glenn" 

<img width="627" alt="image" src="https://user-images.githubusercontent.com/430126/155718570-b92aac48-c25a-4f01-9877-6ba48b9a60cc.png">

**Comment by MAbdurrehman12** [comment]
> Do you still want to work on it?

Yeah, I'm in the middle to setting up this repo locally, currently having some issues with starting the `db service` locally
