### ISSUE TITLE
get ocw departments from the departments array and not course numbers

### ISSUE THREAD

**Issue by abeglova** [mitodl/open-discussions#3550]
In ocw-studio you can set “Department Numbers” in the metadata page. Open-discussions currently ignores those “Department Numbers” when importing courses into search and instead extracts the department numbers from the course numbers.

CMS-W courses have course numbers that start with 21w. 21w isn’t a key in the dictionary that matches department numbers to department name so these courses are imported into search with no department.

The “departments” array for these courses correctly includes CMS-W and should be matched to Comparative Media Studies/Writing by search if we use that for the departments instead of parsing department numbers from the course number

**Comment by pdpinch** [comment]
I don't think we should merge this until we fix https://github.com/mitodl/ocw-studio/issues/1247
