### ISSUE TITLE
Remove max comment depth

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#361]
After comment pagination is merged this won't be needed anymore

**Comment by rhysyngsun** [comment]
Are we sure about this? I'm not sure the UI can handle unbounded comment depth style-wise. I think there was also sentiment that deeply nested discussions weren't of huge value so this had a positive limiting effect in that regard.

**Comment by noisecapella** [comment]
Right, I forgot about the UI aspect of this
