### ISSUE TITLE
Infinite Corridor Front Page, round 2

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-discussions#3630]
#### Designs and Mockups

https://projects.invisionapp.com/share/EZ12VH612GP8#/screens

#### Acceptance Criteria:

- [ ] Header at top
- [ ] Styling, including: center input, horizontal link list, etc
- [ ] icon/thumbnail should show up in with the links to fields

#### Out of Scope

- Designing those neat icons.

**Comment by pdpinch** [comment]
And this one?
