### ISSUE TITLE
Field Pages basic layout

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-discussions#3642]
Focus is on the overall layout... Course cards / rows will be revisited.

#### Designs and Mockups

_Marked up from https://projects.invisionapp.com/d/main#/console/22082155/468413145/preview_

<img width="1865" alt="field_pages" src="https://user-images.githubusercontent.com/9010790/179837439-90913dfe-5bc1-4b88-b31b-1b3a66b86899.png">

#### Acceptance Criteria:

- [ ] Fields page should match mocks above

#### Out of Scope

- Course cards / course rows ... *These can probably be brought over from open-discussions, or perhaps have been already by @abeglova ... either way, I'll revisit them.*
- Any new API stuff

**Comment by ChristopherChudzicki** [comment]
@pdpinch I left a few questions on the mocks above... Are the answers known yet? We may have discussed (2)... I can't remember exactly and the google docs notes are a bit sparse.

**Comment by pdpinch** [comment]
- Let's drop the search icon for now. That's a holdover from the channel UI, where it allows searching within the channel. I don't think we have much use for that idea at the moment. 
- From a user perspective, "Ethics" is a subfield. You need to check with @mbertrand to see where that comes from in the data model.

**Comment by ChristopherChudzicki** [comment]
Closed by #3654
