### ISSUE TITLE
Channel description is not showing up in about panel

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#365]

**Comment by pdpinch** [comment]
Can you be more explicit? I'm seeing what I expect on, for instance, https://discussions-rc.odl.mit.edu/channel/dedp

We decided not to use the description that is set in the MM create channel form. Instead we're using the sidebar (I think? @rhysyngsun ). At the moment I manually set the data, but Nathan is working on the UI.

**Comment by noisecapella** [comment]
Right, I forgot that there were two descriptions. I was editing the other one locally

**Comment by rhysyngsun** [comment]
Yup, it's using the correct field (what reddit UI refers to as the sidebar text). We should probably update MM and the client lib to use the correct field.
