### ISSUE TITLE
Infinite Corridor, styling changes

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-discussions#3672]
A list of styling tweaks / feedback on initial infinite-corridor implementation:

- [x] fix searchbar styling
- [x] (mostly done, see below) make colors match open discussions

Remaining Tweaks https://mitodl.slack.com/archives/C03K5HYGPT9/p1659728393670959
- [ ] Square next/previous buttons like `learn/`
- [ ] Use the dark blue font from open-discussions for cards (not the black font from learn + infinite designs)

**Comment by ChristopherChudzicki** [comment]
@Ferdi or @pdpinch a few questions, some of which may be related to differences in styling between open-discussions and the infinite corridor initial designs:

1. Where should the Biology field title link? _second screenshot above_
2. Re the background annotation (_second screenshot above_)
    - Do we want a gray background like the rest of the page, similar to the initial designs (https://projects.invisionapp.com/d/main#/console/22082155/468413145/preview)
    - or a white background similar to channel pages? (https://open.mit.edu/c/ocwchalkradio)
3. Similarly, there are some differences in font between the Infinite Corridor designs and the Open Discussions [style guide](https://projects.invisionapp.com/share/9SN8J0LPTQ2#/screens/311486535_Home_Logged_Style_Guide):
    - The infinite corridor designs use a gray background vs the blueish background in open-discussions.
    - The "default font" in the open-discussions is also blue (#03152d) vs black in Infinite Corridor.

Re (3) the colors are of course easy to change (controlled by scss variables). For now, I'm going stick with the Infinite Corridor designs for colors but use the Open Discussions style guide that @ferdi linked me for font-sizes and font faces.

**Comment by Ferdi** [comment]
@ChristopherChudzicki when in doubt , try to match open-discussion.   We wanted to keep stying the same. The differences are probably the designer missing some details.
