### ISSUE TITLE
Bundle size is unnecessarily big (open discussions, infinite corridor)

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-discussions#3714]
The bundle sizes for infinite-corridor and open-discussions have both jumped considerably recently. For example, `[@fakerjs/faker](https://www.npmjs.com/package/@faker-js/faker)` is bloating both bundles by `2.6M`  even though we only use it for tests.

**Comment by Shinigami92** [comment]
I had a look into your repo via https://github.com/mitodl/open-discussions/search?p=1&q=faker
Looks like `lorem` is the only API that calls localized values, but even there you take the default faker instance without changing the locale to non-"en"
So I would highly recommend for now to use `import { faker } from "@faker-js/faker/locale/en"` to reduce the faker instance from around 4mb to 600kb

For later things please subscribe to: https://github.com/faker-js/faker/issues/1340 and https://github.com/faker-js/faker/issues/1351
You might be specially interested in the `BaseFaker` we want to introduce

**Comment by ChristopherChudzicki** [comment]
@Shinigami92 Thanks for taking a look, and your work on faker! Interested to follow those issue, especially new module structure. Since it's a dependency we only use in development, the size of faker doesn't really worry me, it's the fact that it was included in our production build at all. (Which is easy for us to avoid with some simple changes to our local modules.)

**Comment by ChristopherChudzicki** [comment]
Closing this for now ; #3725 did a lot. More could be done, of course.
