### ISSUE TITLE
Infinite-corridor field pages don't handle 404 errors from the API

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#3759]
### Steps to Reproduce

Go to a field page url that doesn't exist, for example ../infinite/fields/fakefield/

### Expected Behavior

404 message
robots=noindex meta tag in header

### Actual Behavior

No 404 message, no robots meta tag

### Related Issues
#3752
#3757

**Comment by ChristopherChudzicki** [comment]
I'm going to close this in favor of #3865
