### ISSUE TITLE
Run user profiles through spam filtering

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#3799]
User profiles are another place where users can input arbitrary text and have it show up, so we need to start spam filtering these. At a minimum we're talking the headline and bio. If spam filtering fails or the check cannot be made, reject the update.

**Comment by pdpinch** [comment]
According to [this BI query](https://bi.odl.mit.edu/queries/1221), we have >1000 spammy profiles created since February 2023. We should retire these user accounts.

**Comment by pdpinch** [comment]
@rhysyngsun can we close this?
