### ISSUE TITLE
Index .srt transcript files (and more?) from edx

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#3840]
As a search indexer, I'd like to include .srt transcript files in the index.

#### Designs and Mockups
Add `.srt` to the list of valid text files:

```python
VALID_TEXT_FILE_TYPES = [
    ".pdf",
    ".htm",
    ".html",
    ".txt",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".ppt",
    ".pptx",
    ".xml",
    ".json",
    ".rtf",
    ".ps",
]
```

#### Acceptance Criteria:

- [ ] .srt files are indexed for MITX Online, MITx, xPro, and OLL (after running the `backpopulate_<platform>_files` command for each)
- [ ] Searching for "which is valid for Stokes flows" (included in an srt file for MITx Online run 10.50.CH02x+1T2023) should return that course

**Comment by pdpinch** [comment]
brainstorming a bit on other file types:

- .csv
- .py
- .m (matlab code) 
- .mat (matlab code?) 
- .r
- .md
- .sjson (.sjson is a legacy format for video captions, unique to open edX)

Does Apache Tika do anything with image files? There are a lot of .png, .gif, .svg, .tiff, .jpg, and .jpeg

I built this list from some course exports I happened to have on my computer. To be exhaustive, we would have to do a survey of the static files in xPRO, mitxonline and Residential MITx.

**Comment by JenniWhitman** [comment]
According to the site, the ImageParser class can get metadata from PNG, GIF, BMP and there's also classes for jpeg(JpegParser) tiffs (TiffParser) bpg (BPGParser) PSD (PSDParser) - all of these look like they grab metadata. That would be simplest grab from image files.

They DO mention that there IS an OCR parser if we wanted to grab text from images (TesseractOCRParser). It requires installation and running of tesseract-ocr which is open source (https://github.com/tesseract-ocr/tesseract).
