### ISSUE TITLE
Article editor in New Open

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-discussions#3853]
The article editor (https://discussions-rc.odl.mit.edu/create_post/  --> create article) should be available in "new open" pages. 

### Acceptance Criteria
- [x] Article editor available in new open.
- [x] CKEditor should only be loaded where used (for article editor and widgets).

**Comment by ChristopherChudzicki** [comment]
The "Article Editor" on https://discussions-rc.odl.mit.edu/create_post/ consists of three parts— a **title**, **cover image**, and a **body**.

I've been focusing on the **body editor** for this issue.

@Ferdi The old editor uses two toolbars, one top toolbar and one floating toolbar:
<img width="600" alt="original_article_editor_annotated" src="https://github.com/mitodl/open-discussions/assets/9010790/df748e85-ba24-4225-8d25-3e07248d1151">

This seems a little unusual to me (e.g., it's not clear how to insert an image; I originally did not realize the paragraph icon was a clickable button).

**Question** would we prefer a single top toolbar? (no floating toolbar)

Second: We've talked about using HTML output which seems best to me (and is the CKEDitor default). The old article editor uses a JSON output because that's what Reddit expects. I want to mention that I don't think we currently have any database models that would expect the HTML output, so we may not have anywhere to show / demo the editor aside from a "test page" like this:

<img width="998" alt="Screenshot 2023-06-13 at 3 27 44 PM" src="https://github.com/mitodl/open-discussions/assets/9010790/653be00d-a439-4e5f-8c7b-55d3b2336b35">

**Comment by Ferdi** [comment]
> The old editor uses two toolbars, one top toolbar and one floating toolbar

Originally this was inspired by linkedin + medium 
https://www.linkedin.com/post/new/
https://medium.com/new-story

> we may not have anywhere to show / demo the editor aside from a "test page" like this

Ok , we need to add/update the models

**Comment by pdpinch** [comment]
@ChristopherChudzicki what's the status of this?

**Comment by ChristopherChudzicki** [comment]
I would say this issue is resolved via
- https://github.com/mitodl/mit-open/issues/160
- https://github.com/mitodl/mit-open/issues/139
- https://github.com/mitodl/mit-open/issues/109

and a few other related issues in MIT Open repo.

I'm sure we'll do more work on it at some point, but this issue was meant for a first iteration in open-discussions.
