### ISSUE TITLE
Flaky frontend test

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-discussions#3863]
Sometimes an old `/learn` test fails ([example](https://github.com/mitodl/open-discussions/actions/runs/4375294331/jobs/7655831329#step:13:3016)).

> AssertionError: expected 'September 06, 2000' to equal 'September 6, 2000'

But only when the random test data has a date with day 1-9 and only when the `start_date` actually shows on resource cards. (I suspect the start date rarely showed prior to https://github.com/mitodl/open-discussions/pull/3850, which is why we hadn't noticed this much.)

**Comment by JenniWhitman** [comment]
@ChristopherChudzicki is this failing the same test: https://github.com/mitodl/open-discussions/actions/runs/4747252982/attempts/1

**Comment by ChristopherChudzicki** [comment]
@JenniWhitman Good reminder though, I meant to close this after https://github.com/mitodl/open-discussions/pull/3869
