### ISSUE TITLE
API updates for new open

### ISSUE THREAD

**Issue by JenniWhitman** [mitodl/open-discussions#3868]
As a developer, I'd like to be able to search using API with new filters (split out from #3847 ):

- upcoming courses
- courses with certificate
- micromasters courses
- professional ed courses

#### Designs and Mockups

Updating the current course_catalog api to include those filters makes the most sense for a forward facing API & consistent calls that are going to be made often and without needing the power of the /search api to pull results (aka infinite). Adding the filters through django-filters which should translate nicely into openAPI spec.

Will have 4 new available filters:
- **Certificate** - which uses the same logic from the certificates property, to filter down by courses offering certificates (and those that are not). My plan here is for this to be a boolean field, question in comments for discussion.
- **Upcoming** - Currently this is handled in a separate view which overwrites any filtering because of how it calls the queryset - meaning it can not be combined with other filters (such as the ones we are adding). It is also a different format than the other filters and will not make as much sense in documentation unless added to the filterset with the rest. I'm proposing we add it as a keyword argument here, and leave the other views out of any documentation or public facing API as they're both confusing and not all filters (new, for example, is a sort). This just means adding it to the filterset using the existing logic.
- **Audience** - filter courses by whether they are professional or open, matching the[ current model property](https://github.com/mitodl/open-discussions/blob/72cbb98c8dfb0d7cec98004d4b2ad382414c5307/course_catalog/models.py#L312)
- **offered_by** - filter courses by who/what they are offered by

#### Acceptance Criteria:

- [ ] filterable by upcoming courses (can easily also translate this into past and ongoing filters as well)
- [ ] filterable by courses with certificate
- [x] filterable by micromasters courses
- [x] filterable by professional ed courses

#### Out of Scope

- Not going to add the docs aspect now (unless we want a demo, it's only a few lines to generate a swagger or redoc example quickly)
- Not going to add other filters for now

**Comment by JenniWhitman** [comment]
- micromasters and profesional ed are being solved by #3877 
- upcoming (also new and featured) and certificate will be in the next PR

**Comment by JenniWhitman** [comment]
@Ferdi @pdpinch  there's a couple points of discussion clarification here - let me know if i can make them more clear, but tried to italicize the actual questions/plan themselves. 

For certificates - _my one question/discussion point is whether there is actually a reason for this not to be a boolean field_ - there is the possibility, [the way that the property is written](https://github.com/mitodl/open-discussions/blob/72cbb98c8dfb0d7cec98004d4b2ad382414c5307/course_catalog/models.py#L320), that it could allow for further filtering since it's a list of strings, but for now it only displays one string there, and would be easy/make the most sense from my perspective to filter as boolean. Calling this out in case I'm missing context.  

For upcoming - presently there are 3 views that are adjacent - [upcoming, new, and featured](https://github.com/mitodl/open-discussions/blob/72cbb98c8dfb0d7cec98004d4b2ad382414c5307/course_catalog/views.py#L188). These are inflexible and do not allow for filtering and also will be formatted differently (separate url views instead of parameters as the rest are).  The way they are written will also place them differently in documentation. None of these are a huge deal, but _I'm proposing we add upcoming to the filterset we're using for the rest of the filters in this ticket rather than attempt to modify the current Upcoming view._  This also offers the question of whether we want to add sorting for "new" as a part of this issue or the featured filter (which is based off a featured boolean value that I'm not quite sure of its use.

The above issue description has been updated to reflect this.

**Comment by pdpinch** [comment]
=
