### ISSUE TITLE
Moderator view of reported posts and comments

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#388]
As a channel moderator, I need to see a list of all posts and comments that been reported by learners for violating the guidelines, so I can review and act on them.

**Comment by rhysyngsun** [comment]
Here's reddit's interface for reporting on these:

![selection_109](https://user-images.githubusercontent.com/28598/33783387-8d031042-dc2a-11e7-8104-0d29350b67ca.png)

- "spam" - removes the content and marks it as spam in order to train their spam filter. I'm not sure if this does anything in the open sourced version of reddit
- "remove" - regular removal of content
- "reapprove" - acknowledges the report, but approves the content
- "ignore reports" - acknowledges and ignores future reports

**Comment by pdpinch** [comment]
What does it mean to acknowledge the report? Does that just remove it from this list?

**Comment by pdpinch** [comment]
Also, I know we have an API for remove. Are there PRAW APIs for the other actions?

**Comment by rhysyngsun** [comment]
There are APIs for all those. I believe "reapprove" helps train the spam filter too, "ignore reports" may only ignore them for the current user based on some anecdotal knowledge I've found.

**Comment by rhysyngsun** [comment]
The ignore reports button will require #427

**Comment by roberthouse54** [comment]
We will show the same UI both on the Reports page, and on the regular channel page and post page for any posts or comments that have been reported. We should use the same react component that we use for comments (on a post page) and posts (on a channel page).

We have decided to only have "Remove" and "Ignore All Reports" (which means this and all future reports).

We should show a standard confirmation modal if the admin clicks "Remove".


Reported Posts/Comments page

![image](https://user-images.githubusercontent.com/20047260/34891368-555d3192-f7a3-11e7-924b-cd328cfe267b.png)

A Post Detail page showing a reported comment:

![image](https://user-images.githubusercontent.com/20047260/34891403-78e3033a-f7a3-11e7-8b3c-670fd6c42dde.png)

Remove Post confirmation:
![image](https://user-images.githubusercontent.com/20047260/34891507-d6145324-f7a3-11e7-83e9-2e657f805686.png)

**Comment by rhysyngsun** [comment]
@roberthouse54 @pdpinch the display of the report counts on the channel/post pages for posts/comments will require additional API work, I suggest we split those out to separate tickets

**Comment by pdpinch** [comment]
Can you open an issue for [this](https://github.com/mitodl/open-discussions/issues/388#issuecomment-357345413) so I can understand the scope?

**Comment by rhysyngsun** [comment]
@pdpinch I opened #432 for this, I wouldn't expect it to be too substantial work.

**Comment by rhysyngsun** [comment]
Also, we probably want to keep an eye on those action link layouts - we're building up quite a number of them and I'm not sure how well our current styles will support that.

**Comment by Ferdi** [comment]
@rhysyngsun 

> Also, we probably want to keep an eye on those action link layouts - we're building up quite a number > of them and I'm not sure how well our current styles will support that.

Can you elaborate ?

**Comment by Ferdi** [comment]
@rhysyngsun good point, thx !

**Comment by rhysyngsun** [comment]
To ignore reports on the post/comment `PATCH` the comment/post endpoint with `{"ignore_reports": true}`
