### ISSUE TITLE
User requesting a channel without permission raises a 403 error on moderator API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#393]
This doesn't affect user experience, but leads to an error in Sentry.

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/discussions/issues/414360677/

**Comment by rhysyngsun** [comment]
This is related to and probably fixed with the same code as #408

**Comment by aliceriot** [comment]
yeah I think my PR for #408 addresses this too

**Comment by aliceriot** [comment]
#422

**Comment by pdpinch** [comment]
Re-opening because this happened again (2 events, both the same user):

https://sentry.io/mit-office-of-digital-learning/discussions/issues/414360677/events/13942695900/

**Comment by aliceriot** [comment]
hm it looks from the thingy like this is happening on the post page, and not on the channel page. I can try to refactor the `loadData` function so it won't do this anymore (i.e. so it will only fetch moderators if the post request comes back ok)
