### ISSUE TITLE
Split up more settings into multiple files

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#3939]
As @JenniWhitman pointed out, the `settings.py` file is nearly at the limit of 1000 lines where pylint will start complaining.  The settings for drf-spectacular have already been placed in a separate settings file, we should do the same for more.  A good candidate to start with might be the settings used for course ETL (`MITX_ONLINE_*`, `XPRO_*`, `EDX_*`, `OCW_*`).

**Comment by JenniWhitman** [comment]
I like the idea of the ETL settings - I haven't gone through extensively, but any large LOGICAL pieces we can chunk out I'm all for making space.
