### ISSUE TITLE
API for getting a list of reported comments and submissions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#398]
Based on the PRAW `reports` API:

http://praw.readthedocs.io/en/latest/code_overview/other/subredditmoderation.html#praw.models.reddit.subreddit.SubredditModeration.reports

Questions:

- [x] The `reports` API this can return posts and/or comments. When both are returned, what is the data structure?

**Comment by rhysyngsun** [comment]
The API returns a mixed list of `Submission` and `Comment` objects
