### ISSUE TITLE
Use React 18 in new frontend pages of Open

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/open-discussions#3990]
Currently, we use React 16.14 in all Open frontend bundles: both the old (js+flow) and new (typescript) sections. Because the "old" and "new" portions of Open are separate bundle with separate entrypoints, we can use different React versions.

I would like to suggest that we use React 18 (the current major version, released in March 2022) in the new portions of Open. 
There are no amazing new features that immediately benefit us. However:
- There are **some** improvements that might be beneficial. E.g., React now batches state updates that occur asynchronously (like as the result of an API call or from an event handler) => fewer unnecessary rerenders.
- Several improvements to server-side rendering with React[^1]. We do not currently pursue SSR, but if we ever go down that path (for example, by using NextJS) it would be useful to use React 18. *NextJS [suggests](https://nextjs.org/docs/messages/react-version) using React 18.2 at a minimum.*

I suggest updating React now because, in general, I think it's easier to update early (when the project is smaller) than to update later when it has grown.

[^1]: One example of improved SSR is: In React 16/17, an entire page had to be rendered on the server. Now you can selectively render portions of the page on the server. So, e.g., if `/search` page is slow to load, you could send the HTML for everything except search results immediately,  then send the data when it is ready

**Comment by ChristopherChudzicki** [comment]
We decided not to use React 18 for Infinite Corridor initially because we were sharing packages like `ol-util` and `ol-forms` between the "new" and "old" frontends. We did not want to deal with ensuring the shared packages would work with both versions. Since we no longer share packages between old and new, this is no longer an issue.

**Comment by rhysyngsun** [comment]
I think this is a good idea - the only other reason we've held back historically on React upgrades past 16 was `enzyme`'s nonexistent support for higher React versions and we don't use that library the new infinite code.
