### ISSUE TITLE
Centralize documentation for installation

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#41]
We currently have some of this information in this README, some information in `reddit-config` and some in `reddit` itself (for example setting up `reddit.local` in `/etc/hosts`). We should put all of this in a `Getting Started` section at the top of this README

**Comment by aliceriot** [comment]
The documentation related to docker on OSX included in this README also doesn't seem to be specific to open-discusssions (looks like it was copied from MM). It would be good to also pull that out to one place, so that for each repo (mm, open-discussions, mit-open, etc) we had only the information specific to that repo in the README.

**Comment by pdpinch** [comment]
@gsidebo how much of this did you already do?

**Comment by pdpinch** [comment]
@gsidebo @aliceriot @noisecapella is this still an issue?

**Comment by gsidebo** [comment]
It's half done, as it is for every other docker/django/webpack project we have. The common guide is written (https://github.com/mitodl/handbook/blob/master/common-web-app-guide.md) but the corresponding `README` files in each individual repo (including this one) have not been updated

**Comment by gsidebo** [comment]
I'll try to carve out some time before I sign off today to do that work for this repo (or, if necessary, a different repo that I'm more familiar with)

**Comment by pdpinch** [comment]
What remains to be done here?

**Comment by gsidebo** [comment]
Basically everything for this repo. Documentation has been update w/ reference to the common web app guide for Micromasters and I think one other repo
