### ISSUE TITLE
Snackbar message sometimes sticks around

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#443]
I'm noticing the snackbar message is sticking around indefinitely:
![screenshot from 2018-01-22 10-46-44](https://user-images.githubusercontent.com/863262/35229506-98f6a850-ff61-11e7-9c3e-e3264064cb1b.png)

To reproduce I reported the same post twice in a row

**Comment by mbertrand** [comment]
This might be fixed already?  Reported posts/comments multiple times but was unable to reproduce.  Also tried adding & removing moderators.

**Comment by pdpinch** [comment]
I'm closing this. If we find it again, we can re-open.
