### ISSUE TITLE
Add profile model to map reddit username to django user

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#45]
We should change the code to generate unique reddit usernames and to map this username to the `User` model and a `Profile` model to store extra data which we need for the UI

**Comment by aliceriot** [comment]
Does `Profile` store the reddit username as well? To me it might make more sense semantically for the django user <-> reddit username correspondance to live on a different model, called like `RedditUser` or `RedditUserInfo` or something similar. Is `Profile` just going to store the first + last name, profile image, that kind of stuff?

**Comment by noisecapella** [comment]
Yes, `RedditUserInfo` sounds good to me

**Comment by pdpinch** [comment]
@noisecapella @rhysyngsun is this still a relevant issue?

**Comment by noisecapella** [comment]
No, this is done. The mapping is in micromasters, using `DiscussionUser`
