### ISSUE TITLE
Mail: Manage Open Discussion Email Preferences

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#451]
As a learner, I want an quick and easy way to unsubscribe from unwanted emails. Or edit my preferences as to how often I want to receive emails.

This shouldn't require logging in, so the URL embedded in the email needs to include a enctryped token containing enough information for unsubscribing, i.e. the email address and a reference ot the list for unsubscribing.

Since the settings component will be accessible with and without authentication, it may require two different templates and two different endpoints.

**Comment by roberthouse54** [comment]
In Open Discussions we will add an Settings page, where one of the options will be to allow users to update their preferences for how often they want to receive the Discussion Digest emails. There will be a link to "Settings" in the Discussions sidenav. 

Any emails that are sent to users will have a link to "Unsubscribe." Clicking that link will take users to a logged out version of this page where they will be able to update their preferences without logging in.

After clicking save we will show a standard Snackbar confirmation message that says "Your settings have been updated."

![image](https://user-images.githubusercontent.com/20047260/35813504-c6bd6746-0a61-11e8-922e-30ad00e6fbdf.png)

![image](https://user-images.githubusercontent.com/20047260/35813541-e0ee6a20-0a61-11e8-8064-41ab5447e26b.png)

**Comment by aliceriot** [comment]
To implement the design for this we're going to need the material radio component (see here: https://material.io/components/web/catalog/input-controls/radio-buttons/)

I'm working on adding that to our mdl-react-components package to start off (since I can't do much work on the UI until the backend stuff is in place anyhow).
