### ISSUE TITLE
Analytics: basic BI dashboard for discussions.odl.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#452]
As a member of the micromasters team, I'd like to be able to get a high-level view of discussions analytics. 

Just the basics:

- [ ] count of channels
- [ ] count of posts
- [ ] count of comments

**Comment by maxliu** [comment]
A draft version. https://bi.odl.mit.edu/dashboard/discussions-analytics

**Comment by pdpinch** [comment]
Thanks Max. This looks good to me.
