### ISSUE TITLE
weekly task for digest email

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#460]
### acceptance criteria
For weekly subscribers, we will:
- [ ] take the user's front-page feed
- [ ] sort by top posts
- [ ] filter out any posts more than a week old
- [ ] take the first `n` posts, where n is set in a feature flag

### out of scope
- ideally, the mail would be sent an appropriate time for the user's time zone (i.e. local morning)
- in the future, we might like to do some A/B testing about when this task is run. Currently, it looks like Tuesdays at 10am is recommended as the default

**Comment by rhysyngsun** [comment]
Which day of the week do we want to send these?

**Comment by pdpinch** [comment]
IIRC, someone found some research that said that Tuesday is the best day (at least, until we allow users to set their own preferred day)
