### ISSUE TITLE
daily task for digest email

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#461]
### acceptance criteria
For daily subscribers, we will:
- [x] take the user's front-page feed
- [x] sort by hot posts
- [ ] filter out any posts more than 24 hours old
- [ ] take the first `n` posts, where n is set in a feature flag
- [ ] For our convenience, we can start this task at 10am every morning. 

### out of scope
- ideally, the mail would be sent an appropriate time for the user's time zone (i.e. local morning).

**Comment by rhysyngsun** [comment]
For this, is it reasonable to only search through items on the first page of the user's frontpage?

**Comment by pdpinch** [comment]
How big is a page? 25 posts? 50 posts?

I don't think it's likely we will get more than a page's worth of new posts each day, so limit the search to the first page seems OK. 

If there are more than a page's worth, or if hot posts are pushing new posts to the 2nd page, then I think those are the posts less worth notifying users about. 

> is it reasonable to only search through items on the first page of the user's frontpage?

**Comment by rhysyngsun** [comment]
I think it's 25 right now.
