### ISSUE TITLE
Mail: button for follow / unfollow (or subscribe / unsubscribe)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#469]
As a user, I need a simple way to follow a post or a comment, be able to see my following status, and be able to unfollow a post/comment. 

This button should be behind a feature flag until we have the rest of the "follow" epic ready for release.

**Comment by roberthouse54** [comment]
Following/Unfollowing a Post

![image](https://user-images.githubusercontent.com/20047260/36693323-ef14f062-1b08-11e8-9ab1-10865e899c59.png)

Following a Comment
![image](https://user-images.githubusercontent.com/20047260/36693371-0b28c684-1b09-11e8-8606-dd77d636a21d.png)

When the user either follows or unfollows a comment or post, we should display a snackbar confirmation message. ("You are now [following/unfollowing] this [post/comment].")
