### ISSUE TITLE
Mail: template for new comment notifications

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#470]
The email should include the body of the comment and a link to the comments *parent*. If the comment is a top-level comment, then we can simply link to the comment itself. 

Since users may be tempted to reply by e-mail, we will set the reply address to no-reply@discussions.odl.mit.edu (the current reply address)

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/36695361-123faf9a-1b0f-11e8-8f8a-61f06d4b65c0.png)

**If the comment is on a post the copy will be:**

"You have 1 new comment on your post:"
"Comment from [username]"

**If the comment is a reply to your comment, the copy will be:**

"You have 1 new reply on your comment:"
"Comment reply from [username]"

**Comment by rhysyngsun** [comment]
@pdpinch / @roberthouse54 should these email strip markdown formatting form the post/comment text?

**Comment by roberthouse54** [comment]
I think probably yes. It will keep things simpler. And it is difficult to know whether markdown will render correctly in email clients.

**Comment by rhysyngsun** [comment]
Ok, will do.

Another thing I just realized is we'll be sending this same email to everyone who is subscribed to a given post or comment so the "your post|comment" language might be confusing for anyone who isn't the author of that.

**Comment by roberthouse54** [comment]
There is a slight modification to the design of this. See below.

The notifications for a reply to a post vs. a reply to a comment are slightly different. The main difference is that we are truncating the text of the comment that is being replied to (at top), because it can get long. In the case of a post, just show the whole post title.

![image](https://user-images.githubusercontent.com/20047260/38331042-28a5be90-3820-11e8-8179-9fc83467cc01.png)

**Comment by roberthouse54** [comment]
Another change to the design, making it simpler. (See mock below)

![image](https://user-images.githubusercontent.com/20047260/38381868-28aa2712-38d6-11e8-95c0-412e96f07b00.png)

- We are changing the sender name back to MITx MicroMasters
- The subject line will be in the format "[DEDP_jobs] Re: Job site for Social Impact Jobs" where "DEDP Jobs" is the channel name, and "Job site for Social Impact Jobs" is the post title.
- The links in the footer to allow the used to "Edit your settings" [link to settings page], or "unfollow this post" which links to the post itself, where they can click unfollow.
