### ISSUE TITLE
Track user activity

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#473]
We should add a way of tracking the user's activity. We don't want to do this on every API request so the best way might be whenever we see a token with a newer `iat` (https://en.wikipedia.org/wiki/JSON_Web_Token#Standard_fields) value, we update with that value. This value could then be roughly interpreted as "last login". We should probably store this on the `Profile`.

**Comment by pdpinch** [comment]
What do you mean by "whenever we see a token" -- would that mean an addition to socialauth pipeline?

**Comment by rhysyngsun** [comment]
It'd probably just need to be some fairly vanilla middleware we write.
