### ISSUE TITLE
Mail: Settings UI for automatic follow subscriptions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#474]
as a user, I would like to be have the option to disable comment notifications on my posts and comments

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/36696689-e5b12da6-1b12-11e8-894a-6db4bb9bd93b.png)

**Comment by pdpinch** [comment]
@rhysyngsun do we have the back-end to support one or both of these settings yet? APIs?

**Comment by rhysyngsun** [comment]
@pdpinch we have support for the digest emails, the other work will be done when we get around to the notification implementations

**Comment by roberthouse54** [comment]
There is a slight modification to the design of this:

![image](https://user-images.githubusercontent.com/20047260/38329052-9dc64fb0-381a-11e8-8bbf-1304416d2654.png)
