### ISSUE TITLE
Mail: model and API updates for setting automatic subscriptions on/off

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#475]
As a user I would like to be able to disable the feature that I get email notifications automatically for any replies to my posts and comments.

### out of scope
- in the future, we may want to offer more options than simply "on" and "off," e.g. scheduled digests of notifications

**Comment by rhysyngsun** [comment]
Should this result in not receiving the emails at all or just not having the subscription automatically occur? This has implications where if it's the former, you still accumulate subscriptions but you just don't receive the emails.

**Comment by rhysyngsun** [comment]
Blocked pending answer to the above question.

**Comment by rhysyngsun** [comment]
@pdpinch not sure if you saw my question above

**Comment by pdpinch** [comment]
Sorry I didn't answer this sooner. 

I dream of a future where the notification medium is managed separately from the notification subscription (i.e. email vs. browser vs. something else). Until that day comes, I think this setting is about notification subscription (i.e. "not having the subscription automatically occur")

**Comment by rhysyngsun** [comment]
Closing as discussed since we're ok with current behavior for now.
