### ISSUE TITLE
Editing a comment results in an error page as a non-moderator user

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#476]
The key here is that you must be a non-moderator user. If you go to edit a comment on a post and submit it you will see a 403. Inspecting the payload, the entire `CommentInTree` object is being sent including extraneous values and (more problematically) fields that any moderator-only, which is probably what's causing the 403.

Your edit still succeeds, because the code is ordered such that the change is persisted before applying the admin field changes.

**Comment by aliceriot** [comment]
I think this should be pretty straightforward to address, we are currently patching `{ ...comment, text: text }` (where `text` is the edited comment) and we probably just want to change that to `{ text }`

**Comment by aliceriot** [comment]
Just checked and this happens for editing posts as well ;_;
