### ISSUE TITLE
front-end data model

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#49]
George and I had a brief conversation today about this. I think we should store all the data we need to worry about (`Channels`, `Posts`, etc) in a normalized form, something like:

```js
type store = {
  posts: Map<postID, Post>,
  channels: Map<channelID, channel>
};
```

where `Post` and `Channel` are types holding all the information unique to each. We don't have to use a `Map` (although I like them), we could just as easily use an `Object`, but the idea is that all `Posts` would live in one spot, and handling the result of a `GET` request about a post or a `GET` request for the posts on a channel would be handled the same way - just insert the new posts into the record, and update the store.

To associate `Post` records with a `Channel` we could just store an array of `Post` ids on the `Channel` object which relevant to it - same for comments on a `Post`, etc.

I think designing the store like this will keep our lives simpler, and allow us to write code (e.g. for displaying posts, displaying comments, etc) that can be more agnostic about where the data came from, i.e. did we fetch these comments from a subreddit or from expanding a comment tree?

There's some documentation in the `redux` documentation arguining for this sort of design pattern [here](http://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html).

**Comment by aliceriot** [comment]
@noisecapella @rhysyngsun thoughts?

**Comment by aliceriot** [comment]
The PR I merged yesterday implements `postForChannel` as a sort of join table - it's type is basically `Map<channelID, Array<postID>>`. It lives in it's own reducer, instead of being part of the channel reducer.

**Comment by pdpinch** [comment]
What's the status of this? It sounds like it's In Progress.

**Comment by rhysyngsun** [comment]
I think we can close it now since we've implemented this and have functional code for it, right? I'll close feel free to reopen.
