### ISSUE TITLE
restore Missing comments

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#498]
Starting around 2/7 the RabbitMQ servers were unable to authenticate, leading to a problem with persisting comments. Renewing the RabbitMQ credentials fixed the problem for new comments, but we still have an issue with comments submitted between 2/7 and today. 

In our investigation so far, we can confirm that the submitted comments exist in postgres, but they are not returned by the open discussions API.

**Comment by pdpinch** [comment]
Here are two examples:

The post at https://discussions.odl.mit.edu/channel/DEDP/4o indicates that it has two comments, but none are visible. Looking at the postgres database, it appears that there should be comments available at https://discussions.odl.mit.edu/channel/DEDP/4o/comment/D6 (`thing_id=474`) and https://discussions.odl.mit.edu/channel/DEDP/4o/comment/DO (`thing_id=492`)

Similarly, the post at https://discussions.odl.mit.edu/channel/DEDP_Jobs/4s indicates that it has two comments as well, but neither displays. According to the db, there should be comments at https://discussions.odl.mit.edu/channel/DEDP_Jobs/4s/comment/DC and https://discussions.odl.mit.edu/channel/DEDP_Jobs/4s/comment/DQ

**Comment by rhysyngsun** [comment]
Fixed in prod
