### ISSUE TITLE
Update README with explanation of how variables and host names should be configured

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#501]
Update the README to explain how to modify hostnames in development so that open-discussions and micromasters docker containers can properly communicate and share cookies.

Explain how to set the following env. variables for OD and MM, some of which need to be synced to the same values.   Also might be good to add some of these to `.env.example` if not already there.

In open-discussions:
```
MICROMASTERS_EXTERNAL_LOGIN_URL
MICROMASTERS_BASE_URL
OPEN_DISCUSSIONS_COOKIE_NAME
OPEN_DISCUSSIONS_JWT_SECRET
OPEN_DISCUSSIONS_REDDIT_CLIENT_ID
OPEN_DISCUSSIONS_REDDIT_SECRET
OPEN_DISCUSSIONS_REDDIT_URL
```

in micromasters:
```
OPEN_DISCUSSIONS_JWT_SECRET
OPEN_DISCUSSIONS_COOKIE_NAME
OPEN_DISCUSSIONS_COOKIE_DOMAIN
OPEN_DISCUSSIONS_REDIRECT_URL
OPEN_DISCUSSIONS_BASE_URL
OPEN_DISCUSSIONS_API_USERNAME
```

**Comment by rhysyngsun** [comment]
FYI - `MICROMASTERS_EXTERNAL_LOGIN_URL` and `MICROMASTERS_BASE_URL` are going away in #492
