### ISSUE TITLE
Add REST API for front page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#51]
We should add an endpoint `/api/v0/frontpage/` which has the same content as a subreddit listing but which uses the frontpage listing algorithm (I think this is 'hot' by default) to create a listing of posts for all subreddits the user is subscribed to.

**Comment by pdpinch** [comment]
Would this be part of #15?

**Comment by aliceriot** [comment]
it's necessary for #15 to be fully implemented, but I can work on the UI without the API being present yet (see the PR I opened yesterday to add factories).

**Comment by aliceriot** [comment]
I realized we'll need to include one extra piece of data in this API which we don't need in the `postsForChannel` API - namely, we need to know which channel the posts is being pulled from.
