### ISSUE TITLE
Change date format so it is internationally understandable

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#510]
Currently, we use the date format mm/dd/yyyy. 

This is confusing for some international learners in countries where the date is commonly formatted at dd/mm/yyyy. To fix this, we should switch to a date format that writes out the month like this:

March 12, 2018.

**Comment by aliceriot** [comment]
The date library we are using also has some internationalization support, see here for examples: http://momentjs.com/docs/#/i18n/ so we could try to figure out, based on the user's browser, what their locale is and adjust the date support accordingly (although it may be a bit strange to see something like 'dimanche 15 juillet 2012' if the rest of the app is only in English)

**Comment by aliceriot** [comment]
I think that, looking through our code, in `open-discussions` we only ever use the `moment.fromNow()` function (which returns something like '1 month ago', '2 years ago', etc), so I don't think we'll need to make any changes over here (just in MM)
