### ISSUE TITLE
increase uwsgi buffer 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#529]
even though we have decreased the size of the discussions cookie in #444, we should still bump up the uwsgi buffer in case there are any users still out there with the old cookie. 

As we've seen on [odl-video-service](https://github.com/mitodl/salt-ops/commit/b32fdd89b0fc0b799db98176a5541b72b809092b), there may also be some MIT users generating large header requests.

**Comment by pdpinch** [comment]
@Ferdi before we make this change, would you mind testing to see if you're still getting the "big cookie" issue?

The test would be to visit the following URLs and log in with MicroMasters/edx:

https://discussions.odl.mit.edu/
https://discussions-rc.odl.mit.edu/
https://discussions-ci.odl.mit.edu/

**Comment by Ferdi** [comment]
No issues for me.
