### ISSUE TITLE
Add a link to "Settings" in the sidenav

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#545]
![image](https://user-images.githubusercontent.com/20047260/37716832-cce4d706-2cf5-11e8-9233-0700b17e7d5e.png)

**Comment by pdpinch** [comment]
Uh, this wasn't quite ready to work on yet...

**Comment by roberthouse54** [comment]
This instead:

![image](https://user-images.githubusercontent.com/20047260/37729552-ab6e0ac0-2d13-11e8-91b5-5f0d7a79ed28.png)

**Comment by rhysyngsun** [comment]
We should defer merging this until #541 is released and #535 is complete.
