### ISSUE TITLE
Add ZenDesk "Help" widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#549]
Same as MicroMasters, in theory. 

If we can, we should pre-populate the user's name and email address. We can leave the "MicroMasters Program" drop down empty.

**Comment by aliceriot** [comment]
do you think we should just hide the program drop down for discussions?

**Comment by pdpinch** [comment]
Yes, if possible. 
> do you think we should just hide the program drop down for discussions?
>
