### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#559]
As a user, I'd like to be able to find out more about a poster. In particular, I'd like to know how committed they are to the discussions and what their other posts have been. 

We can do this in a couple of phases, when these features start to provide user value. 

1. User chip with count of posts and joined date
2. User chip with karma
3. User chip with link to User Profile page, with list of posts & comments
4. User chip with message user link

**Comment by roberthouse54** [comment]
Also possibly show country?

**Comment by pdpinch** [comment]
this isn't really relevant or accurate any more
