### ISSUE TITLE
User chip with count of posts & joined date

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#562]
As a user, I'd like to know more about the user who made a post or a comment, so I can judge their involvement in the platform.

When I mouse over a user image in a channel listing, I'll see a pop-up with a count of the user's posts and a the date they joined the platform.

**Comment by pdpinch** [comment]
As a user, I'd like to know more about the user who made a post or a comment, so I can judge their involvement in the platform. 

When I mouse over a user image in a channel listing, I'll see a pop-up with a count of the user's posts and a the date they joined the platform.

**Comment by roberthouse54** [comment]
Other possible things to show (future?):
-  karma
- country

**Comment by pdpinch** [comment]
we don't plan to use user chips any more
