### ISSUE TITLE
Performance: slow page load in Chrome

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#587]
Google Analytics is reporting that loading discussion pages in Chrome takes significantly longer than all other browsers. 

![screenshot 2018-04-06 09 17 16](https://user-images.githubusercontent.com/430126/38423246-5bf3a90e-397b-11e8-8e50-1e38c55729ad.png)

**Comment by aliceriot** [comment]
Looking into this, some initial thoughts:

- we have far more usage on chrome, compared with other browsers (about 68% of traffic), so this skew could reflect sampling error (i.e. if we saw the same amount and distribution of page views on other browsers they would also be slow)

- I realized that we don't seem to have enabled cloudfront in the production discussions app for serving JavaScript and CSS static assets, that would definitely cut down on the amount that the user needs to download (and I think, iirc, we wrote some reusable stuff around that in MM). We are also not currently using gzip, the GA tools suggest we could save close to 70% of the download size on some of our bigger JS files by enabling that (for reference the current total download size to load the homepage is around 1.2 mb, so we might be able to get down to around the 400 kb range, which would be great.

Looking at this distribution of page load times (I can't figure out a way to get a better figure, GA is a bit frustrating to use) it seems like our average load times might be getting dragged up by just a few users with extremely long load times:

![blblblblblblblb](https://user-images.githubusercontent.com/6207644/38507776-69e94a7e-3beb-11e8-8f26-d1bd03b4ceae.png)

(it isn't all the data, just a random sample of 107 page views, don't ask me why you can't analyze all of it). As to why we see this effect more with Chrome than other browsers, I'm not sure. One answer might be that Chrome is widely used on Android devices, but looking through the data for the homepage (`/`) it looks actually like mobile devices are generally faster, so...

![mobilefaster](https://user-images.githubusercontent.com/6207644/38508054-2580cff0-3bec-11e8-9d80-5e31640e4502.png)

yeah so idk. I think we should get cloudfront and gzip set up, and see what difference that makes, and then if, after doing that, we're still seeing a big issue with chrome maybe dig deeper to see if there are some relevant browser differences (between chrome and the other browsers) which we can try to optimize for.

**Comment by pdpinch** [comment]
have you been able to reproduce a "slow" load with your own browser?

**Comment by aliceriot** [comment]
Yeah, it's pretty straighforward to do that by throttling the connection, but it doesn't really tell us much about what's driving the slow loads that users are seeing

**Comment by aliceriot** [comment]
this is the data for page load time vs country:

![fjfjfjfjfjfjfjfjfjfjfjfj](https://user-images.githubusercontent.com/6207644/38508870-51bb785c-3bee-11e8-80b1-812e7eeddf2c.png)

I'm thinking this is likely more primary than what browser the user is using.

**Comment by pdpinch** [comment]
Can you do a similar analysis of country & browser? I'll be convinced if we see most everyone in Nigeria is using Chrome. 

I wonder if there's a Cloudfront node close to Nigeria.

**Comment by aliceriot** [comment]
I'm really not a fan of the GA interface...

Here's the divisions of Nigeria in which we've had page-viewed vs browser:

![nigeria_by_browsers](https://user-images.githubusercontent.com/6207644/38509256-64e06f0e-3bef-11e8-9ee1-9212bcf0c3dc.png)

I think it's pretty clearly the internet connection for the one user who has a 47 second load time, and not something to do with Chrome, although in the absence of data points from users of _other_ browsers from that area we can't completely rule it out.

**Comment by pdpinch** [comment]
I opened an issue to add CDN (Cloudfront) support. I think we can do gzip at the same time (at least for static assets). 

This should probably also go into the cookie-cutter django app, if that's possible.

**Comment by pdpinch** [comment]
Closed in favor of #595
