### ISSUE TITLE
Configure cloudfront CDN

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#595]
Investigation of slow loading time in Chrome (#587) lead to the realization that the app isn't configured to use Cloudfront. We should set that up and, when we do, also turn on gzip compression. 

Here's how we did this in MicroMasters: https://github.com/mitodl/micromasters/pull/1924/files

**Comment by pdpinch** [comment]
Can this be added to the django cookie-cutter app?

**Comment by pdpinch** [comment]
I'm re-opening this and assigned to @mitodl/devops because this doesn't seem to be turned on in production or RC.

**Comment by aliceriot** [comment]
The relevant commit is not yet in production, since I'm still waiting on the RC distribution being set up to confirm the commit there.

**Comment by shaidar** [comment]
Created cloudfront distribution for `RC` in AWS and added key/value to Heroku app.

**Comment by aliceriot** [comment]
:+1:

**Comment by aliceriot** [comment]
Can we get one set up for prod too?

**Comment by shaidar** [comment]
@aliceriot Created cloudfront distribution for `Prod` in AWS and added key/value to Heroku app.

**Comment by pdpinch** [comment]
This looks to me like it's done.
