### ISSUE TITLE
When a comment is made, add it to the search index

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#606]

**Comment by pdpinch** [comment]
we'll need to think through the questions in #605 first

**Comment by pdpinch** [comment]
@gsidebo you're working on this right? Please assign it to yourself and move to in progress.

**Comment by gsidebo** [comment]
Setting this to 'blocked' for the time being as we look into https://github.com/mitodl/open-discussions/issues/720. We will likely close this issue in favor of that one
