### ISSUE TITLE
don't fetch style.js in production

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#617]
We use the `ExtractTextPlugin` in prod to pull the style bundle out as a separate CSS file (instead of a JavaScript file). In prod currently, however, we include both the CSS file and the JS on the page...

**Comment by aliceriot** [comment]
actually, just looked into this a little more and the JS file is typically a few hundred bytes, so I don't think we need to worry too much about this. it does look like it isn't required for the CSS to all work ok. I set up my dev env to have a prod-ish static files things going on, blocked the `style.js` file, and everything looks normal. So we may want to work on trying to get rid of it in order to avoid the overhead of an additional request, but it's probably not like super important (or going to make a huge difference).

**Comment by noisecapella** [comment]
Yeah, if the CSS was extracted out the file would just be the `__webpack_public_path__` assignment

**Comment by pdpinch** [comment]
I don't think this is actually in progress any more. I'm going to move it to tech debt. 

@aliceriot if you are working on this, feel free to move it.

**Comment by aliceriot** [comment]
I think we can probably just close actually, not sure what @noisecapella thinks
