### ISSUE TITLE
Better logging for failed emails

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#618]
Locally I get this message due to misconfiguration: `mail.exceptions.SendEmailsException: [(<anymail.message.AnymailMessage object at 0x7f6effc34ef0>, AnymailRequestsAPIError())]`

If I let it raise it gives me enough information to know that it's a misconfigured domain name. Is there a way we can put the error message + stacktrace in the `failed_message_errors` list so that it gets output by the loggers?

**Comment by pdpinch** [comment]
Is this mostly a development issue, or are you concerned about issues in production?

**Comment by rhysyngsun** [comment]
I think we should just `log.exception()` each individual error from mailgun. I think rolling up the exceptions made sense in MM where we are using the batch API, but here we're not so there's no reason to maintain that holdover from the MM code.
