### ISSUE TITLE
Add pydocstyle linting, switch to pycodestyle

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#623]
https://pypi.org/project/pydocstyle/

We should also switch to pytest-pep8 to pytest-pycodestyle and use pytest-pydocstyle for this

**Comment by aliceriot** [comment]
Could we possibly also look into not requiring docstrings for everything? I feel like I often write things like

```python
def get_foo():
    """function to get foo"""
    ...
```
or
```python
class FooAPI:
    """API for Foo"""
```

to make the linting errors go away, which just feels really silly to me, since these comments add zero information most of the time.
