### ISSUE TITLE
Add test for authentication in reddit

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#63]
The authentication code in `channels/api.py` is mostly uncovered because we mock this out for most tests. We should add a unit test or two for it, specifically `_get_user_credentials` and `_get_requester_kwargs`

**Comment by rhysyngsun** [comment]
This was actually covered by these tests added a while ago: https://github.com/mitodl/open-discussions/blob/master/channels/api_test.py#L505-L559
