### ISSUE TITLE
consider using Prettier for JavaScript formatting

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#64]
[prettier](https://prettier.io/) is an automated code-formatting tool for JS that looks pretty nice, basically it parses the JavaScript to an AST and then re-writes it all, allowing it to do more complicated types of automated transformations that ESLint, for instance, can't do in an automatic way. It seems like there's support to run it alongside ESLint, since prettier doesn't catch certain kinds of semantic errors in the code (which ESLint does).

anyway, I think it looks interesting and would like to try it out! @noisecapella @rhysyngsun thoughts?

**Comment by noisecapella** [comment]
I'm fine to try it out

**Comment by rhysyngsun** [comment]
I'm game

**Comment by aliceriot** [comment]
cool, I'll look into setting it up!

**Comment by aliceriot** [comment]
semicolons? no semicolons?

**Comment by aliceriot** [comment]
I opened the PR with `--no-semi`, we can easily change it back if we want.
