### ISSUE TITLE
Create (and re-create) index using existing posts and comments

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#641]

**Comment by noisecapella** [comment]
The approach I'm taking currently is to use reddit's REST API to iterate over channels, posts and comments and index them: https://github.com/mitodl/open-discussions/pull/651/files#diff-649494e1cc93b79504ba109a547519f6R1

I'm going to rely on Celery to do exponential backoff and throttling

**Comment by pdpinch** [comment]
@noisecapella when we met with @blarghmatey I think we discussed a few other possibilities. We should note them here as well and why we're not pursuing them now:

1. Building the index directly off of postgres database.
2. Building the index directly off of the Cassandra database
3. Leveraging Reddit's existing Solr integration

**Comment by pdpinch** [comment]
Gavin also reminded me yesterday that we're limited to 1000 items (posts? comments? I'm not sure) for each API call.
