### ISSUE TITLE
Search posts and comments in one channel

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#642]
There is some discussion of the implementation in this google doc: https://goo.gl/5TvGpw

**Comment by gsidebo** [comment]
Preliminary document structure looks like this:

```javascript
{
  "post_id": {
    "type": "long"
  },
  "post_title": {
    "type": "text"
  },
  "comment_id": {
    "type": "long"
  },
  "parent_comment_id": {
    "type": "long"
  },
  "text": {
    "type": "text"
  },
  "author": {
    "type": "keyword"
  },
  "score": {
    "type": "long"
  },
  "created": {
    "type": "date"
  },
  "removed": {
    "type": "boolean"
  },
  "deleted": {
    "type": "boolean"
  },
  "channel_title": {
    "type": "keyword"
  },
  "doc_type": {
    "type": "keyword"
  }
}
```

Some notes:

- This will represent both comments and posts. The `doc_type` field value will differentiate between the two (ES documentation highlights this approach [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_custom_type_field)).
- `score` indicates overall upvote/downvote tally.
- Depending on what we find while testing this, we may add a separate column for # of comments for a post. We want to be able to show this number in search results and sort by it.

**Comment by gsidebo** [comment]
A few notes: 

1. This sentence in the doc links to a deprecated guide: "What is the best way to handle the [relationship](https://www.elastic.co/guide/en/elasticsearch/guide/master/relations.html)". The Elasticsearch Definitive Guide has not been updated to reflect the changes in Elasticsearch 6, and so it still refers to adding different mapping types to a single index (that isn't possible in ES6).
1. Posts and comments have a very similar structure. Posts and comments both include the following fields: `text`, `author`, `score`, `removed`, `created`, `channel_title`. Creating a single mapping to represent both isn't all that much of a stretch, and there should not be any noticeable performance or storage space penalty from the small number of fields that are irrelevant to each type (e.g.: the `title` field for `comment`-type documents)
1. Using the [join datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html) comes with some limitations. The docs describe a [performance penalty](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html#_parent_join_and_performance), and parent and child documents must be [indexed on the same shard](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html#_parent_join_restrictions).
1. Just as a general guideline, Elasticsearch and other NoSQL databases encourage denormalized/"flat" data. [The definitive guide touches on that here](https://www.elastic.co/guide/en/elasticsearch/guide/master/denormalization.html), and though the guide hasn't been updated for version 6, that principle is still the same. The document structure described above is in line with that recommendation.

All of the above are technical concerns. Are you worried about any features that we might not be able to implement with this structure?

**Comment by pdpinch** [comment]
replaced by #1316
