### ISSUE TITLE
BI: number of email deliveries/opens/clicks per week

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#663]
As an engineer, I'd like to be able to visualize the number of notification email deliveries, opens and clicks over time (per week seems like a useful grouping for now). 

Mailgun logs deliveries and opens currently. We may need to make some changes to the mail template / API call in order to track clicks. 

We may have to do some configuration work to persist mailgun data and integrate it into BI. Mailgun only keeps logs for 30 days.

**Comment by pdpinch** [comment]
@maxliu can you discuss with @mitodl/devops how best to persist the Mailgun data for BI?

**Comment by pdpinch** [comment]
I just confirmed that mailgun is configured to deliver this data to fluentd.

**Comment by pdpinch** [comment]
BUT, click tracking wasn't turned on for the discussions-odl domain -- I'll try it now.

**Comment by blarghmatey** [comment]
@maxliu this data is now present in BI under the "Athena Data Lake" data source. Mailgun events are uploaded hourly and should be queryable from the BI interface. Let me know if you run into any issues.

**Comment by pdpinch** [comment]
Data is still not accessible from BI. I'm assigning this back to DevOps.

**Comment by blarghmatey** [comment]
This data should be available now for @maxliu to begin building the reports.

**Comment by pdpinch** [comment]
@maxliu can you add a link to the query here?

Based on the last time we met, we need the following changes:

- [ ] add open rates (maybe already done?)
- [ ] look into the bounce and drop data and decide:
  - [ ] which one is more useful (probably drop) 
  - [ ] does it need to be filtered? (I care more about dropped for spam than I do about dropped for a bad domain)
- [ ] add it to the Open Discussions dashboard

**Comment by maxliu** [comment]
links

Mailgun weekly monitoring https://bi.odl.mit.edu/queries/482#796
Mailgun drop summary  https://bi.odl.mit.edu/queries/485#798
Mailgun bounced summary https://bi.odl.mit.edu/queries/479#788

**Comment by maxliu** [comment]
map for mailgun events and tables on BI. 


Item | Mailgun event   and tag | Table name  on BI | Explaination
-- | -- | -- | --
1 | Clicked |   | The email recipient   clicked on a link in the email. Click tracking must be enabled in the Mailgun   control panel, and the CNAME record must be pointing to mailgun.org
2 |   |   |  
3 |   |   |  
4 |   |   |

**Comment by pdpinch** [comment]
This looks good to me.
