### ISSUE TITLE
BI: number of digest unsubscribes over time

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#664]
As an engineer, I'd like to know how many people are unsubscribing from the digest email.

**Comment by maxliu** [comment]
Can you provide more info for this issue?

**Comment by pdpinch** [comment]
We can see that a user has unsubscribed to the frontpage digest by looking at `notifications_notificationsettings` where `notification_type="frontpage"` and `"trigger_frequency="never"`

**Comment by maxliu** [comment]
note: in the table of notifications_notificationsettings for the record of notification_type=frontpage and trigerfrequncy=never

**Comment by maxliu** [comment]
query on BI:

https://bi.odl.mit.edu/queries/364/source

**Comment by pdpinch** [comment]
This chart looks good. We do need to find a way to correlate it to other actions on the site (either code releases or particular post activities)
