### ISSUE TITLE
BI: number of posts and comments per week

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#665]
As an engineer, I'd like to keep track of the increase (or decrease) of posts and comments over time

**Comment by maxliu** [comment]
need to figure out how to find the data time for each post and comment.

**Comment by pdpinch** [comment]
@maxliu I think you did this, in https://bi.odl.mit.edu/queries/365#582 ?

**Comment by maxliu** [comment]
Yes, this is done.
