### ISSUE TITLE
BI: number of followed posts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#666]
As an engineer, I'd like to know how often the follow feature is being used. 

We can track this using the notifications table. However, I don't think we can differentiate between people who clicked "follow" and people who are automatically following their own posts.

**Comment by maxliu** [comment]
note:  in "channels_subscription" post and comments

**Comment by pdpinch** [comment]
`cnt_of_active_users` isn't the right label for this. This is a count of unique users who are using the subscribe/follow feature.

**Comment by pdpinch** [comment]
After further discussion with Ferdi, we decided this graph wasn't useful. The data is a mix of users who actively subscribed by clicking the follow button and users who passively subscribed by automatically following their own post or comment. 

I'll open a new issue for tracking follow button clicks using Google events.

**Comment by pdpinch** [comment]
replaced by #732
