### ISSUE TITLE
Create basic search page

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#669]
#605 and #606 cover the work to add/edit posts and comments in the Elasticsearch index as changes are made in the app. This issue covers the following:

- Add a search page to the UI that is only available when a feature flag is set
- Include a text input for a search term with a submit button (no search-as-you-type yet)
- Show basic information for posts and comments that match the text (perhaps with a link to that object)
- Limit results to posts/comments in channels that the logged-in user has permission to view

**Comment by gsidebo** [comment]
There are a few things we need to figure out in order to display these objects in search results exactly as they would appear in the search page (which is listed as one of the requirements):
1. Decide on how to index a user's full name and profile image so they can be displayed with posts/comments in search results (or forego the indexing and introduce some logic that fills in the name/picture outside of the ES query)
1. Decide how we want to render comments. Do we show the post title with a link to the post? Where does that post title go relative to the comment? Do we show anything special for inner comments as opposed to top-level comments? Do we show anything special if the matching comment has child comments? Do we need to show user/picture/score for the parent post as well as the comment itself?
1. Decide on how (if at all) we want to highlight the text of posts/comments that match the search term.

I would recommend that we implement this with a very basic search result UI (i.e.: not exactly reflecting the appearance of posts/comments elsewhere in the app) and create separate issues for:
1. Rendering search results in a way that matches the way we render posts/comments elsewhere in the app
1. Implementing a paging control

**Comment by pdpinch** [comment]
overtaken by events
