### ISSUE TITLE
Update frontend to handle user sessions that don't have a JWT token

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#670]
Our current frontend implementation has some code that assumes the existence of a JWT token that needs to be periodically renewed (e.g. the code in `static/js/lib/auth.js`). We need to allow for user sessions that are valid but don't have a JWT token.

#### Known cases:

- [ ] Anonymous users
- [ ] Users with a OD django session (e.g. logged in via email, EdX, Touchstone, etc)

#### Ideas

- When a user first navigates to OD with a JWT token, give them an actual django session and remove the token. Then we could remove JWT-specific code in OD and the JWT can just be an alternative mechanism to acquire a session. We'd need to roll this out in phases:
  - **Phase 1** - Update OD to support MM JWT -> session authentication. This would require a new auth page of some sort.
  - **Phase 2** - Update MM to send the user to the auth endpoint
  - **Phase 3** - Remove legacy support of JWT tokens in frontend
- ???

**Comment by pdpinch** [comment]
I'm moving this to In Progress since there's a PR open.

**Comment by pdpinch** [comment]
This is mostly done. Needs MM config and then a clean up issue in open.

**Comment by pdpinch** [comment]
I opened https://github.com/mitodl/micromasters/issues/3988 and https://github.com/mitodl/open-discussions/issues/727 for the follow up work.
