### ISSUE TITLE
create account with Touchstone

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#671]
As a member of the MIT community, I'd like to be able to create an account using Touchstone.

### acceptance criteria
- [x] use MIT email address for new account
- [x] use MIT name (SAML `displayName`?) to populate profile name

### questions
- [ ] What happens when Touchstone flow fails, or user bails out? 

### related issues (out of scope)
- pre-populate headline with MIT role, 
- set MIT status in profile
- user should be able to reset (add) password after creating account
- user should be able to add another email address to the account, for account recovery

**Comment by pdpinch** [comment]
The related profile issues are blocked until the profile model is created

**Comment by mbertrand** [comment]
- Touchstone (via [django-shibboleth](https://github.com/Brown-University-Library/django-shibboleth-remoteuser/blob/master/shibboleth/backends.py#L59)) will automatically overwrite the email address of the `User` on login if `email` is included in the `SHIBBOLETH_ATTRIBUTE_MAP` Django settings (as they are in OVS).  If excluded, email will not be auto-populated at all on Touchstone login/registration.  Could fork `django-shibboleth` and make these login updates optional based on a new boolean setting, or save user-specified email addresses in `Profile` instead.

- Logging in via Touchstone doesn't necessarily mean you are affiliated with MIT (collaboration accounts open to anyone).

**Comment by pdpinch** [comment]
I updated the description to move the password reset function out of scope. We'll tackle that in a separate issue(s).

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Log in through EdX or MicroMasters or Touchstone or Email](https://trello.com/c/Wuwcvzzb/42-log-in-through-edx-or-micromasters-or-touchstone-or-email)

**Comment by mbertrand** [comment]
@tmacey do you know if there are any additional attributes returned by Touchstone with successful login, besides `EPPN`, `MAIL`, `DISPLAY_NAME`?

**Comment by mbertrand** [comment]
@blarghmatey  I think we will need to generate our own X509 certificate for each server this will be enabled on (discussions.odl.mit.edu, discussions-rc.odl.mit.edu, discussions-ci.odl.mit.edu?), and then register each with the Touchstone IdP.  

![screen shot 2018-05-25 at 8 54 26 am](https://user-images.githubusercontent.com/187676/40545367-96a8a7bc-5ff9-11e8-85ae-a0343f964f50.png)

**Comment by mbertrand** [comment]
@blarghmatey should I create the x509 certs and private keys and pass them on to you; and then send requests to touchstone support?  I have the attribute map set up for the Touchstone parameters I know about, was just wondering if there were more that I could map to, found a list [here](http://kb.mit.edu/confluence/display/istcontrib/Touchstone+FAQ#TouchstoneFAQ-DeveloperSupport)

**Comment by mbertrand** [comment]
@pdpinch looks like Touchstone should return an `affiliation` attribute if the user is affiliated with MIT.  That could be used to populate a boolean `mit_affiliated` attribute for the Profile model.

**Comment by pdpinch** [comment]
> @pdpinch <https://github.com/pdpinch> looks like Touchstone should return an affiliation attribute if the user is affiliated with MIT. That could be used to populate a boolean mit_affiliated attribute for the Profile model.
> 


Worth looking into. Is there any documentation for that field? What are the possible values? Are we seeing this in practice (I know, you probably can't tell yet).

**Comment by mbertrand** [comment]
There is some documentation at http://kb.mit.edu/confluence/display/istcontrib/Touchstone+FAQ#TouchstoneFAQ-AttributeReleasePoliciesandPrivacy

Looks like the possible values are `staff`, `student`, and `affiliate`.  I don't know if that's what actually happens in practice yet.

**Comment by mbertrand** [comment]
@blarghmatey @shaidar the code for SAML support has been merged, here are the new environment variables that need to be set for it to work:

```
FEATURE_SAML_AUTH=True
SOCIAL_AUTH_SAML_SP_PUBLIC_CERT=<x509 public certificate string for server>
SOCIAL_AUTH_SAML_SP_PRIVATE_KEY=<x509 private key string for server>
SOCIAL_AUTH_SAML_ORG_DISPLAYNAME=<'MIT ODL' or whatever else you prefer>
SOCIAL_AUTH_SAML_CONTACT_NAME=<'ODL Support' or whatever else you prefer>

SOCIAL_AUTH_SAML_IDP_ENTITY_ID=https://idp.mit.edu/idp/shibboleth
SOCIAL_AUTH_SAML_IDP_URL=https://idp.mit.edu/idp/profile/SAML2/Redirect/SSO
SOCIAL_AUTH_SAML_IDP_ATTRIBUTE_PERM_ID=EPPN
SOCIAL_AUTH_SAML_IDP_ATTRIBUTE_NAME=DISPLAYNAME
SOCIAL_AUTH_SAML_IDP_ATTRIBUTE_EMAIL=MAIL
SOCIAL_AUTH_SAML_IDP_X509=MIIDCDCCAfCgAwIBAgIJAK/yS5ltGi7MMA0GCSqGSIb3DQEBBQUAMBYxFDASBgNVBAMTC2lkcC5taXQuZWR1MB4XDTEyMDczMDIxNTAxN1oXDTMyMDcyNTIxNTAxN1owFjEUMBIGA1UEAxMLaWRwLm1pdC5lZHUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDgC5Y2mM/VMThzTWrZ2uyv3Gw0mWU9NgQpWN1HQ/lLBxH1H6pMc5+fGpOdrvxH/Nepdg6uAJwZrclTDAHHpG/THb7K063NRtic8h9UYSqwxIWUCXI8qNijcWA2bW6PFEy4yIP611J+IzQxzD/ZiR+89ouzdjNBrPHzoaIoMwflftYnFc4L/qu4DxE/NWgANYPGEJfWUFTVpfNV1Iet60904zl+O7T79mwaQwwOMUWwk/DEQyvG6bf2uWL4aFx4laBOekrA+5rSHUXAFlhCreTnzZMkVoxSGqYlc5uZuZmpFCXZn+tNpsVYz+c4Hve3WOZwhx/7bMGCwlx7oovoQWQ5AgMBAAGjWTBXMDYGA1UdEQQvMC2CC2lkcC5taXQuZWR1hh5odHRwczovL2lkcC5taXQuZWR1L3NoaWJib2xldGgwHQYDVR0OBBYEFF5aINzhvMR+pOijYHtr3yCKsrMSMA0GCSqGSIb3DQEBBQUAA4IBAQDfVpscchXXa4Al/l9NGNwQ1shpQ8d+k+NpX2Q976jau9DhVHa42F8bfl1EeHLMFlN79aUxFZb3wvr0h5pq3a8F9aWHyKe+0R10ikVueDcAmg0V7MWthFdsyMwHPbnCdSXo2wh0GhjeIF3f3+hZZwrZ4sZqjX2RmsYnyXgS1r5mzuu4W447Q1fbC5BeZTefUhJcfHQ56ztIFtLJdRuHHnqj09CaQVMD1FtovM86vYwVMwMsgOgkN3c7tW6kXHHBHeEA31xUJsqXGTRlwMSyJTju3SFvhXI/8ZIxshTzWURBo+vf6A6QQvSvJAju4zVLZy83YB/cvAFsV3BexZ4xzuQD
```

Also, the servers that this will be enabled on (RC and production?) [will need to be registered with Touchstone](https://github.com/mitodl/open-discussions/issues/671#issuecomment-392051310).

Not sure if creating the x509 certificates and registering with Touchstone is something I should do or if I should leave it up to you?

**Comment by pdpinch** [comment]
@mbertrand now that #735 has merged, what else needs to be done to allow creating accounts with Touchstone?

**Comment by mbertrand** [comment]
@pdpinch the comment just above yours details the additional steps.  Also there will need to be a link somewhere in the UI (`Log in with Touchstone`).

**Comment by pdpinch** [comment]
@mbertrand can we review the field mappings? I think we should commit some documentation about how they work.

**Comment by mbertrand** [comment]
@pdpinch do you mean Touchstone attributes -> User/Profile attributes?

`MAIL` ->  `User.email`
DISPLAYNAME -> `User.first_name`, `User.last_name`, `Profile.full_name`
