### ISSUE TITLE
Require users with MIT email login with Touchstone

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#672]
As a new user creating an account, if I have an email that ends in mit.edu (i.e `@mit.edu` or `@csail.mit.edu`), I should be directed to login with Touchstone.

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redirected to Touchstone if signing in with MIT email](https://trello.com/c/EWTffTsG/43-redirected-to-touchstone-if-signing-in-with-mit-email)

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Various Error messages (open card to read checklist):](https://trello.com/c/KjxX8kBU/46-various-error-messages-open-card-to-read-checklist)

**Comment by mbertrand** [comment]
@pdpinch should I be able to see those trello cards (I just created a Trello account with my MIT email address)?

**Comment by Ferdi** [comment]
@mbertrand, I don't think you need trello access. Let's talk tomorrow

**Comment by mbertrand** [comment]
PR #746 should be merged before working on this one.

**Comment by pdpinch** [comment]
Per planning, I'm reassigning this to Nathan

**Comment by mbertrand** [comment]
@pdpinch, what do you prefer:

1) Automatically redirect users to the Touchstone login page if they enter an MIT email and click the 'Next' button on the registration page (this is how I've currently implemented it).

2) Disable the 'Next' button if they enter an MIT email, display a message like 'Please login using Touchstone instead', and make them manually click the 'Touchstone@MIT' button/link.

**Comment by pdpinch** [comment]
To capture our face-to-face discussion with Ferdi, we decided on 2.
