### ISSUE TITLE
3rd party login error handling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#675]
As a user, if I cancel my 3rd party login, or it otherwise fails, I should get an error message and be able to return the screen I started on.

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Various Error messages (open card to read checklist):](https://trello.com/c/KjxX8kBU/46-various-error-messages-open-card-to-read-checklist)

**Comment by pdpinch** [comment]
Currently, this is only a concern for Touchstone login (edX login is on hold)

**Comment by rhysyngsun** [comment]
Do we know what kinds of errors we typically encounter here?

**Comment by pdpinch** [comment]
Honestly, I think is is moot as long as we only use Touchstone. It doesn't have a cancel button, so I don't think there's any way to get back to discussions without a successful authentication. 

We can ask Matt when he's back on Monday.
