### ISSUE TITLE
Profile: Update content (post) card to display headline 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#677]
As a user, when I see a post I'd like to know about the person making the post. I'd like to see the headline from their profile. 

For example, on https://zpl.io/2j4rxL4 the headline is "UCLA Post Doc Physics"

**Comment by mbertrand** [comment]
Should the author headline be part of the link to the profile (author name is a link)?
`<a href=..>NAME -- HEADLINE</a>`
 or 
`<a href=..>NAME</a> -- HEADLINE`

**Comment by Ferdi** [comment]
<a href=..>NAME</a> -- HEADLINE

**Comment by mbertrand** [comment]
There's currently no limit on the length of a headline, this can make a mess of the formatting.  Should headline be limited to a certain length?  Or just display the first X characters of the headline?

<img width="822" alt="screen shot 2018-08-06 at 4 52 51 pm" src="https://user-images.githubusercontent.com/187676/43740581-9d3450f2-9999-11e8-8746-fdff8e188d85.png">

<img width="888" alt="screen shot 2018-08-06 at 4 53 29 pm" src="https://user-images.githubusercontent.com/187676/43740585-a0cc9c4c-9999-11e8-9d1c-d0b552147950.png">

**Comment by Ferdi** [comment]
It should not be long. I thought it was 64 chars in the design. I'll check

**Comment by mbertrand** [comment]
For now I'll truncate the headline to the first 64 characters when displaying it on the post card.

**Comment by Ferdi** [comment]
Why don't we properly fix this by limiting the nr of characters in the profile form ?

**Comment by mbertrand** [comment]
Is 64 the agreed upon number of characters?  I will update the model field and form.

**Comment by Ferdi** [comment]
60
