### ISSUE TITLE
Profile: display red badge when profile is incomplete

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#680]
As a user, I'd like to see a subtle notification that my profile is incomplete, which will remind me to complete it when I have the time. 

We can display a (red, circular) badge over the profile image to indicate that the profile is not complete. When we add more fields to the profile in the future, we can use the same mechanism to draw user attention.

**Comment by mbertrand** [comment]
@pdpinch @roberthouse54 here are some variations using two material components icons, any preference for one over the other (or something else), smaller or bigger, etc?

<img width="203" alt="screen shot 2018-05-16 at 1 24 48 pm" src="https://user-images.githubusercontent.com/187676/40133084-a5d918a0-590c-11e8-8809-cd94506f19bd.png">
<img width="206" alt="screen shot 2018-05-16 at 1 24 17 pm" src="https://user-images.githubusercontent.com/187676/40133087-a8bb3d28-590c-11e8-881c-27fa03d9a09b.png">

**Comment by roberthouse54** [comment]
Hi Matt. We want to just use a small red circle like this:

![image](https://user-images.githubusercontent.com/20047260/40133560-2d1903e2-590e-11e8-9cb3-be3e3b02aee6.png)

**Comment by mbertrand** [comment]
Thanks @roberthouse54, will do

**Comment by pdpinch** [comment]
Don't spend too much time on the design, because that may change. 

The longer term value will be in the API and component logic. Please let us know how you plan to do it.

**Comment by mbertrand** [comment]
@pdpinch: 
- add a new property/function `is_complete` to the `Profile` model.  Will return `False` if there is no profile image, or if any of the following are blank/null: `name`, `headline`, `bio`. 
- Add the result of `is_complete` to the  javascript settings passed to the front-end.
- If the result is False, display the red circle.

**Comment by pdpinch** [comment]
Since there's a PR open for this, I'm moving it to In Progress
