### ISSUE TITLE
Profile: profile image model and API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#681]
As a new user, I'd like to be able to upload my a profile image. And, as a micromasters user, I'd like to be able to replace my profile image imported from MicroMasters. 

The existing profile model and API supports URLs for images, but does not allow for a new image to be uploaded.

**Comment by pdpinch** [comment]
Based on https://github.com/mitodl/open-discussions/issues/674#issuecomment-387539778 it appears that we don't need a new model. However, we will still need an API change to support image file uploads.

**Comment by pdpinch** [comment]
@mbertrand are you working on this?

**Comment by pdpinch** [comment]
@mbertrand what's the status of this issue?

**Comment by mbertrand** [comment]
@pdpinch The API is in place, I have a PR to adjust it (create the small and medium images from the main image), but blocked it to wait on the UI design for thumbnail sizes, which are currently copied straight from micromasters (max 64 pixels small, 128 medium).  But the design doesn't specify any particular thumbnail size so it can probably be unblocked?
