### ISSUE TITLE
Profile: UI to upload profile image

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#682]
As a new user, I'd like to be able to upload profile images. 

As an existing MicroMasters user, I can upload a new image to replace my image on Open.  

Invision Design at https://invis.io/J8KZT9PR5EN#/301346725_CropProfileImage

Zeplin styling at https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b22b71d0fd925e6553dc7f3

**Comment by pdpinch** [comment]
@roberthouse54 are there designs for this? What can we borrow from MicroMasters?

**Comment by pdpinch** [comment]
Waiting on final designs to be posted to Invision

**Comment by mbertrand** [comment]
@pdpinch @roberthouse54 is there an invision link I can look at to see the UI design?

**Comment by pdpinch** [comment]
It starts at https://invis.io/7XK8IN8W348#/301299124_Profile_Open_Drop_Down but it looks like we still don't have the image upload screens there.

**Comment by pdpinch** [comment]
Invision Design at https://invis.io/J8KZT9PR5EN#/301346725_CropProfileImage

Zeplin styling at https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b22b71d0fd925e6553dc7f3
