### ISSUE TITLE
Profile: Profile image model changes and API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#693]
As a user, I want to be able to upload a profile image.

As a micromasters user, I want to be able to use my MicroMasters profile image, or replace it with a new image (I don't need to undo this change) 

The current profile image fields are populated with URLs from MIcroMasters. We need to migrate these fields and their data to an updated model that allows the user to upload new files. Our goal is a similar user experience to MicroMasters. We can take the same approach as MicroMasters, but we should take a careful look at how it was implemented in case there is a better way. 

### acceptance criteria
- [x] existing users don't have to do anything, and their current profile images will continue to work
- [x] new micromasters users will still have their profile images filled when a discussions account is created for them
- [x] existing users can update their profile image
- [x] new users can upload a profile image
- [x] users who haven't uploaded a profile image get some kind of default image
- [x] we can support multiple image sizes
- [x] profile images can be served from a configurable CDN

**Comment by mbertrand** [comment]
@rhysyngsun @pdpinch Is it correct to assume that:
- discussions and micromasters should use separate CDN's (ie: S3 buckets/cloudfront URL's), so
- updating a profile image on discussions won't change the profile image on MM, and
- part of the migration (and creation of new discussions users) should involve copying over the images from MM to discussions so they are not using the identical image URLs.

**Comment by rhysyngsun** [comment]
I don't see anything wrong with those assumptions. I think the only thing is that we would need to decide if we copy the entire bucket over or if we only copy the ones discussions is aware of.

**Comment by rhysyngsun** [comment]
Although I guess that also sort of depends on our eventual goal to have open be the central user data point, so should we instead have both apps point to the same CDN/S3 bucket with the idea that Open eventually becomes the authoritative owner of that data and MM would relay through Open?

**Comment by rhysyngsun** [comment]
Additionally, I think this requirement:

> new micromasters users will still have their profile images filled when a discussions account is created for them

Will complicate the multiple-S3-bucket story, because we'll have to either a) have OD continuously copying the files from one bucket to another on user creation or b) have MM upload the files by way of the OD rest API (probably the better option design-wise since this same API can be used for end-users).

**Comment by mbertrand** [comment]
@rhysyngsun after talking with @pdpinch this morning, I've decided to try a different approach of leaving the existing fields as they are and adding new ImageFields, which will allow MicroMasters to keep continuing to create OD users & profiles without any changes :

```python
    image = models.CharField(null=True, max_length=MAX_IMAGE_FIELD_LENGTH)
    image_small = models.CharField(null=True, max_length=MAX_IMAGE_FIELD_LENGTH)
    image_medium = models.CharField(null=True, max_length=MAX_IMAGE_FIELD_LENGTH)

    image_file = models.ImageField(null=True, max_length=2083, upload_to=profile_image_upload_uri)
    image_small_file = models.ImageField(null=True, max_length=2083, upload_to=profile_image_upload_uri_small)
    image_medium_file = models.ImageField(null=True, max_length=2083, upload_to=profile_image_upload_uri_medium)
```

Then via a custom `Profile.save` method (or alternately a signal), transfer/convert the URL in the existing field to an image (if the corresponding `ImageField` value is `None`):

```python
    def transfer_image_url(self, image_prop):
        """
        Convert a URL in 'image', 'image_small', or 'image_medium' field to an image in corresponding
        'image_file', 'image_small_file', 'image_medium_file' field.
        Args:
            image_prop(str): The name of the property to check for and convert a URL.
        """
        img_url = getattr(self, image_prop)
        img_file = getattr(self, '{}_file'.format(image_prop))
        if img_url and not img_file.name:
            try:
                suffix = image_prop.split('_')[-1] if '_' in image_prop else ''
                parsed_uri = urlparse(img_url)
                if parsed_uri.netloc:
                    response = requests.get(parsed_uri.geturl(), timeout=10)
                    response.raise_for_status()
                    getattr(self, '{}_file'.format(image_prop)).save(
                        generate_filepath(parsed_uri.path, suffix).lstrip('%s/' % IMAGE_PATH_PREFIX),
                        BytesIO(response.content),
                        True
                    )
            except:  # pylint:disable=bare-except
                logger.exception('Error saving image from URL %s for profile %s', image_prop, self.user.username)
```

At some point in the future, Micromasters could be modified to update the `ImageField`s directly via the OD Profile API, at which point the original text fields could be removed.

**Comment by rhysyngsun** [comment]
@mbertrand @pdpinch 

Could I suggest an even simpler approach since it is less work (punting on the copying work) and gets us to profile image uploads on OD faster with less complexity (because we would really need to have that transfer code in an async task)?

### For now:
- Add the new image_file fields you're suggesting, profile uploads from OD itself can start to use this
- Update the API to use `image_file`, `image`, or the default image, in that order of fallback

### In the future
- Update MM to upload the file itself, so MM starts populating those fields instead
- Run a one-time script to transfer images for profiles that have `image` set but not `image_file`
- Remove the old columns and all usages

**Comment by mbertrand** [comment]
Thanks @rhysyngsun, sounds good to me!
