### ISSUE TITLE
As a logged in user, I want to be able to upvote posts

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#70]
On:

- Frontpage
- Channel page
- Individual post page

**Comment by rhysyngsun** [comment]
Partial work in [nl/channel_upvote](/mitodl/open-discussions/tree/nl/channel_upvote)

**Comment by pdpinch** [comment]
Does this include viewing the number of upvotes?

**Comment by rhysyngsun** [comment]
@pdpinch We already display the upvote count, but not an indication of whether your vote is included (probably we'd do this by showing the button as selected/highlighted).
