### ISSUE TITLE
UX for login page

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#700]
Flow at https://invis.io/FHJ8CLVVSBK#/298613522_MIT_OPEN_IAFLOW_052118-pdf_1

Designs are at https://invis.io/JCJ5RJK9RA2#/297321219_Log_In_Step_1
([project link](https://projects.invisionapp.com/d/main#/console/14225859/297321219))

### acceptance criteria
- [ ] user can login with email and password
- [ ] if user enters an address ending with `mit.edu` display message and ask them to login with Touchstone
- [ ] if user enters an address for an existing account (e.g. edX) display error and ask them to login with any connected social auth
- [ ] if email / password combo is unrecognized, display and error message

### out of scope (related issues)
- "reveal password" eyeball button 
- #701 sign up / "Make an account with the email above" 
- #721 forgot password
- #671 user can login with Touchstone
- #713 user can login with edX

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sign up / Log in from any page](https://trello.com/c/nJlUvlhX/40-sign-up-log-in-from-any-page)

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Various Error messages (open card to read checklist):](https://trello.com/c/KjxX8kBU/46-various-error-messages-open-card-to-read-checklist)

**Comment by pdpinch** [comment]
When there's a PR for this, can we try setting up a Review app, so we can get some eyes on the design and behavior before we merge?

I can take on the effort of working out the configuration and getting some test data in place.

**Comment by pdpinch** [comment]
I added a link to the [flow diagram](Flow at https://invis.io/FHJ8CLVVSBK#/298613522_MIT_OPEN_IAFLOW_052118-pdf_1) to the description.
