### ISSUE TITLE
UX for sign up page

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#701]
Flow at https://invis.io/FHJ8CLVVSBK#/298613522_MIT_OPEN_IAFLOW_052118-pdf_1

Designs are at https://projects.invisionapp.com/d/main#/console/14225859/297321219

### acceptance criteria
- [ ] sign up with email
- [ ] error message if account already exists with that e-mail: offer any existing auth methods
- [ ] minimal e-mail validation (@ sign and at least one dot? or can we do something real-time with mailgun?)
- [ ] send verification mail 
- [ ] when user verifies email request password, request full name, password and T&C agreement
- [ ] if verification has expired, display an error and allow user to send another verification email
- [ ] #676 minimal password validation: at least 8 characters?
- [ ] error message if T&C are not agreed to
- [ ] return user to page they were viewing, with a toast-like message

### out of scope (related issues)
- #700 UX for login page
- forgot password
- #671 user can sign up with Touchstone
- user can sign up with edX
- "reveal password" eyeball button

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sign up / Log in from any page](https://trello.com/c/nJlUvlhX/40-sign-up-log-in-from-any-page)

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Various Error messages (open card to read checklist):](https://trello.com/c/KjxX8kBU/46-various-error-messages-open-card-to-read-checklist)

**Comment by pdpinch** [comment]
When there's a PR for this, can we try setting up a Review app, so we can get some eyes on the design and behavior before we merge?

I can take on the effort of working out the configuration and getting some test data in place.
