### ISSUE TITLE
Fix intermittent JS test timeouts on travis

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#706]
The tests pass on rerun, but may initially fail due to timeouts, e.g.:

```
  459 passing (1m)
  2 failing
  1) PostPage
       should switch the sorting method when an option is selected:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at <anonymous>
  2) PostPage
       as a moderator user
         should report a comment:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at <anonymous>
```

**Comment by aliceriot** [comment]
we can probably avoid the issue by just raising the timeout time, but that's not optimal. we may want to do that as a stop-gap, but we should invest some more time in finding out why the tests are slow and trying to speed them up.

**Comment by pdpinch** [comment]
@noisecapella if you're working on this, please change the pipeline to in progress. If not, you should  unassign yourself.
