### ISSUE TITLE
If user lands on a page (channel, post) that requires a login, ensure they end up back on that page

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#709]
After logging in, the user should end up on the page they were trying to reach. This should more or less mean that we need to be sure to set `?next=X` wherever we're redirecting to login and that value is carried along our authentication flows.

**Comment by pdpinch** [comment]
@rhysyngsun why is this blocked by the JWT code?

**Comment by rhysyngsun** [comment]
@pdpinch it was mostly to avoid redoing work, but if folks are looking for stuff to do, we can simply roll that into the necessary work for that issue

**Comment by rhysyngsun** [comment]
Accidentally merged the PR
