### ISSUE TITLE
forgot password 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#721]
form: https://invis.io/RPJ8CFK4DY8#/298626349_Forgot_Password_Step_1

As a user who has forgotten their password (including users without a password), I'd like to be able to have a password reset link sent to my registered email(s). 

### acceptance criteria
- [ ] if email address is unrecognized, alert user to re-enter the e-mail
- [ ] email (template to be provided) includes one-time-use or a time-limited link to reset password (whatever is supported by social-auth / django)

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Various Error messages (open card to read checklist):](https://trello.com/c/KjxX8kBU/46-various-error-messages-open-card-to-read-checklist)

**Comment by pdpinch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Password reset request](https://trello.com/c/kDwXiK2r/47-password-reset-request)

**Comment by pdpinch** [comment]
Check with Nathan how much of the pipeline for this already exists. The biggest lift here should be just the form and the mail template.

**Comment by gsidebo** [comment]
How do we determine if an email address is 'unrecognized'?

**Comment by Ferdi** [comment]
@gsidebo as in : there is no account with this e-mail address

**Comment by gsidebo** [comment]
Got it. For some reason I interpreted that as an address that would fail if we attempted to send to it

**Comment by gsidebo** [comment]
Worth considering: Django's default password reset form does not show an error for unrecognized emails for a reason: https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.views.PasswordResetView

> If the email address provided does not exist in the system, this view won’t send an email, but the user won’t receive any error message either. This prevents information leaking to potential attackers. If you want to provide an error message in this case, you can subclass PasswordResetForm and use the form_class attribute.

**Comment by Ferdi** [comment]
@gsidebo we discussed about that a bit during the design process.   Not giving users any feedback is not a great user experience.  I think we should do if it's not too much work.
