### ISSUE TITLE
Update grid, drawer, top nav

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#724]
As a design itertion towards "open" we would like to update the grid, drawer behavior and the top nav in Discussions. 

See https://invis.io/S5KQD8JAPTD#/298453914_Intermediate_Logged_Out

### acceptance criteria
- [x] #679 move user menu to top right (logged in user only)
- [x] Remove "> Discussions" from top nav
- [x] move "Submit a New Post" button into the drawer (logged in user only)
- [x] add a home button to the drawer (links to / )
- [x] drawer behaves similar to https://youtube.com
  - [x] at widths greater than appx 1280, drawer defaults to open, shifting grid to the right
  - [x] at narrower widths, automatically close the drawer and grid resizes
  - [x] when the user opens the drawer at width < 1280, it opens above the grid

### out of scope
- channel icons
- final styling (fonts and colors)

**Comment by pdpinch** [comment]
When there's a PR for this, can we try setting up a Review app, so we can get some eyes on the design and behavior before we merge?

**Comment by aliceriot** [comment]
@pdpinch should I try to make all of these changes in one PR? I think it could end up being fairly large if I did, but if we wanted to review the whole design before it went out I'd need to do that or do something like open multiple PRs against like a `frontend-redesign` branch which we could merge into `master` only when we're happy with the whole thing

**Comment by pdpinch** [comment]
That's a good question. 

Branches make me nervous, but I can't think of a way to make this work with a feature flag. 

If you do it as a series of PRs to a feature branch, how many / how long do you think it would take? Of the options, I'm leaning towards this.

**Comment by aliceriot** [comment]
I talked to Ferdi and he thought it would be best to just go ahead and do the work in separate PRs

**Comment by aliceriot** [comment]
I don't think any of the planned changes will be very disruptive or different on their own, so that makes sense to me

**Comment by pdpinch** [comment]
That would certainly be easier. I'd still like to try getting a review app set up, so let me know when a PR is ready.

**Comment by aliceriot** [comment]
For removing '> Discussions' from the toolbar, should the `Micromasters` link still link out to micromasters?

**Comment by pdpinch** [comment]
Yes, for now. IIRC, that link leverages a value in the django site settings?

**Comment by aliceriot** [comment]
yep, that's right

**Comment by pdpinch** [comment]
So, I thought you were going to do this in multiple PRs, but it looks like it all went in to #736? At least, everything appears checked off to me. 

There is one issue though -- there are now *two* user profile images, one on the left and one on the right. 

I'll close this issue and open another issue for the duplicate user profile image (as a bug).

**Comment by aliceriot** [comment]
ok, so based on discussing more what we want to change this is my understanding of what we want to do. We want to change the drawer / navigation setup from what we're currently using to:

- at small screen widths use what material calls a 'temporary drawer' (one which slides in the from left and sits above all content on the site)
- at larger screen widths we want to use a 'persistant drawer' (which slides in from the left but pushes the page content over). we want to default this to open, but we want to present the user with the option to close it.

Currently we're using the temporary drawer at small screen widths. We'll need to add a new component to be an implemented for the persistent drawer. We'll most likely have to end up using both drawers on the screen at the same time, and just hide the one we don't want to see via css or something.

**Comment by aliceriot** [comment]
the drawer components that Material has can be demoed here: https://material-components.github.io/material-components-web-catalog/#/component/drawer

**Comment by pdpinch** [comment]
The Invision Link in the description isn't working anymore, so I replaced it with a new one to the "MIT Open Prod" project.
