### ISSUE TITLE
WYSIWYG editor for basic posts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#725]
As a user, I'd like to be able to author basic posts with a WYSIWYG editor. 

As a developer, I'd like to store post texts as markdown, as we do currently. 

We'll try using [prosemirror](https://prosemirror.net/) 

### acceptance criteria:
- [x] bold
- [x] italic 
- [x] links
- [x] list 
- [x] quote (likely needs add'l styling for rendering)

### related issues
- WYSIWYG editor for comments

**Comment by aliceriot** [comment]
Along with implementing the editor for post creation, should I go ahead and switch over to using it for post editing and comment creation as well?

**Comment by pdpinch** [comment]
Nice. I have some questions:

Is it hard to move it below the text field?

What does the <> button do if we're storing markdown?

Can we omit the "insert" menu (assuming it's inserting images), at least for now?

What's the last icon for?

**Comment by aliceriot** [comment]
I think it won't be too hard to move it below the text. currently I'm using a pre-made menu bar, if we want to customize it I'll need to make our own but I think it shouldn't be too bad if I use the pre-made one as a reference. The `<>` button makes a code block.

If we decide to do our own menu bar we can easily omit the 'insert' menu. The last icon is for 'select parent' - i'm not sure exactly why that's useful, haha.

**Comment by aliceriot** [comment]
Are these the final buttons that we want to have in a menu bar?

![fjfjfjfasdfncncmd](https://user-images.githubusercontent.com/6207644/43146229-cd6e53c8-8f2e-11e8-9291-8d587930b4a8.png)

I don't think we can do the text alignment ones without some sort of change on the backend, because there is not support in Markdown for aligning text like that (i.e. left-justified, right-justified, etc).

**Comment by Ferdi** [comment]
@aliceriot , only the ones listed in the acceptance criteria, for now.

**Comment by aliceriot** [comment]
ok cool

**Comment by aliceriot** [comment]
is there a design anywhere for what the link insertion should look like? If not I can make something up, haha

**Comment by Ferdi** [comment]
@aliceriot good point we forgot about that.  Can you do something similar to google doc link ?

**Comment by aliceriot** [comment]
sure
