### ISSUE TITLE
Add "restricted" to permitted channel types

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#726]
Add this as a new allowed type as it's already supported in reddit natively: https://github.com/mitodl/open-discussions/blob/master/channels/constants.py#L5-L11

**Comment by pdpinch** [comment]
Just to double-check, "restricted" means that anyone can view the channel (it's "public") but only contributors can post?

**Comment by pdpinch** [comment]
And I assume we can use the existing `add_contributors` API to add users who can post to the channel?

**Comment by rhysyngsun** [comment]
@pdpinch correct on both counts

**Comment by pdpinch** [comment]
@noisecapella I think you told me you did this as part of #830
