### ISSUE TITLE
Remove legacy support of JWT tokens in frontend

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#727]
Once #699 is deployed to production and https://github.com/mitodl/micromasters/issues/3988 is done, we can remove support for jwt tokens in the frontend. 

Specifics:

- [x] Remove logic that renew the JWT
- [x] Update the link on `/auth_required/` to go to `/login` instead

**Comment by rhysyngsun** [comment]
I actually figured out how to unblock this by making the redirect url conditional on `allow_email_auth` setting.
