### ISSUE TITLE
subscribe users to default channels

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#75]
As a new user, when I create an account, I want to be able to see the basic discussion content. I will need to be automatically subscribed to the basic set of channels. 

This is a configuration option in reddit. For now, we'll just configure this as a deployment task.

**Comment by rhysyngsun** [comment]
How are default channels defined? Are we using reddit's concept of default channels where they subscribe the user to a set of default channels at signup and if the default list changes the user's subscriptions are unaffected or is it something else?

**Comment by blarghmatey** [comment]
I have created a new Reddit instance located at https://open-discussions-reddit.odl.mit.edu and created 3 subreddits (/r/podcastinit, /r/dataengineering, /r/odlengineering) and set the podcastinit and dataengineering subreddits as the values to the `automatic_reddits`. This means that when new users log in they should see both of those subreddits/channels in their list.

**Comment by pdpinch** [comment]
How can I confirm this?

**Comment by rhysyngsun** [comment]
See https://github.com/mitodl/refresh_token/pull/5
