### ISSUE TITLE
Remove duplicate profile image, settings link

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#761]
In #736 we added a new user menu to the top right, but the old features (user profile image, settings link) still exist in the old drawer. They should be removed. 

![screenshot-discussions odl mit edu-2018 06 04-09-18-53](https://user-images.githubusercontent.com/430126/40919857-cccb4552-67d8-11e8-8816-a065fc29d692.png)

**Comment by aliceriot** [comment]
What should we do about the red dot for an incomplete profile? Currently it's only implemented in the nav bar, it would be trivial to move it over to the new user menu but I just wanted to be sure that's what we want to do.
