### ISSUE TITLE
Better mobile layout for channels

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/open-discussions#764]
The mobile layout has too much padding, and is cluttered because of the user image. We should remove the image and tighten up the padding considerably.

![40191196-b58c6fa0-59ce-11e8-8259-04e6bd120042](https://user-images.githubusercontent.com/20047260/40924613-b2f0c53c-67e5-11e8-84fe-5bb51e4fb81c.png)

**Comment by pdpinch** [comment]
addressed by #1153
