### ISSUE TITLE
List Page: Updates to cards for posts 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#776]
See https://invis.io/CTLC400X932#/301261181_Home_Nav_Drawer_Open

Zeplin: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b181e38cc5680ae11702acf

### acceptance criteria
- [x] remove user profile image
- [x] restyle text
- ~~restyle vote button / vote count~~
- [x] restyle comment button / comment count
- [ ] any click on the card opens the detail view (except clicking on the "new window" icon)
- [x] overflow menu for remaining buttons

### related issues (out of scope)
- user "headline" (e.g. "UCLA Post-doc Physics")
- Display thumbnail image for link-type posts that have thumbnails
- restyle vote button / vote count

**Comment by pdpinch** [comment]
Here's the Zeplin link for CSS: https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b181e38cc5680ae11702acf

let me know if that works.

**Comment by aliceriot** [comment]
yep!

**Comment by pdpinch** [comment]
@aliceriot one change to the acceptance criteria on this: you can keep the existing upvote button. 

The new version isn't final, so we don't want to waste time changing it now.

**Comment by aliceriot** [comment]
cool, glad I didn't start on that yet, haha

**Comment by aliceriot** [comment]
ok, I have a kind of 'first draft' of this together, we don't yet have the stuff in place to show an image so I haven't worked on that yet:

![first_draft](https://user-images.githubusercontent.com/6207644/41743081-ea636c82-756d-11e8-8d84-2b7b5d9becde.png)

**Comment by pdpinch** [comment]
This is looking pretty good. 

Is the Zeplin thing helping? I ask because some of the spacing and margins seems a little off, which I thought would come straight from Zeplin. Things like the spacing between the comment button and the comment count and the left and right margins. Nothing major. Definitely tweak-y stuff.

**Comment by aliceriot** [comment]
It's mainly helpful with colors, with spacing and stuff it's not super straightforward to directly copy it over

**Comment by aliceriot** [comment]
that image is also before I went back for a final round of polishing things up, here's what it looks like now:

![postlistdisplay](https://user-images.githubusercontent.com/6207644/41797604-b124b586-7638-11e8-8fa7-253c999b9c71.png)

![postlistdisplaymobile](https://user-images.githubusercontent.com/6207644/41797611-b42364f8-7638-11e8-8c97-63e8f18ad1a6.png)

**Comment by aliceriot** [comment]
The spacing and stuff? Mainly it comes down to sort of measuring the pixels between things on zeplin and translating that over to the React component. It doesn't always map cleanly, though, because sometimes we can't lay out the HTML in a way that directly corresponds with the things in Zeplin - I do think it's helpful though, provided it isn't too much work to get the design in there in the first place.
