### ISSUE TITLE
List View: display images for link posts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#778]
### acceptance criteria:
- [ ] store the url of thumbnail images returned by embedly service
- [ ] resize images as necessary
- [ ] consider how thumbnail images will work in search results 
- [ ] if there is no thumbnail, display nothing (e.g. if the site is password-protected)

**Comment by blarghmatey** [comment]
Yes, we can securely expose the routes if they exist. The scraper service is running on the instances, so the link data should be getting retrieved for use.

**Comment by pdpinch** [comment]
blocked waiting for our discussion with embed.ly and then subsequent decisions about caching image URLs and image data.

**Comment by mbertrand** [comment]
@pdpinch @roberthouse54 what is the preferred thumbnail size for link posts in list view?  Is there a screenshot in Invision?

**Comment by pdpinch** [comment]
Did you get it from Zeplin?

**Comment by mbertrand** [comment]
I saw the design in Zeplin.

**Comment by Ferdi** [comment]
@mbertrand Now that we decided to use embedly display api, the description of this issue seems out of date. It suggests that we are downloading the images and saving them ourselves.  @pdpinch

**Comment by pdpinch** [comment]
I removed the acceptance criteria about CDN (that was written before we decided to use the embedly API)

**Comment by mbertrand** [comment]
@pdpinch @Ferdi embedly provides a fallback option to display a default thumbnail if the request fails (for instance if the image is no longer available), seems like a good idea to take advantage of this - is there a particular default image that should be used in this case?

**Comment by Ferdi** [comment]
If it's easy for you ignore it for now. It will take time until we agree on an image to use :-)

**Comment by pdpinch** [comment]
I updated the description to address [Matt's question about a fallback](https://github.com/mitodl/open-discussions/issues/778#issuecomment-406649269). If there is no thumbnail image, we'd like to display nothing.
