### ISSUE TITLE
Use existing code to serialize posts/comments for the ES index

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#790]
We created new serialization functions for posts and comments while working on the search feature. Turns out those serializers already exist [[1](https://github.com/mitodl/open-discussions/blob/master/channels/serializers.py#L88)][[2](https://github.com/mitodl/open-discussions/blob/master/channels/serializers.py#L279)]! We should get rid of those search-specific ones and change the search logic to use the previously-existing ones.

**Comment by pdpinch** [comment]
I was planning to have a quick chat with @noisecappella and you about this, but I don’t know when we’ll have time and apparently we’re still digging a deep hole (#809). 

Unless there’s a good reason to keep these separate, we should just go ahead and refactor these into one. 

How do we avoid this in the future?

**Comment by gsidebo** [comment]
@pdpinch A few notes about this issue:

1. There actually is _some_ sense in keeping these serializers separate. The serialized ES document does differ in some necessary ways from the serialized objects we feed into the front end. For example, we serialize values like `comment_id` and `post_id` instead of just `id` for the search index. It just seems to make _more_ sense to use the same serializer and modify the results to the object required by the ES index.
1. I would consider this to be very low risk. I can see two main ways that this could be a real problem: (1) the structure of the actual reddit objects change, or (2) the front end makes assumes a certain document structure and we cause an error by changing one serializer and not the other. [1] basically can't happen, as we know. [2] is more likely, but as mentioned above, there is already a difference between the two types of objects. We were always going to have to account for _some_ difference in the structures of those objects either in the back end or front end.
1. This is a pretty straightforward fix. It was simple to write these redundant serializers and it will be simple to change them over to the existing one as well.

So overall I consider this relatively low cost and low risk tech debt, but I'll give some thought to how we can avoid this in the future.
