### ISSUE TITLE
As a logged in user, I'd like to be able to view a list of channels that I'm subscribed to

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#83]
In the current screen designs, this is implemented as a left-hand sidebar that collapses to a menu in mobile. 

### acceptance criteria
- [x] REST API for list of subscribed channels
- [x] simple HTML rendering of list
- [ ] CSS will be addressed in #85 

Desktop:
<img width="239" alt="screenshot 2017-08-01 09 29 33" src="https://user-images.githubusercontent.com/430126/28827586-12484118-769c-11e7-9c71-bbacf05b6477.png">

Mobile:

<img width="239" alt="screenshot 2017-08-01 09 30 26" src="https://user-images.githubusercontent.com/430126/28827590-15b83c5e-769c-11e7-88a5-90ec55c098a6.png">

**Comment by pdpinch** [comment]
@noisecapella now that #90 has merged, what remains to be done here?

**Comment by noisecapella** [comment]
CSS Styling

**Comment by pdpinch** [comment]
Has it been deployed to odl-open-discussions-ci? I see a "Home" header, but no list. But maybe that's because of #57?

**Comment by pdpinch** [comment]
Since the styling is in a separate issue, I think we can close this.
