### ISSUE TITLE
Gravtar integration

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#833]
As a user, I'd like to save time uploading a profile image by using my existing gravatar image. 

### acceptance criteria:
- [x] By default use the gravatar image as the user’s profile image
- [x] If gravatar not found, use the initials
- [x] allow the user to upload a new image and override the gravatar

**Comment by mbertrand** [comment]
@pdpinch should the existence of a gravatar image be checked for only when the profile is created?
