### ISSUE TITLE
Fix window width-based UI quirks in the top bar and drawer 

### ISSUE THREAD

**Issue by gsidebo** [mitodl/open-discussions#844]
There are a couple UI quirks going on with the top bar and the drawer depending on the browser window width:
1. When the window is between 950-960px, there is a gap between the drawer content and the top bar
    
    ![ss 2018-06-20 at 11 15 33](https://user-images.githubusercontent.com/14932219/41674613-8e0fffe8-748e-11e8-9ba1-215c745abb33.png)
2. The padding in the top bar somewhat arbitrarily changes at different widths. There is extra padding >960px, then it is removed until 850px when it is added again, then it is removed again at 600px.
    
    &gt;960px - added padding
    ![ss 2018-06-20 at 13 41 32](https://user-images.githubusercontent.com/14932219/41675115-d05890bc-748f-11e8-9ce7-574b4f5a0c35.png)
    850-960px - padding removed
    ![ss 2018-06-20 at 13 41 44](https://user-images.githubusercontent.com/14932219/41675158-efdd1c64-748f-11e8-8417-ebd7f44fc4f2.png)
    600-850px - padding added again
    ![ss 2018-06-20 at 13 42 05](https://user-images.githubusercontent.com/14932219/41675179-fe026ca4-748f-11e8-87d3-42c463dbbcec.png)
    &lt;600px - padding partially removed again (see above the user image thumbnail)
    ![ss 2018-06-20 at 13 42 26](https://user-images.githubusercontent.com/14932219/41675191-03175ac4-7490-11e8-9b08-e5911df31da2.png)

**Comment by aliceriot** [comment]
what browser do you see this on? I can't repro this on Chrome

**Comment by gsidebo** [comment]
Just checked it out on master again. This must have been fixed since I last checked out master. Nevermind!
