### ISSUE TITLE
CSS Styling 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#85]
Based on the designs in Invision:

- [x] Basic fonts, colors, and styling for Channel pages, post summaries, and post content. (Addressed in #95
- [x] Styling for the sidebar with the channels and the "Submit Post" button.
- [x] Styles for the Create Post page ~~and the Create Channel page.~~
- [x] HTML and CSS for a navbar, assuming we are going to have one.
- [x] Styling for the comments UI.
- [x] #115 Responsive CSS for mobile for all of the above.

**Comment by roberthouse54** [comment]
Work that needs to be done:
- Basic fonts, colors, and styling for Channel pages, post summaries, and post content. (Addressed in https://github.com/mitodl/open-discussions/pull/95
- Styling for the sidebar with the channels and the "Submit Post" button.
- Styles for the Create Post page and the Create Channel page. 
- HTML and CSS for a navbar, assuming we are going to have one.
- Styling for the comments UI. 
- Responsive CSS for mobile for all of the above.

**Comment by aliceriot** [comment]
I'm going to work on #115, just basically getting the spacing, width, etc set-up so the site will work on a phone.

**Comment by aliceriot** [comment]
Opened a few issues (which I'll work on) for small issues that Rob has noticed:

- #123 
- #125
- #126
- #127

**Comment by pdpinch** [comment]
"Create Channel" isn't part of the open-discussions app. There's an issue for it at https://github.com/mitodl/micromasters/issues/3473. I've updated the description of this issue.

**Comment by aliceriot** [comment]
There is a 'create channel' page in the OD admin (`/manage/channel/new`)
