### ISSUE TITLE
SEO: add slug to post detail URL

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#865]
As a search crawler, I expect relevant keywords in the URL

### acceptance criteria
- [ ] slugify the post title
- [ ] append slugified title to existing URL (i.e. keep reddit id in URL)
- [ ] all internal links and permalinks should include the slugified title in the URL

**Comment by mbertrand** [comment]
@pdpinch should the slug be in post comment URL's as well?
https://.../channel/everybody/1sqc/comment/3fcw/  -->
https://.../channel/everybody/1sqc/<post_slug>/comment/3fcw/

**Comment by pdpinch** [comment]
I chatted with Ferdi. We'd like the comment URLs to get an SEO bump too, so let's keep the post slug in the comment URL as well (i.e., choice 2)
