### ISSUE TITLE
replace `channel` in page URLs with `c`

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#867]
In order to shorten URLs, and allow us more flexibility about UI labelling, we'd like to obscure the "channel" in page URLs. 

No need to change API URLs.

**Comment by mbertrand** [comment]
@pdpinch what about channel management & moderation URL's?
http://.../manage/channel/edit/public20180613a/basic
http://.../moderation/channel/public20180613a

**Comment by pdpinch** [comment]
ideally, they should be changed too. Are they more complicated than the rest? 

I'm a little surprised by the sequence of items in the path. I think I would have put manage and moderate after channel, in which case they would't be such a special case. But that seems like a bigger change.
