### ISSUE TITLE
display user initials instead of anonymous avatar in email notifications

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#868]
Compare: 

![screenshot 2018-07-03 11 31 55](https://user-images.githubusercontent.com/430126/42229546-b66ea432-7eb4-11e8-9605-5a98856deb9a.png)
from https://discussions.odl.mit.edu/channel/DEDP/eq/

and:

![screenshot 2018-07-03 11 32 44](https://user-images.githubusercontent.com/430126/42229593-d14cc90a-7eb4-11e8-8f36-ffafbe4a24b1.png)

### related issues:
- # display user initials instead of anonymous avatar in widget on micromasters portal

**Comment by mbertrand** [comment]
Already seems to be working on discussions-rc:

<img width="1040" alt="screen shot 2018-07-31 at 4 12 37 pm" src="https://user-images.githubusercontent.com/187676/43484611-cf9673ac-94dc-11e8-886f-1fbf0f27bac2.png">

**Comment by pdpinch** [comment]
This is also working in production.
