### ISSUE TITLE
Add check for matching Channel object in permission classes

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#894]
This would make sure that only channels which the discussions server knows about are accessible

**Comment by pdpinch** [comment]
Would this also fix #741 "don't throw 500 when channel doens't exist" ?

**Comment by noisecapella** [comment]
Yes I think these cover the same problem

**Comment by mbertrand** [comment]
@pdpinch @noisecapella  do you want this check in the permission classes so that the user sees `You do not have permission to view this page` for an invalid channel name?  Or do you want the user to get a 404 page?
