### ISSUE TITLE
Display an error when posting to reddit fails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#911]
Currently on CI when a post to reddit fails, the user is returned to the channel listing page, without any clue of what happened. We need to return an error to the user, and also raise an exception to Sentry so we can fix the underlying problem.

**Comment by pdpinch** [comment]
Maybe a sentry error was thrown? See https://sentry.io/mit-office-of-digital-learning/discussions/issues/607939636/?query=is:unresolved

**Comment by pdpinch** [comment]
Sentry issue: [DISCUSSIONS-8X](https://sentry.io/mit-office-of-digital-learning/discussions/issues/607939636/)

**Comment by mbertrand** [comment]
@ferdi a snackbar message is temporarily displayed if something goes wrong with creating a new comment ("Unknown error replying to comment").  Do you also want a snackbar message if something goes wrong creating a new post (message: "Unknown error creating post"), and leave the user on the post form page?

Comment error:
<img width="463" alt="screen shot 2018-08-10 at 10 03 05 am" src="https://user-images.githubusercontent.com/187676/43962102-cc19767a-9c84-11e8-8575-ae913cc4b21b.png">

Proposed post error:
<img width="460" alt="screen shot 2018-08-10 at 10 04 01 am" src="https://user-images.githubusercontent.com/187676/43962105-cdf80600-9c84-11e8-88f3-0740510dd06c.png">

**Comment by mbertrand** [comment]
Thanks Ferdi, I'll go with the banner.

**Comment by mbertrand** [comment]
@Ferdi @pdpinch to make handling of errors when creating comments and posts more consistent, what do you think of:

- [ ] Changing the comment error display to use a banner instead of a snackbar
- [ ] Using an error message of "Unknown error creating [comment|post], please try again"

**Comment by mbertrand** [comment]
@pdpinch while testing comment errors I noticed that if something does go wrong, the post detail page is replaced with an error page ("Error loading page"), on which the banner (or the snackbar on master branch) message appears.  Is this expected behavior or should I create a new issue for it?

**Comment by mbertrand** [comment]
https://github.com/mitodl/open-discussions/issues/1069

**Comment by pdpinch** [comment]
In response to your [questions above](https://github.com/mitodl/open-discussions/issues/911#issuecomment-412875630)

- Definitely a banner
- Ideally I'd like some more user friendly, like "Something went wrong creating your [comment|post]. Please try again or contact us at [support email address]."
