### ISSUE TITLE
Detail page: Improvement related to embedly cards

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#925]
Based off of [embedly cards](https://embed.ly/code?url=http%3A%2F%2Fwww.nytimes.com%2F2015%2F10%2F23%2Fopinion%2Flady-gaga-and-the-life-of-passion.html), see https://invis.io/CQMZNZ5D5EW

### acceptance criteria:
- [x] display site name, above the thumbnail (favicon not required)
- [x] don't display the author (seems to be used inconsistently) 
- [x] Link to site (where appropriate) below the thumbnail image 
- [x] if the thumbnail is large enough, use the full width of the post, with text below
- [ ] If the thumbnail is too small (e.g. [OCW](https://embed.ly/code?url=https%3A%2F%2Focw.mit.edu%2Fcourses%2Felectrical-engineering-and-computer-science%2F6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013%2Findex.htm%3Futm_source%3DOCWDept%26utm_medium%3DCarouselSm%26utm_campaign%3DFeaturedCourse)), do the image side-by-side with the text excerpt

**Comment by aliceriot** [comment]
google translate tells me that 'lees dit op $URL' means 'read this on $URL', is that what we should go for for the copy for the 'read more' link?

**Comment by aliceriot** [comment]
or maybe 'read more on $URL'? not sure what the best preposition is, on? at? haha

**Comment by pdpinch** [comment]
I don't think I'd trust Google translate on prepositions in this case... 

The embed.ly example card uses "Read the article on $URL" -- I think "Read this on $URL" is a little better, since not everything will be an article. 

![screenshot 2018-07-19 15 12 46](https://user-images.githubusercontent.com/430126/42964891-66ee2b58-8b66-11e8-8681-8bdd5cde494d.png)

**Comment by aliceriot** [comment]
Ok, I'll go with that :+1:
