### ISSUE TITLE
Post form: save link to thumbnail image

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#926]
When a user posts a link, we should store a link to its thumbnail image for later use, like for building list views and for displaying search results

### acceptance criteria:
- [x] add a thumbnail field to the post model
- [x] When the results of the embed.ly API are returned, store a link to the thumbnail
- [x] when adding the post to the search index, include the thumbnail link
- [x] #778 When displaying the post in a list view, use the [embed.ly display API](https://embed.ly/docs/explore/display/resize) to resize the thumbnail appropriately

### out of scope
- image caching
- CDN

We considered some options for caching the image and/or the resized image, but at this time it seems simplest to just use the embedly display API, which uses a CDN to deliver resized images. If we start approaching the month limit of 25,000 display API requests, we may reconsider this.

**Comment by mbertrand** [comment]
@pdpinch The url for an embedly resized image includes the API key, which should not be exposed on the front end:  `https://i.embed.ly/1/display/resize?key=<api_key>&url=<image_url>&width=<pixels>&height=<pixels>`

We could have a Django view that makes the request to embedly on the backend and passes on the response to the frontend.  This will hide the API key but add some performance overhead (client -> backend -> embedly -> backend -> client).  Or the embedly response could be saved to our own CDN (Cloudfront) and that URL could then be used instead, but this issue mentions that the CDN is out of scope for now.

**Comment by pdpinch** [comment]
Embed.ly doesn't have any other authentication mechanism, like JWT? 

I could ask if there's some approach we would like.

**Comment by pdpinch** [comment]
What do you mean by saving the "embedly response" ?

> Or the embedly response could be saved to our own CDN (Cloudfront) and that URL could then be used instead, but this issue mentions that the CDN is out of scope for now.

**Comment by mbertrand** [comment]
embed.ly's authorization options are either [a key in the url or oauth](https://docs.embed.ly/docs/authentication).  Currently the embedly requests are [routed through the backend](https://github.com/mitodl/open-discussions/blob/master/embedly/api.py#L9), hiding the key from the frontend.   Might be able to use referrer whitelisting to safely expose the key on the frontend.

By saving the embedly response, I mean saving the resized image generated by embedly to Cloudfront and using that URL instead.

**Comment by pdpinch** [comment]
FWIW, embed.ly has sample code that includes the key in front-end javascript.... 

If you turn on referer whitelisting, what does it do if there is no referer passed? (something the paranoid internet users do)

**Comment by mbertrand** [comment]
If whitelisting is turned on, and there is no referrer passed, then the API should respond with a 403 error.

**Comment by mbertrand** [comment]
"[ ] When the results of the embed.ly API are returned, store a link to the thumbnail"

The initial call to embedly is made before the post is saved (to reddit or to django), so there is nowhere to save it to yet, but I can add the embedly thumbnail URL to the post form data state.  

When a new post is submitted, it is initially saved to reddit only.  Although a praw reddit object includes a `thumbnail` attribute, there does not appear any way to set that attribute when creating or updating that object via the praw API.  

A celery task `channels_task_helpers.sync_post_model` syncs the reddit post with the django database (ie creates a `Post` model object) and another task `search_task_helpers.index_new_post` syncs it with elasticsearch.  Both tasks are passed the newly created reddit object (with no thumbnail).  

Embedly could be called again to get the thumbnail and save it for each link post, though this doesn't seem very efficient.  

Another option is to pass on the embedly thumbnail url to the celery tasks in addition to the reddit object (as a tuple), which is the approach I'm testing out at the moment.  @noisecapella do you think that makes sense?

**Comment by mbertrand** [comment]
PS Another approach would be to create a new `URLThumbnail` model with attributes `post_url` and `thumbnail`.  The post's url could be used to look up the correct URLThumbnail object if any.

**Comment by mbertrand** [comment]
Going with the `LinkThumbnail` approach

**Comment by Ferdi** [comment]
@aliceriot do we need to save the image dimensions as well ?

**Comment by noisecapella** [comment]
@mbertrand Feel free to move the creation of the `Post` out of the celery task if it's useful. I needed to do something similar for `Channel`

**Comment by mbertrand** [comment]
@pdpinch should thumbnails be bulk retrieved, saved & indexed for all pre-existing link posts?  Or just let that happen gradually over time as users view the posts and trigger embedly?

**Comment by pdpinch** [comment]
Which requires more new code? Are you already updating the thumbnail whenever embedly is called?

**Comment by mbertrand** [comment]
Adding thumbnails to old link posts in bulk would require some more new code.  

The thumbnails should be saved when embedly is called if they don't already exist (and with a slight tweak could be updated with the latest thumbnail if they do exist).

**Comment by pdpinch** [comment]
I think that should be fine then, as long as the list view behaves itself (i.e. no broken thumbnail image, but omitted images OK)

I don't think we have a large number of these in production that weren't just tests.

**Comment by pdpinch** [comment]
@mbertrand can this be closed?

**Comment by mbertrand** [comment]
@pdpinch sure as long as it's ok for the last checkbox (#778) to still be in progress.

**Comment by pdpinch** [comment]
I thought I had written those as independent issues. I'll be patient then.
