### ISSUE TITLE
Navigation: Sections for "Channels you moderate" & "Channels"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#928]
As a channel moderator, I'd like an easy way to see which channels I am a moderator on and which channels I'm subscribed to. 

In the navigation, add a section for "Channels you own" (channels for which the current user is a moderator) and a section for "Channels" (the channels to which the current user is subscribed). For "Channels you own" there should also be a gear icon for each channel which links to the channel settings interface. 

See https://invis.io/9EN908ZQPAX#/311617712_Channel_Settings_Entrance

### acceptance criteria:
- [ ] move 'Submit a new post' button below the home tab

### out of scope
- sorting channels in the navigation

**Comment by rhysyngsun** [comment]
@pdpinch how are we defining a channel owner?

**Comment by Ferdi** [comment]
@rhysyngsun    I think it means "as a channel moderator / administrator"

**Comment by rhysyngsun** [comment]
Ok, good, we already have that if that's the case, just wanted to be sure since "owner" was new nomenclature.

**Comment by pdpinch** [comment]
Sorry, we discussed this in planning, but I didn't write it down. I've updated the description now.

**Comment by pdpinch** [comment]
I fixed the broken InVision link in the description and changed the "gear icon" to an "edit button"

**Comment by noisecapella** [comment]
Can you fix the inVision link again?

**Comment by noisecapella** [comment]
How should we sort the channels in the list, or is that out of scope?

**Comment by pdpinch** [comment]
Sorting of channels is out of scope. For now we'll have so few that the default sort will be acceptable.
