### ISSUE TITLE
Login: display an error message when email isn't recognized

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#931]
When a user is logging in and we don't recognize their email address, we can simply display a validation error on the login form, instead of going to another form.

**Comment by rhysyngsun** [comment]
@pdpinch to clarify, does this basically mean we are doing away with this page from our mockups (https://projects.invisionapp.com/d/main#/console/14225859/297321221/preview) and instead displaying a validation message and requiring the user to manually navigate to /register and re-enter their email address to begin the registration process?

**Comment by pdpinch** [comment]
Sorry, I thought I had answered this earlier. 

That's correct. It's more like a validation error message than a new form. 

I don't think "requiring the user to manually navigate to /register" isn't any more onerous than requiring them to click a button to create a new account.
