### ISSUE TITLE
Login: display email field on /login/password form 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#934]
Keep the email field on the password screen, similar to the [firebase demo](https://fir-ui-demo-84a6c.firebaseapp.com/)

**Comment by rhysyngsun** [comment]
@pdpinch questions:

- Is the idea that we still validate the email address prior to showing the password field?
- Do we want the email address editable like in the demo? (we'll what this means to switch the user for an in-flight PSA auth, or if we should just start a new flow and replay the inputs)

**Comment by pdpinch** [comment]
Yes, we still want to validate the e-mail so we can redirect users with an incorrect email or an email that matches an external social auth (like MicroMasters or Touchstone).

It would be nice to allow editing, but if it's easier to make it read-only that would be OK with me.

**Comment by Ferdi** [comment]
@pdpinch what is this issue about ?

**Comment by pdpinch** [comment]
In the current implementation, login with email & password looks like this:

1. 
![screenshot 2018-07-19 15 23 40](https://user-images.githubusercontent.com/430126/42965401-e1a6e816-8b67-11e8-94ea-c4af29d339f6.png)

2. 
![screenshot 2018-07-19 15 23 52](https://user-images.githubusercontent.com/430126/42965404-e5a96da8-8b67-11e8-9adf-9e406fdb8a57.png)

On the 2nd screen, you had asked that the email still be visible. Moreover, it should behave more like the user is still on the same form.
