### ISSUE TITLE
Handle case where user wants to remove themself as a moderator

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#938]
I'm not sure what the design should be otherwise but at least we should redirect the user back to the channel page.

See https://invis.io/9EN908ZQPAX#/311617721_Channel_Settings_Members

**Comment by pdpinch** [comment]
These is a design now in InVision: https://invis.io/FBI9T9AJS3Y#/311010836_Settings__Channel_Roles_inline_Copy_5

**Comment by pdpinch** [comment]
Updated description with link to InVision: https://invis.io/9EN908ZQPAX#/311617721_Channel_Settings_Members
