### ISSUE TITLE
Home: anonymous user

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#948]
As an anonymous user, I'd like to see posts on the home page from all the public channels. I'd also like to be able to create an account. 

~~If our reddit supports an r/all endpoint, we can use that.~~ We'll try using the existing reddit default channel functionality so anonymous users can see public channels. 

The "Become a Member" button should be behind the same feature flag that controls creating email accounts.

See mock-ups at https://invis.io/9EN908ZQPAX#/311617690_Home_Not_Logged
Desktop CSS at https://zpl.io/2EAZJpY
Mobile at https://zpl.io/ad7AKeL

### acceptance criteria
- [ ] For anonymous users, display posts from all public channels

### out of scope
-  "discover" button: this is displayed only to logged in users
-  "Learn, Share, Connect" intro text
- "Become a Member" button (behind feature flag) 
-  Without the feature flag, continue to direct anonymous users to log in with MM (i.e. /auth_required/ )

**Comment by pdpinch** [comment]
I fixed the broken InVision link in the description, but the Zeplin links are still broken.

**Comment by rhysyngsun** [comment]
@pdpinch This should be solved in one go with the default channels, which also accomplishes part of #75

**Comment by pdpinch** [comment]
I updated the description based on https://github.com/mitodl/open-discussions/issues/948#issuecomment-411822233 and fixed then Zeplin link.
