### ISSUE TITLE
comment / post follow emails have misleading subject lines

### ISSUE THREAD

**Issue by aliceriot** [mitodl/open-discussions#974]
Just for kicks I am following a few posts on the production instance, and today I got an email with a subject starting like this:

![replycomm](https://user-images.githubusercontent.com/6207644/43268375-78a36d38-90be-11e8-86bb-be667545a7b4.png)

this is misleading for two reasons:

- I clicked 'follow' on the post, not on a comment
- the thing I was being notified of was a new reply to a top-level-comment, and I did not write the comment

I think we may want to think about clarifying this a little bit

**Comment by pdpinch** [comment]
Would a different subject line do the trick?

This is too long, but something like: `Reply to the post you are following: "post title"`

??

**Comment by aliceriot** [comment]
Yeah, something along those lines would be good

**Comment by pdpinch** [comment]
This should be fixed by #1066 

The plan is to use a subject with simply: Re: [`channel.title`] `post.title`
