### ISSUE TITLE
MIT Open Terms of Service and Privacy Policy

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#985]
Currently we link to the MicroMasters Terms of Service. Instead, we should link to an MIT Open Terms of Service. 

There is an [InVision mock-up](https://projects.invisionapp.com/share/MYIA6FAKU83#/screens/318515823_Privacy_Statement) and a [Google Doc with the raw copy](https://goo.gl/YEB3pB). The copy has been reviewing by MIT legal.

### acceptance criteria:
- [ ] create page in open-discussions app for terms of service and privacy policy
- [ ] update link in footer
- [ ] update link in sign-up screens

**Comment by pdpinch** [comment]
I updated the description with a link the copy, and some acceptance criteria.

**Comment by pdpinch** [comment]
replaces #935

**Comment by rhysyngsun** [comment]
@pdpinch where should the privacy policy be linked from? We currently don't have any links to any privacy policy of any kind

**Comment by pdpinch** [comment]
For now, the Privacy Policy is just a tab off of the Terms of Service. However, I think we may end up adding additional, direct links to the page footer and to email footers.
