### ISSUE TITLE
Use the material menu component for sorting posts and comments

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#987]
... instead of the native browser `<select>` input 

### acceptance criteria
- [ ] update channel page (above list of posts)
- [ ] update detail page (above list of comments)

**Comment by aliceriot** [comment]
should we go for the 'standard' one here? https://jamesmfriedman.github.io/rmwc/select-menus

**Comment by aliceriot** [comment]
here's what that looks like:

![material-dropdown-thing](https://user-images.githubusercontent.com/6207644/44593566-bc892080-a791-11e8-873b-121a70820a4a.png)

**Comment by pdpinch** [comment]
I'm not sure where the underline is coming from. I don't see it in [the spec](https://material.io/design/components/menus.html#exposed-dropdown-menu).

But it's still better than what we have now, so I say let's go for it.

**Comment by aliceriot** [comment]
is the component here more what we're looking for? https://jamesmfriedman.github.io/rmwc/menus

there's a few different material components which allow some sort of selecting-type behavior to happen, we can use whichever one is the best for our use-case.

**Comment by pdpinch** [comment]
Oh wait. I was looking at the (Drop Down) Menu and your were suggesting an Input Select. 

I can't tell if the rmwc implementation of menus supports the "Exposed Drop Down Menu" from material.io. If it doesn't maybe we should stick with the Input Select Menu.

**Comment by aliceriot** [comment]
this link here let's us set whatever display we want for the currently selected item, it just implements the actual menu part: https://jamesmfriedman.github.io/rmwc/menus

so I think we can use that to easily implement what appears in the mocks, assuming it implements the kind of menu we want.

**Comment by aliceriot** [comment]
btw for the material.io menus, if you look here: https://material.io/design/components/menus.html#implementation the web version of the component is listed as 'under development'
