### ISSUE TITLE
Channel header with channel banner and channel avatar

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#989]
As a channel owner, I want to see my branding reflected in the channel page. 

See https://invis.io/9EN908ZQPAX#/311617692_Channel_ClimateX and [Zeplin mockup](https://app.zeplin.io/project/5b181d3bf71408ae4d406b94/screen/5b60e6947d6f9ad509224cee)

### acceptance criteria
- [x] Display channel banner when there is one
  - [x] the banner should always be 105 pixels tall, at all screen widths
  - [ ] when the screen is too narrow to show the full banner width, left-align it
- [x] Transparent background when there is no channel banner
- [x] Display channel avatar when one was uploaded
- [x] Display channel initials avatar when there isn't an avatar uploaded
- [x] Display channel headline, if there is one (see #1094)

### related issues
- #927 Channel Settings: banner image and avatar image
- #990 Add channel tabs to channel template

**Comment by pdpinch** [comment]
I updated the broken InVision link in the description.

**Comment by pdpinch** [comment]
I added another acceptance criteria for the channel headline. 

I also added a link to Zeplin to the description.

**Comment by aliceriot** [comment]
going to do as part of my PR for #1137
