### ISSUE TITLE
Add channel tabs to channel template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#990]
As a channel owner, I want to customize my channel with additional tabs. 

For MVP, we will only display the default "Posts" tab. 

![tabs](https://user-images.githubusercontent.com/125561/43417536-3e64350a-9409-11e8-960b-e123a0807190.png)

https://invis.io/9EN908ZQPAX#/311617692_Channel_ClimateX

### acceptance criteria
- [ ] Add the "Posts" tab
- [ ] Add "All" label on the left
- [ ] no search box for MVP
- [ ] align widgets (rightmost column) with the channel tabs instead of the 1st post

### related issues

- #987 Use the material menu component for sorting

**Comment by pdpinch** [comment]
I fixed the broken link in the description and added a few acceptance criteria (no search box & aligning widgets)

**Comment by pdpinch** [comment]
Blocked until we get some design guidance on default banners and avatars

**Comment by aliceriot** [comment]
this element appears in the design for the post page too:

![tags](https://user-images.githubusercontent.com/6207644/44874536-7b00e580-ac69-11e8-97b4-169b9947ac24.png)

**Comment by aliceriot** [comment]
I think it will be easiest to do this as part of #1137 

what is this still blocked on?

**Comment by pdpinch** [comment]
I was waiting to get the design finalized (in particular, the specifics in #1156). That's clear now. 

It would be great if this were part of #1137.

**Comment by aliceriot** [comment]
cool, will do
