### ISSUE TITLE
Link names to Profile in Post cards and comment cards

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#993]
As a user, I'd like to find out more about the people who make posts and comments. 

Link the user avatar and name in posts and comments to the user's profile page.

**Comment by pdpinch** [comment]
@ferdi do we need to think about privacy settings on profiles? I don't think we need it yet,  since name, profile image and and headline are already displayed on every post. There isn't much more to see on the profile.

**Comment by aliceriot** [comment]
- [ ] compact post display
