### ISSUE TITLE
Use reddit API to determine link domains

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#995]
On post cards and details pages, we include the domain name to help users understand the source of a link. Currently, we're extracting the link domain ourselves. It would be more consistent to use the url as returned from reddit, in `submission.domain`

**Comment by aliceriot** [comment]
if we think we'll be moving away from reddit at some point there might be an argument to avoid doing this, unless there's an issue with the current code to extract the domain in the frontend

**Comment by aliceriot** [comment]
just becauase it's another dependency on reddits implementation details

**Comment by mbertrand** [comment]
I agree with @aliceriot

**Comment by Ferdi** [comment]
@aliceriot @mbertrand  ok.  Can we fix an issue with the current domain names:

The domain name for https://www.nytimes.com/2018/07/23/science/gorongosa-animals-environment.html 
should be "nytimes.com" , not "www.nytimes.com"

**Comment by aliceriot** [comment]
I think we could probably address that with a regex or something along those lines

**Comment by mbertrand** [comment]
@ferdi do you want to remove just `www.` or all subdomains like `store.nytimes.com`?

**Comment by Ferdi** [comment]
@mbertrand just www
