### ISSUE TITLE
Google Analytics for each channel

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#997]
As a channel owner, I'd like to be capture web traffic with Google Analytics for later review. 

Similar to what we did for MicroMasters, we can set configure a GA account for each channel. Page events for the channel page and any detail pages should be sent to the appropriate GA account. 

### acceptance criteria
- [x] add a GA UA id to the channel model
- [x] admin only UI for now
- [x] include the channel GA UA in the channel list page and on all post detail pages within the channel
- [x] confirm that page view events are recorded 
- [x] allow for multiple channels to use the same GA UA for aggregating channel analytics

**Comment by rhysyngsun** [comment]
probably relevant: https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers

**Comment by mbertrand** [comment]
@pdpinch in the micromasters code, it looks like `course.models.Program` has a `ga_tracking_id` field, used like this in a template:
```
    {% if ga_tracking_id %}
      ga('create', '{{ ga_tracking_id }}', 'auto', 'programPageTracker');
      ga('programPageTracker.send', 'pageview');
    {% endif %}
```

It should be pretty straightforward to take a similar approach in discussions, adding `ga_tracking_id` to the `channels.models.Channel` model and including the appropriate javascript on the relevant pages.

**Comment by mbertrand** [comment]
@pdpinch what about creation & management URL's like:
`/create_post/publicchannel2`
`/manage/c/edit/publicchannel01/basic/`
